### ISSUE TITLE
[Request] Add option to save DIC console output into a log file.

### ISSUE THREAD

**Issue by nightson** [SabreTools/MPF#131]
I always save whatever DIC outputs in the console for future reference. Could you add an option in DICUI to automatically save DIC output into a log file?

For example:
MYSTJ.log
```
N@N-PC E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI
# DiscImageCreator.exe cd j MYSTJ.bin 8 /c2 /s 2
AppVersion
        x86, AnsiBuild, 20181022 162920
/c2 val1 is omitted. set [4000]
/c2 val2 is omitted. set [0]
CurrentDirectory
        E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI
WorkingPath
         Argument: MYSTJ.bin
         FullPath: E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI\MYSTJ.bin
            Drive: E:
        Directory: \Program\Media\Dumping\DiscImageCreator\Release_ANSI\
         Filename: MYSTJ
        Extension: .bin
StartTime: 2018/12/31(Mon) 07:24:03
Set the drive speed: 1411KB/sec
This drive supports [OpCode: 0xd8, SubCode: 0]
This drive supports [OpCode: 0xd8, SubCode: 1]
This drive supports [OpCode: 0xd8, SubCode: 2]
This drive supports [OpCode: 0xd8, SubCode: 8]
Checking reading lead-out -> OK
Checking SubQ adr (Track)  1/ 1
Checking SubRtoW (Track)  1/ 1
Reading DirectoryRecord   14/  14
Set OpCode: 0xd8, SubCode: 8(Raw)
LBA[-00001, 0xffffffff]: Q[4101000000000000017404a1]
Checking SubQ ctl (Track)  1/ 1
Creating .scm (LBA) 327090/327090
No C2 errors
Copying .scm to .img
Descrambling data sector of img (LBA) 327089/327089
Exec ""E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI\EccEdc.exe" check "E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI\MYSTJ.img""
FILE: E:\Program\Media\Dumping\DiscImageCreator\Release_ANSI\MYSTJ.img
Checking sectors (LBA) 327089/327089
[NO ERROR] User data vs. ecc/edc match all
Creating bin, cue and ccd (Track)  1/ 1
Calculating hash: MYSTJ.scm [769315680/769315680]
Calculating hash: MYSTJ.img [769315680/769315680]
Calculating hash: MYSTJ.bin [769315680/769315680]
EndTime: 2018/12/31(Mon) 07:35:33
```

**Comment by mnadareski** [comment]
Most of the outputs are captured individually in the many, MANY output files that DIC outputs. Output redirection from the console is something that we will be exploring as we get the full output redirected to our window.

**Comment by Jakz** [comment]
@mnadareski  which output is currently not redirected to the log window? I was investigating the code, we should be able to mimic output to `LogWindow `also to a file with some proper management for parsing of `\r` hacks used by DIC but for general output (so when no dump is currently being made) we should use a separate main log file which could complicate things.

**Comment by mnadareski** [comment]
I think it's just the dump status and how far it got doesn't always get captured. Honestly, I can't think of anything else that ISN'T captured in all 50 output files.

**Comment by mnadareski** [comment]
Though not strictly going to a log, having the output go to the log output which can then be saved is a reasonable compromise.

**Comment by nightson** [comment]
> 
> 
> Though not strictly going to a log, having the output go to the log output which can then be saved is a reasonable compromise.

Thanks for the hard work! I still think saving the output to a log file would be a nice touch because it enables us to have an quick overview of what was happening during the dumping process without looking though the individual logs.
