### ISSUE TITLE
[Request] Rar/Zip packaging

### ISSUE THREAD

**Issue by diego-rbb-93** [SabreTools/MPF#22]
As i told you time ago Reign, i would like to ask for an option to automatically package the whole dump and the logs on a (single/separated? Dont care too much) Rar or Zip file (dont care too about the format, what you see easy or better).

This option is basically interesting for casual dumpers that want to colaborate and share but dont have time for submitting or whatever reason, so they just upload the whole materia generated from the dumping process.

No rush on this, just wanted to leave the request formally done over here. Thanks so much for all your work buddy.

**Comment by reignstumble** [comment]
Now that we have a single file where every necessary information is dumped, I'm not sure this would still be necessary. Tell me what you think diego-rbb-93.

Thanks

**Comment by diego-rbb-93** [comment]
Oh man, ive lost track of this while ive been out. How does DICUI deal with the generated contents now?

At the end of the next week ill back to the Discord group and to dumping so i will check how DICUI does things now and give you my opinion xd

**Comment by mnadareski** [comment]
The situation now is that a file called `!submissionInfo.txt` is created that contains a template for all of the information that needs to be submitted, along with any values that it could populate automatically from the DiscImageCreator outputs. If a custom set of inputs is used, it makes its best guess as to what needs to be included.

**Comment by mnadareski** [comment]
@diego-rbb-93 I realize that this has been lingering for a very long time. I don't feel it would be a good fit right now to add packaging of the logs and auxiliary files since it adds some unnecessary overhead to DICUI. Does the `!submissionInfo.txt` file work for what this original issue was for?
