### ISSUE TITLE
[Problem] UI does not adapt to lower resolutions

### ISSUE THREAD

**Issue by Kreeblah** [SabreTools/MPF#230]
I just got started with DICUI since it has a form for generating submission data for Redump, but I noticed an interesting issue on my computer with 1.17.1: when the UI has the log window displayed, the top of the UI runs off the screen, and when the submission data form is displayed, that runs off the bottom of the window.

I imagine a lot of this has to do with the fact that I'm running the UI in a VM.  I run Macs, so I don't have a ton of options here.  However, in order to get better font and graphic smoothing, Macs run have displays which are natively 2x the width and height of the resolution used by the OS, and then scales up text and graphics with interpolation to smooth them out.

The reason why this matters is that VMWare natively configures Windows to do this, too, in order to make things readable.  My default resolution in my Windows VM is 2560x1440 with a 200% scaling factor (effectively 1280x720).  I can force it back to 100%, but it displays 1:1 with the physical display then, and everything is microscopic.  And since it's already filling the bulk of my display (after taking into account screen space for the VMWare UI, the system dock, etc.), I don't have a ton of space to bump up the scaled resolution.

So, is there any chance that a future version might be able to detect when the UI won't fit vertically on the screen, and have some sort of alternative like a side-by-side thing?  If nothing else, running off the side of the screen instead would be easier to deal with in terms of being able to grab the title bar to move the window around.

**Comment by mnadareski** [comment]
For better or worse, getting a more adaptive UI is not in the cards right now. Until we get someone who is much MUCH better at UI than I am, I'm not sure there's going to be a chance to the layout. I know this isn't the best answer, but I will keep this open for a while in the hopes that someone else who uses DICUI can assist with this.

**Comment by mnadareski** [comment]
Thanks to some help from UI person, I've finally learned about things like stack panels and tabbed windows. As such, most of the UI should be lower resolution friendly, finally. Please test it out to see if it works for your case.

**Comment by mnadareski** [comment]
I'm going to mark this as done for now. If any other accessibility issues arise, a new issue should be opened.

**Comment by Kreeblah** [comment]
I just gave this a go, and the layout is totally usable in my VM.  Thanks for looking into it!
