### ISSUE TITLE
[Problem] Crash to desktop while dumping Crysis Warhead / Crysis Wars

### ISSUE THREAD

**Issue by azw71** [SabreTools/MPF#232]

**Comment by azw71** [comment]
steps to reproduce:
- Put Crysis Warhead or Crysis Wars into drive
- Select IBM PC Compatible/DVD-Rom and start dump.
- after reading the complete dvd program crashes

I'm using a Plextor PX-755a drive with firmware 1.08

**Comment by azw71** [comment]
Windows error reporting entry in Eventviewer/application Log:
Fehlerbucket , Typ 0
Ereignisname: CLR20r3
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: DICUI.exe
P2: 1.17.1.0
P3: 85e388a9
P4: mscorlib
P5: 4.8.4220.0
P6: 5f03a9e2
P7: 6606
P8: 10a
P9: System.FormatException
P10:

**Comment by mnadareski** [comment]
A few pieces of information that I'd like for you to provide, since this is unfortunately not that helpful. Please try to address them in the order I have here, since this will help me help you better:
- What version of DICUI are you using? The log seems to indicate 1.17.1. If that's the case, please try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/dicui/build/artifacts) to see if that's still happening.
- Have you tried with any other discs? Is it specifically Crysis Warhead and Crysis Wars that this was happening with?
- Did you remove the disc immediately after dumping completed?
- Can you try disabling copy protection scan in the options and see if it still happens.

**Comment by azw71** [comment]
- I used the actual release version 1.17.1 for this issue. I tested the WIP build from yesterday, same issue
- tested with https://github.com/jmalarcon/DotNetVersions:
C:\Portable\Tools\DotNetVersion>DotNetVersions.exe
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
- I dumped several disc the last days, none of had this issue, only Crysis Warhead and Crysis Wars.
- no, I didn't remove the disc after dumping
- the crash is gone with disabled copy protection scan

**Comment by azw71** [comment]
probably a different issue occured after dumping "Two Worlds" today. In the generated file !submissionInfo.txt is a debug log embedded:

Copy Protection:
	Copy Protection:

Path could not be scanned! System.IO.IOException: Unzulässige Funktion.



   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()

   bei System.IO.FileSystemEnumerableIterator`1..ctor(String fullPath, String normalizedSearchPath, String searchCriteria, String userPath, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)

   bei System.IO.FileSystemEnumerableIterator`1.Clone()

   bei System.IO.Iterator`1.GetEnumerator()

   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

   bei BurnOutSharp.ProtectionFind.Scan(String path, Boolean includePosition, IProgress`1 progress)

   bei DICUI.Utilities.Validators.<>c__DisplayClass6_0.<RunProtectionScanOnPath>b__2() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:Zeile 1040.

   bei System.Threading.Tasks.Task`1.InnerInvoke()

   bei System.Threading.Tasks.Task.Execute()

--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   bei DICUI.Utilities.Validators.<RunProtectionScanOnPath>d__6.MoveNext() in C:\projects\dicui\DICUI.Library\Utilities\Validators.cs:Zeile 1038.

**Comment by mnadareski** [comment]
From the errors I'm seeing above, it looks like the disc is either becoming unreadable or is being removed before or during scanning. Does it sound like the disc is spinning down when it starts doing the scan? Or does Windows indicate any issues with the drive after?

I'm having a bit of a hard time trying to figure out a way around this beside just disabling copy scan (which is a major source of disc reads after dumping).

**Comment by mnadareski** [comment]
It's been a while and the last full release also included changes to the protection scanning library. Can you please retest and see if that fixed the issue you were seeing?

**Comment by mnadareski** [comment]
I'm going to call this closed as a similar issue (linked above) was fixed as well. If this comes up again, please open a new issue.
