### ISSUE TITLE
[Request] Pull supported media speeds

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#236]
My F drive (USB) is a 4012, so max speed of 40x.
But DICUI still detects:
Supported media speeds: 1,2,3,4,6,8,12,16,20,24,32,40,44,48,52,56,72

Could be a problem on my side (drive on USB with Ugreen adapter).

Not a real problem, just in case something must be checked on your side.

**Comment by mnadareski** [comment]
Yeah, unfortunately a known issue... because it doesn't *actually* detect speeds for a drive. It has a list of speeds internally that it pulls from for each media type. I'm going to convert this to a request, since *actually* pulling that data is outside of what I know how to do right now.

**Comment by mnadareski** [comment]
This is not feasible with how things are going for MPF. If this is possible in the future, then this can be reopened.
