### ISSUE TITLE
[Request] Output Filename = Output Directory when you change the Output filename

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#239]
Default: when disc is inserted and scanned, output filename is chosen automatically by DICUI, then output directory is filed with "Default Output Path"\"output filename without extension". Great.

When you change the Output filename, Output directory is not updated accordingly. This is normal.
But could you add an option that also update automatically the Output directory according to the new Output filename given by the user ?
It is better to write something only once, instead of twice ;)

**Comment by sadikyo** [comment]
If you decide to add this, please do not make it default or automatic.  I know myself and others have systems that don't use this structure.

**Comment by mnadareski** [comment]
I'm going to say, this is slightly niche for my liking. The default output path is meant as just that: a reasonable default. If a user decides to change the name of the file, as sadikyo was saying, I'm not sure how many people would expect it to also automatically adjust the path. *If* this is something that someone else wants to work on as an option, I'll leave this here for them. It seems simple in practice, I just don't think it's a good fit.

**Comment by mnadareski** [comment]
Due to the complexities of how paths are handled, especially with broader dumping program support, I am going to have to deny this feature request outright.
