### ISSUE TITLE
[Request] To keep track of the window location of DICUI

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#243]
It will be useful, if it is possible to do.

Example:
I have 2 screens, and want DICUI on to show on the right screen. So I move the windows to it.
But every time I reopen DICUI, it shows on the left screen, centered, instead of the last location used (on the right screen).

Window.WindowStartupLocation ?

**Comment by mnadareski** [comment]
This is likely not going to be happening as this is already 2 years old. If this is a required feature, then it can be reopened.
