### ISSUE TITLE
[Problem] With new DIC 20201101 - read PVD from _mainInfo.txt

### ISSUE THREAD

**Issue by Madroms** [SabreTools/MPF#244]
With new DIC 20201101, the read of _mainInfo.txt to retrieve PVD is broken.

I only check 1 PS2 CD disc, 1 Saturn disc and 1 DVD VIDEO disc with the new version of DIC. More tests are needed with other discs to validate this piece of code.

On GetPVD function, you may replace most of the code by doing this search:

```
// Searching for Check Volume Descriptor
while (!(line = sr.ReadLine()).StartsWith("========== Check Volume Descriptor ==========")) ;

// Read the next line so the search goes properly
line = sr.ReadLine();

// Make sure we're in the area
if (!line.StartsWith("========== LBA[000016, 0x00010]: Main Channel =========="))
   while (!(line = sr.ReadLine()).StartsWith("========== LBA[000016, 0x00010]: Main Channel ==========")) ;

// We assume the first non-LBA0/4 sector listed is the proper one
// Fast forward to the PVD
while (!(line = sr.ReadLine()).StartsWith("0310")) ;

// Now that we're at the PVD, read each line in and concatenate
string pvd = "";
for (int i = 0; i < 6; i++)
    pvd += sr.ReadLine() + "\n"; // 320-370

return pvd;
```

**Comment by Madroms** [comment]
You can also use the same code for GetSegaHeader

**Comment by mnadareski** [comment]
Please attach a copy of the failing `_mainInfo.txt` files, when you have a chance. I somewhat knew the new DIC's additions would break something.

**Comment by Madroms** [comment]
Here are 3 of them.
[test_PVD_saturn_disc (1)_mainInfo.txt](https://github.com/SabreTools/DICUI/files/5473366/test_PVD_saturn_disc.1._mainInfo.txt)
[test_PVD_DVD_VIDEO_disc (1)_mainInfo.txt](https://github.com/SabreTools/DICUI/files/5473368/test_PVD_DVD_VIDEO_disc.1._mainInfo.txt)
[SLPM-60239 (1)_mainInfo.txt](https://github.com/SabreTools/DICUI/files/5473370/SLPM-60239.1._mainInfo.txt)

**Comment by mnadareski** [comment]
Since the newest DIC might have some issues, I'm putting this bug on ice for a bit. I will still try to investigate the best way to address this as time goes on, but it's less likely to be soon or before the next release of DICUI.

**Comment by mnadareski** [comment]
This is kinda addressed as of https://github.com/SabreTools/MPF/commit/a183a1ec916554611161362410290948735d8a31 but I'm leaving this open just in case the last stable DIC does even something weirder.

**Comment by Madroms** [comment]
Great!
I think you also need to modify GetSegaHeader

**Comment by Madroms** [comment]
I just found it doesn't work for multisession discs as it is not on LBA 16.
like on my lastest dump: ========== LBA[061271, 0x0ef57]: Main Channel ==========

So maybe you could add 2 searches:
if LBA 16 found =>  ok
if not search for (seems to be on CD and DVD):
0000 : 01 43 44 30 30 31 01 00  20 20 20 20 20 20 20 20   .CD001..        
I don't know if you can rely on this 2nd pattern for every discs.

**Comment by mnadareski** [comment]
Hey @Madroms can you see if this is still an issue with latest WIP builds?

**Comment by mnadareski** [comment]
Closing this as I think this has been fixed and broken multiple times over by this point. It should be in the "fixed" state as of now.
