### ISSUE TITLE
Malwarebytes says it is malware

### ISSUE THREAD

**Issue by rpatrick1** [SabreTools/MPF#245]
Hello

Just to let you know, Malwarebyte has just identified DICUI.Avalonia.dll as malware on my computer.

**Comment by requiemninja** [comment]
That's due to MBAM utilizing machine learning to detect 'anomalous' programs. Simply a false positive. 
Details here: https://blog.malwarebytes.com/detections/machinelearning-anomalous-100/

**Comment by mnadareski** [comment]
Honestly, with Avalonia being super experimental, I'm pretty sure that this will fall by the wayside as Avalonia gets removed at some point.
