### ISSUE TITLE
[Request] Configure a default system when MPF is unable to detect the system of a disc

### ISSUE THREAD

**Issue by meemo** [SabreTools/MPF#246]
**Is your feature request related to a problem? Please describe.**
I am dumping a large amount of CD/DVD PC games and it it gets annoying to hunt for IBM PC Compatible from the systems list every time I dump a game.

**Describe the solution you'd like**
An option for a default system in the options menu (possibly in the path category). The best implementation I can think of is a drop down like in the main DICUI window where you select a system. This system will then be automatically be set if DICUI/MPF cannot detect the system of the disc.

A more permanent solution could be to improve detection for IBM PC Compatible discs, but that's far more work.

**Comment by mnadareski** [comment]
I'm adding "Help Wanted" to this because I don't have a good way of fitting this into the UI. The settings, sure, but not the actual options window.

**Comment by mnadareski** [comment]
It can be forced in the config file using the `DefaultSystem` setting as of https://github.com/SabreTools/MPF/commit/d3d225644dc1c2387b7fe0278b0d6d831aaa1b76
