### ISSUE TITLE
[Request] "Label/L1 Mould SID" Greyed out on DVD-5 discs

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#247]
Some DVD-5 discs have Mould SID codes on the label side despite not being dual-layer. 
This option should be available for these instances.

**Comment by mnadareski** [comment]
Yeah, I guess. I technically have it so everything single-layer only has those things enabled. DVD-5, BD-25, and HD-DVD-15 all probably have a similar issue.
