### ISSUE TITLE
Cannot build - CS0246 - unknown Schemas, TrackTypeTrackType, CICMMetadataType and so on

### ISSUE THREAD

**Issue by Arrrrrrachno** [SabreTools/MPF#248]
**Version**
What version are you using? 

tried github master and 1.18

**Build**
What runtime version are you using?

cannot build --> no runtime used, but 4.8 is installed

**Describe the issue**
I try to build the project with Visual Studio 2019 Community Edition and it fails in [MPF/DICUI].Library\Aaru\Parameters.cs.
It complains with CS0246 in different lines, first one is in line 14, the next in line 2201.
In general it cannot find "Schemas" and a lot of data types like TrackTypeTrackType, TragFlagsType and so one.

Probably because of [MPF/DICUI].Library is failing to build, everything else could not be build, too (dependencies). Thus all 5 projects failed.

**To Reproduce**
1. download and extract fresh/clean copy of source 
2. open solution file with Visual Studio 2019 Community Edition
3. wait until everything is downloaded and setup
4. try to compile

**Expected behaviour**
no errors on build

**Additional context**
I tried to find a solution online, but "Schemas" is not a very good word to search for. And with other words like "TrackTypeTrackType" I had zero hits. There is probably missing some source code, but in wiki (https://github.com/SabreTools/MPF/wiki/Build-a-Local-Copy) there is nothing additional -- as far as I can see. In shorts it's written the "to Reproduce" steps.
What am I missing?

**Comment by mnadareski** [comment]
I should probably add a mention there, but you need to run `git submodule init` to pull down the required project. This isn't a bug, but I do consider it an oversight in my documentation, so I'll leave this open until I fix it.

**Comment by mnadareski** [comment]
I've updated the documentation accordingly. Sorry for missing that step in the instructions.
