### ISSUE TITLE
[INFO] DIC-Only Dump Output

### ISSUE THREAD

**Issue by Whovian9369** [SabreTools/MPF#250]
When running DIC by itself (specifically the debug build), there's less files output.
Example CD dump's output file list:
```
gamecube_cd_fina.bin
gamecube_cd_fina.c2
gamecube_cd_fina.ccd
gamecube_cd_fina.cue
gamecube_cd_fina.img
gamecube_cd_fina.scm
gamecube_cd_fina.sub
gamecube_cd_fina_20201230T103045.txt
gamecube_cd_fina_img.cue
```

Also a request: Add an "Info" template to the New Issue template file.

**Comment by mnadareski** [comment]
First part addressed in https://github.com/SabreTools/MPF/commit/3a490cfc8d2439ed4df3eefc1be0be7b0f71c0b9
Second part addressed in https://github.com/SabreTools/MPF/commit/f27040cd1c7e941548dba92687fe3c59641fd67e
