### ISSUE TITLE
[Info] Cleanrip BCA not properly output in submissionInfo with MPF Check

### ISSUE THREAD

**Issue by Whovian9369** [SabreTools/MPF#251]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
- .NET Core 3.1 has known limitations, so make sure that what you're giving information on isn't already in another build.
- Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.

If none of those apply, then continue...

**Is your information related to one of the dumping programs supported or something that isn't a bug in the code? Please describe.**
When using MPF Check to generate submissionInfo from CleanRip info on (at least) a GameCube disc dump, BCA is output in way that Redump "New Disc" form does not accept.

**Additional context**
BCA in the output submissionInfo.txt:
```
Extras:
	BCA: 00000000000000000000000000000000000000000000000000004b47534345ce17202e
```

Original BCA file with via `xxd` hex editor/viewer:
```
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 4b47 5343 0405 ce17 0200 020e  ....KGSC........
```

What I submitted to Reedump and was accepted (`xxd` BCA output, without offsets and ASCII output section):
```
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 4b47 5343 0405 ce17 0200 020e
```

**Comment by mnadareski** [comment]
I know this may be difficult, but can you also check to see if just the 32-character wide strings also work? For example, using the BCA above:
```
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
000000004b4753430405ce170200020e
```

If that is the case, then it is similar to how the PIC data needed to be formatted,
