### ISSUE TITLE
[Request] Generic parsing

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/MPF#253]
This is more of a note for myself for the future, possibly related to `dd`.

Is it possible to have it so that a generic image, something like an ISO, IMG, or BIN/CUE can be processed *without* the rest of the input files? Basically, if something is input, try to read as much information as possible from it, including hashes, PVD, and the like.

This would be good so that things like PSP dumps not using UIC, dd dumps, etc. could also have submission information generated, albeit not to the same level of quality as something from a supported tool.

As an addendum, porting over some of the hashing code from SabreTools will be required as a part of this, since there will be a lot of assumptions made with regards to external hashes only. This also will solve an issue that is not quite taken care of yet regarding the outputs from UIC.

**Comment by sadikyo** [comment]
This would be awesome.  +1.

If you could "load" an image and have it read as much of this type of information into an output file, that would be really cool.

**Comment by mnadareski** [comment]
Due to more refined aims of MPF and the removal of dd for Windows, I am considering this fully out of scope now.
