### ISSUE TITLE
[Problem] Copy protection gets stuck scanning DLL/MPQ files on Diablo II discs on 1.17+

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#254]
**Version**
What version are you using? 

- [X] Stable release (1.17, 1.17.1, 1.18)
- [X] WIP release (1.18-480)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
Attempting to scan Diablo II discs ([http://redump.org/disc/25181/](url), [http://redump.org/disc/25182/](url), [http://redump.org/disc/43323/](url)) for copy protection results in MPF getting "stuck" on either the BINKW32.DLL file (1.17, 1.17.1) or the D2CHAR.MPQ file (1.18, 1.18-480). Drive appears to stop spinning. The same result occurs whether you do a full dump and scan, or if you just do "Scan for protection."

**To Reproduce**
1. Open the listed above versions of DICUI/MPF.
2. Dump one of the listed above versions (maybe more) of Diablo II.
2a. Alternatively do "Scan for protection" on the same discs.
3. Wait for it to dump/scan.
4. See that the log gets stuck on one of the listed files above.

**Expected behavior**
MPF should scan these discs properly for protection. It works fine on 1.16.1.

**Screenshots**
![image](https://user-images.githubusercontent.com/68273043/105377796-30d18380-5bd9-11eb-838c-fadb421e0300.png)
![image](https://user-images.githubusercontent.com/68273043/105377888-42b32680-5bd9-11eb-9d44-dfeba71080d5.png)

**Comment by mnadareski** [comment]
I linked this over to the proper GitHub. I can guarantee that it's only the MPQ files that are causing the issues, as I had to use external library code to scan inside of them and they are *slow*. I'll try to look into either reasons this is happening or disable MPQ scanning entirely until it can be worked out.

**Comment by mnadareski** [comment]
This has been fixed in BurnOutSharp. I'll close this issue once it gets into the MPF WIP builds.

**Comment by mnadareski** [comment]
Addressed as of https://github.com/SabreTools/MPF/commit/47b5bbe7e7ca80dc5bfd6a8314fd7c254637ad5d
