### ISSUE TITLE
[Problem] Check if sub-program executables exist

### ISSUE THREAD

**Issue by Nithanim** [SabreTools/MPF#256]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X ] WIP release (2957370f net48; basically all starting from d1529f42)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on (Windows 10)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
Before calling one of the included sub-programs (like DiscImageCreator.exe) it should be checked if they exist. Win10 Defender really enjoys deleting the new DiscImageCreator version. The "Start Dumping" button pretty much becomes a no-op then (except for a single log entry) and leaves you completely in the dark on why MPF does not work.

**To Reproduce**
1. Download a build with DIC version 20210102 on Windows 10
2. Extract MPF
3. Completely ignore the Windows notification (like all other useless notifications)
4. Press "Start Dumping"
5. Try multiple versions of MPF and wonder for a really long time why it won't do anything
6. Hate Windows

**Expected behavior**
An error message (in the logs) that the program executable is not where it should be.

**Screenshots**
None

**Additional context**
None

edit: Happy issue 256!

**Comment by mnadareski** [comment]
So this just recently came up from another user as well that DIC's latest version is getting erroneously flagged. The dev of DIC has already been notified, but yeah, that's probably a good idea to check.

**Comment by mnadareski** [comment]
Possibly addressed as of https://github.com/SabreTools/MPF/commit/999c4dceb59c6daf69b094c3e0dee8bce8c65bf6

**Comment by Nithanim** [comment]
There is at least an error message now but a bit less informational than I hoped.
![image](https://user-images.githubusercontent.com/2402064/105761815-dd9e5e80-5f53-11eb-8067-a9b5f00e512f.png)

**Comment by mnadareski** [comment]
What would you consider to be more informational? I picked wording that I felt captured the basics.

**Comment by Nithanim** [comment]
Sorry! I mean it is good that there is a error message now but i would not know what "the program" is. A relative path would have helped me tremendously to discover what was missing and then find out why.

**Comment by mnadareski** [comment]
Ah I see what you mean. I can add that info. One minute.

**Comment by mnadareski** [comment]
Seems like I missed a bit of a check that I had already accounted for long before. I'll clean up what I had.

**Comment by mnadareski** [comment]
Try out the changes in https://github.com/SabreTools/MPF/commit/101193cb78603fb8f7b7cb302cb460fb84b9e05d

**Comment by Nithanim** [comment]
Thank you very much! Looks great now.
```
Populating systems, 116 systems found.
Scanning for drives..
Found 1 drives: D
Trying to detect system for drive D.. unable to detect.
Trying to detect media type for drive D.. detected DVD-ROM.
Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24
Setting drive speed to: 24
Changed system to: IBM PC Compatible
Starting dumping process..
Error! Programs\Creator\DiscImageCreator.exe does not exist!
```

**Comment by mnadareski** [comment]
Okay, cool. Glad that worked out a bit better.
