### ISSUE TITLE
Generate !SubmissionInfo.txt for audio cds / discs mastered as audio cd

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/MPF#260]
Using a recent MPF beta.

**Comment by eubrunosilva** [comment]
videonow have this problem. I have here some disks and I can help debug/fix

**Comment by mnadareski** [comment]
@dizzzy77 Sorry, but I don't support beta versions of the dumping software.

@eubrunosilva I don't think your issue is related to this.
