### ISSUE TITLE
New Languages and Regions Support

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#266]
New languages and regions have been added to Redump's new disc utility.

Regions:
-Australia, Germany
-Bulgaria
-Estonia
-Export
-Iceland
-Lithuania
-New Zealand
-Serbia
-USA, Australia

Languages:
-Estonian
-Indonesian
-Icelandic
-Latin
-Latvian
-Lithuanian
-Macedonian
-Albanian
-Serbian

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/MPF/commit/3f3a1c9a442fe2e09d49ed072d4564805a87d4b1
