### ISSUE TITLE
[Problem] DVD-Video discs' protections are not being detected

### ISSUE THREAD

**Issue by Bigmanjapan** [SabreTools/MPF#279]
``MPF_2.0-net48`` doesn't detect protection in DVD-Video discs via ``Scan for protection`` feature although the discs are protected and their protections are properly described in the logs when the discs are actually dumped.

http://redump.org/disc/11720/

Taking this disc as an example. ``Scanning for protection`` doesn't detect anything.

Logs: https://mega.nz/folder/YaYVAIqJ#4debSlZWPKQBMfU0rx1Mqg

**Comment by mnadareski** [comment]
I think I misunderstood the original request the first time I read it. You're asking for the standalone `Scan For Protection` to detect the things that DIC outputs. Without a lot of retooling, this is not possible, as those are fully dependent on DIC outputting those values currently. Those are not being handled by BOS as outputs.

**Comment by mnadareski** [comment]
I will look into seeing if I can use the DVDAuth.exe executable bundled with DIC to get this output, but I can't guarantee that this is possible.
