### ISSUE TITLE
[Problem] MPF freezes when you open the about menu and switch to a different window

### ISSUE THREAD

**Issue by SilasLaspada** [SabreTools/MPF#284]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release 2.0-ebaf9539

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [ ] .NET Framework 4.8 running on (Operating System)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
When you open the about menu and switch to a different window, MPF freezes. You can unfreeze by switch to the about window of MPF using task manager.

**To Reproduce**
1. Go to Help
2. Click on About
3. Switch to another window

**Comment by mnadareski** [comment]
Clarification: do you mean freeze as in the About window becomes uninteractable? Or do you mean that main MPF window becomes uninteractable when the About window pops up? The latter is expected, the former is not (and couldn't be reproduced locally).

**Comment by SilasLaspada** [comment]
I mean that the About window becomes hidden, meaning I can't interact with the main window. I have to close the About window via task manager in order to interact with the main window again.

**Comment by mnadareski** [comment]
After trying this a few times, I'm not exactly sure how you got into this situation. It's supposed to be intentional that the main window isn't interactable until the info window is closed, though.

**Comment by SilasLaspada** [comment]
Fixed as of latest commit
