### ISSUE TITLE
[Problem] "Error in detecting media type: IMAPI2 recorder not supported" when trying to detect type for an Xbox disc.

### ISSUE THREAD

**Issue by InternalLoss** [SabreTools/MPF#288]
**Version**
What version are you using? 

- [x] Stable release 2.
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [x] .NET Framework 4.8 running on Windows 10
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
When an OG Xbox (or 360) disc is inserted into a Kreon drive running externally via my SATA->IDE converter, the tool defaults to DVD-VIDEO, with the error `Error in detecting media type: IMAPI2 recorder not supported`.

This also occurs in the WIP .NET 4.8 version.

**To Reproduce**
1. Insert the disc
2. Launch MPF
3. Observe the terminal
(NOTE, inserting disc OR pressing "Scan for Discs" both perform the same action)

**Expected behavior**
MPF selects type Xbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/30775249/122650175-49fb4380-d129-11eb-8928-af160cb1181c.png)

**Comment by mnadareski** [comment]
As this came up before, the IMAPI2 thing is something I can't work around until I move to another library for detection. However, I can have it check for `SEP13011042` as the name for an XBOX disc.
