### ISSUE TITLE
[Problem] Checking Redump against a dump fails when Redump is not available

### ISSUE THREAD

**Issue by InternalLoss** [SabreTools/MPF#289]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release Version 2.0-6d57a05f

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on Windows 10
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
I assume this is an issue with Redump checking as Redump is currently timing out - when completing a dump using the WIP version + Redump credentials, the program hangs and has to be forcibly closed.

**To Reproduce**
1. Either have redump.org be down, or point to a server that doesn't respond (Redump in this current time will just 503 time out eventually or not respond - **it still opens a TCP connection**)
2. Dump a disc
3. Wait for "No external tools needed to show in logs"

**Expected behavior**
App should gracefully time out (and maybe warn the user that redump.org was not accessible) after 5-10 seconds, and potentially show "Querying redump.org" while this occurs.

**Screenshots**

**Additional context**

**Comment by InternalLoss** [comment]
```
C:\Users\Inter>curl -vvv http://redump.org
* STATE: INIT => CONNECT handle 0x80008f888; line 1643 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x80008f888; line 1689 (connection #0)
* family0 == v4, family1 == v6
*   Trying 62.141.35.244:80...
* STATE: WAITRESOLVE => WAITCONNECT handle 0x80008f888; line 1771 (connection #0)
* Connected to redump.org (62.141.35.244) port 80 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x80008f888; line 1834 (connection #0)
* Marked for [keep alive]: HTTP default
* STATE: SENDPROTOCONNECT => DO handle 0x80008f888; line 1858 (connection #0)
> GET / HTTP/1.1
> Host: redump.org
> User-Agent: curl/7.71.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x80008f888; line 1929 (connection #0)
* STATE: DO_DONE => PERFORM handle 0x80008f888; line 2050 (connection #0)
* Mark bundle as not supporting multiuse
* HTTP 1.1 or later with persistent connection
< HTTP/1.1 503 Service Unavailable
< Date: Sun, 20 Jun 2021 12:38:00 GMT
< Server: Apache
< Content-Length: 359
* Marked for [closure]: Connection: close used
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache Server at redump.org Port 80</address>
</body></html>
* STATE: PERFORM => DONE handle 0x80008f888; line 2240 (connection #0)
* multi_done
* The cache now contains 0 members
* Closing connection 0
```

cURL logs from trying to GET http://redump.org/ for reproduction.

**Comment by mnadareski** [comment]
Turns out, the default timeout for requests is 100(!) seconds. I wasn't aware of this. I'll set a much more reasonable timeout to fix this.
