### ISSUE TITLE
MPF Cant dump CD-Rom disks

### ISSUE THREAD

**Issue by Zopolis4** [SabreTools/MPF#293]
**Version**
What version are you using? 

Stable release (2.0)

**Build**
What runtime version are you using?

.NET Framework 4.8 running on (Windows 10)

**Describe the issue**
When trying to dump an IBM-PC Compatible CD-Rom, the console complains about missing additional files from the output.
[console.log](https://github.com/SabreTools/MPF/files/6799494/console.log)

**To Reproduce**
1. Insert a IBM-PC Compatible CD-Rom disk
2. Select IBM-PC Compatible
3. Select Start Dumping

**Expected behavior**
The CD-Rom would dump as expected.

**Comment by Whovian9369** [comment]
Are you sure this is the right log file? It appears to have completed properly?

> Scanning for drives..
> Found 1 drives: D
> Trying to detect system for drive D.. detected IBM PC Compatible.
> Trying to detect media type for drive D.. Detected Unknown.
> Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24
> Setting drive speed to: 24
> Starting dumping process... Please wait!
> Look for the separate command window for more details
> Executing DiscImageCreator... please wait!
> DiscImageCreator has finished!
> Running any additional tools... see log for output!
> No external tools needed!
> Gathering submission information... please wait!
> Extracting output information from output files...
> Running copy protection scan... this might take a while!
> 
> ...
> 
> Copy protection scan complete!
> Extracting information complete!
> Waiting for additional disc information...
> Additional disc information added!
> Formatting information...
> Formatting complete!
> Writing information to !submissionInfo.txt...
> Writing complete!
> Compressing log files...
> Compression complete!
> Submission information process complete!
This... worked tho?

**Comment by Zopolis4** [comment]
I saw no submission info screen, no files were dumped, and at the end of the log in red (it was cut from the log) is this:
`There were files missing from the output:
ISO\Rescue Helicopte\Rescue Helicopte.ccd
ISO\Rescue Helicopte\Rescue Helicopte.cue
ISO\Rescue Helicopte\Rescue Helicopte.dat
ISO\Rescue Helicopte\Rescue Helicopte.img
ISO\Rescue Helicopte\Rescue Helicopte.sub
ISO\Rescue Helicopte\Rescue Helicopte_img.cue
ISO\Rescue Helicopte\Rescue Helicopte.img_EdcEcc.txt
ISO\Rescue Helicopte\Rescue Helicopte.scm`

**Comment by mnadareski** [comment]
The likely case is that whatever drive you are using isn't supported by DiscImageCreator, the program that MPF uses to dump discs by default. Please see [this list](http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility) for more details about supported drives.

**Comment by Zopolis4** [comment]
Ah, that would be it.
