### ISSUE TITLE
[Request] Show read only fields in "Disc Information" window 

### ISSUE THREAD

**Issue by SilasLaspada** [SabreTools/MPF#301]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're asking for isn't already in another build.
- Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.

If none of those apply, then continue...

**Is your feature request related to a problem? Please describe.**
After I dump a disc, sometimes I get annoyed that I have to close the Disc Information window to be able to read information about a disc such as error count or PVD, meaning I have to finish writing the metadata in the text file itself.

**Describe the solution you'd like**
I'd like for there to be read only fields in the Disc Information window containing information such as error count and PVD.

**Describe alternatives you've considered**
Closing the Disc Information window and finishing the submission in the text file.

**Additional context**

**Comment by sadikyo** [comment]
This would be a nice enhancement - whether it shows in a separate tab or wherever, I think it would be handy.  It'd also be a quick test to see if there was a problem with collecting information that should be there.

**Comment by mnadareski** [comment]
This has been started as of the recent WIP builds. Not all fields are represented yet.
