### ISSUE TITLE
[Request] Allow entering tab character in all ring codes fields.

### ISSUE THREAD

**Issue by nightson** [SabreTools/MPF#303]
**Is your feature request related to a problem? Please describe.**
In some rare cases, even Mastering SID, Mould SID and Toolstamp have wide spacing between characters. However, pressing tab  in the ring codes section of MPF will only move the focus to the next field unless you're in the mastering codes field.

**Describe the solution you'd like**
Pressing tab should insert an tab character.

**Describe alternatives you've considered**
I like being able to tab through text fields without the need to mouse click anything so maybe we can assign a hotkey for entering a tab character? 

**Additional context**
Some examples:
http://redump.org/disc/65166/
http://redump.org/disc/80647/

**Comment by mnadareski** [comment]
I'm looking at https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.textboxbase.acceptstab?view=windowsdesktop-6.0 for this and it seems like this is an either-or scenario. I'm marking this as needing help because I see the value in both having tab navigation _and_ tabs in the fields.

**Comment by mariomadproductions** [comment]
> As an addendum to that, would it be troublesome to add the ability to Ctrl+Tab or Shift+Tab or something like that to skip to the next field like normal?

I think this would be a good idea, although as you will be moving fields more often then inserting tabs, I think it should be reversed: shift-tab to insert tab, tab to move to the next field.

**Comment by meemo** [comment]
How about using replacement character sequences that will be replaced with a tab character when processed? Here are some examples that would work:

 - `\t`
 - ` \t ` (one space on each side)
 - `<tab>`
 - `   ` (three or more spaces in a row)

This should be fairly trivial to implement, while still allowing for tab navigation to work without having to add a modifier key,

**Comment by mariomadproductions** [comment]
> How about using replacement character sequences that will be replaced with a tab character when processed? Here are some examples that would work:
> 
> * `\t`
> * `\t` with one space before and after it
> * `<tab>`
> * Three or more spaces in a row
> 
> This should be fairly trivial to implement, while still allowing for tab navigation to work without having to add a modifier key,

I think that'd work well as well although the program should make it obvious when its done a replacement to avoid accidental replacements.

**Comment by sadikyo** [comment]
I think converting automatically both:
<tab>
and
[three spaces]

would definitely be helpful.

I'm a bit hesitant on \t because that is more likely to at least potentially be on a ring, and I could see people getting confused if typing

RINGCODE\t123

because it kind of runs all together.

but....

RINGCODE<tab>123
or
RINGCODE <tab> 123
or
RINGCODE   123   [3 spaces]

I could see converting.

**Comment by fuzz6001** [comment]
Isn't the current official tabulator `<tab>`?
http://wiki.redump.org/index.php?title=Ring_Code_Guide
Is this guide outdated?

Why do you guys try to use other methods? (`\t`, 0x09 and multiple spaces)

**Comment by NovaSAurora** [comment]
Because a lot of people don't read. It's about 50/50 `<tab>` vs triple-space

**Comment by fuzz6001** [comment]
It's not about submissions, it's about the discussion here.

**Comment by sadikyo** [comment]
> Isn't the current official tabulator `<tab>`? http://wiki.redump.org/index.php?title=Ring_Code_Guide Is this guide outdated?
> 
> Why do you guys try to use other methods? (`\t`, 0x09 and multiple spaces)

`<tab>` is certainly the easiest way to describe to someone what a ring should look like.  Dumpers can submit information either with `<tab>` or with the ACTUAL tab character.  In fact, having the actual tab character in the text string is even easier for mods.  The redump system does not parse automatically, so we have to do that manually with every single dump.

**Comment by fuzz6001** [comment]
> In fact, having the actual tab character in the text string is even easier for mods. The redump system does not parse automatically, so we have to do that manually with every single dump.

Ahh... I didn't know that.
