### ISSUE TITLE
EXE Date does not populate in full for Saturn discs

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#305]
**Version**
What version are you using? 

- [X ] WIP release (2.1-656)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
When saturn discs are dumped, the header now populates correctly in the submission file, but the EXE date appears to only partially populate.  For example, I have a submission where the EXE date should be 1995-09-09 [which matches the header], but only "1995-09-" populates in the EXE date field.

**To Reproduce**
1.  Dump a saturn disc

**Expected behavior**
The EXE date populates and agrees with the date in the header

**Screenshots**
Can send if needed.

**Additional context**
Let me know if you have any questions!

**Comment by mnadareski** [comment]
With latest WIP, this does not seem to be occurring. Reminder that older versions of DIC are not supported unless otherwise specified.
