### ISSUE TITLE
[Problem] 2.1-656 - cannot write !submissionInfo.json.gz after successful DiscImageCreator completion

### ISSUE THREAD

**Issue by JakeW11** [SabreTools/MPF#306]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 
- [x] WIP release (2.1-656)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on (Windows 10 Pro 20H2)

**Describe the issue**
**!submissionInfo.json.gz** write failure after DiscImageCreator successfully completes.

**To Reproduce**
1. Go to 'MPF'
2. Click on 'Tools -> Options -> Dumping' - check all of these checkboxes:
![image](https://user-images.githubusercontent.com/90137593/132125551-af1652f5-a4e3-40c1-9135-d69e5a488b43.png)
3. Select 'Start Dumping' in MPF.
4. Disc image (DVD-Video in this case) successfully completes - however there is an error in the log output:

Scanning for drives..
Found 2 drives: H, N
Trying to detect system for drive H.. detected DVD-Video.
Trying to detect media type for drive H.. Detected DVD-ROM.
Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24
Setting drive speed to: 24
Starting dumping process... Please wait!
Look for the separate command window for more details
Executing DiscImageCreator... please wait!
DiscImageCreator has finished!
Running any additional tools... see log for output!
No external tools needed!
Gathering submission information... please wait!
Extracting output information from output files...
Extracting information complete!
Waiting for additional disc information...
Additional disc information added!
Formatting information...
Formatting complete!
Writing information to !submissionInfo.txt...
Writing complete!
**Writing information to !submissionInfo.json.gz...
Writing could not complete!**
Compressing log files...
Compression complete!
Submission information process complete!

**Expected behavior**
**!submissionInfo.json.gz** should write successfully.

**Screenshots**

**Additional context**

**Comment by mnadareski** [comment]
Can you check to see if there are any over-large files in the output? For example, any 100+ MB non-image files?

**Comment by JakeW11** [comment]
![MPF-Log](https://user-images.githubusercontent.com/90137593/132241269-111db294-64d2-420c-990c-a68a7fa9038e.GIF)

Checked - no large files in the output.

**Comment by mnadareski** [comment]
Finally tracked down the cause of this and testing out a fix.

**Comment by JakeW11** [comment]
Thank you! Working now.
