### ISSUE TITLE
"Help" Menu doesn't show up in MPF on Win 7, and update check fails on startup

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#313]
**Version**
What version are you using? 

- [X] Stable release (2.1)
- [X] WIP release (2.1-676)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
On Windows 7, the "Help" menu doesn't seem to appear in MPF, and on the latest WIP build (which does an automatic update check on startup), the update check fails.  Other users tested with Win10, and the help menu shows on Win10 and update check works.

**To Reproduce**
1. Open MPF
2.  Watch update check fail (in 2.1-676)
3.  Look for the Help menu (any version of MPF)
4.  Cry when you don't find it

**Expected behavior**
A Help menu is expected to appear, and the update check is expected to work.

https://media.discordapp.net/attachments/461797735427735562/892508416961024010/unknown.png?width=508&height=572

**Comment by mnadareski** [comment]
Unfortunately, because of the potentially flaky support for .NET Framework 4.8 on Win7 now that it's out of support, I'm not sure I can do much about this. I'll close this as a won't do. If someone else wants to maintain older versions of .NET for this purpose, I won't stop anyone.
