### ISSUE TITLE
MPF does not HTTP encode passwords appropriately for redump.org

### ISSUE THREAD

**Issue by InternalLoss** [SabreTools/MPF#314]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release Version 2.1-0e5d8af0
**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on Windows 11w
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
Trying to log into redump.org in MPF settings fails, as the latest build does not HTTP encode passwords.

**To Reproduce**
Select Tools, and Options
Navigate to Login Info
Enter a password with special characters
Try to login

**Expected behavior**
"Redump credentials accepted", as present on 2.1

**Screenshots**

**Additional context**
I checked in Wireshark, and the stable version correctly encodes my password; latest does not.

**Comment by mnadareski** [comment]
This _was_ fixed before but apparently I undid it by accident.
