### ISSUE TITLE
[Request] Can MPF Generate Software/Hardware descriptions for what is used to dump, in the submission file?

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#315]
**Is your feature request related to a problem? Please describe.**
Not really a 'problem' - just that it might be nice to see this info consolidated.

**Describe the solution you'd like**
I think it'd be helpful, if MPF could extract the MPF version, DIC version, and Hardware used for dumping a particular dump, and put that in the submission file.  This way, mods and users could easily see exactly what was used for that particular dump, which is sometimes helpful with troubleshooting / reviewing issues / etc.

**Describe alternatives you've considered**
The info is in the various log files, so we can dig around and find it if we need to.

**Additional context**
If this is difficult or "not worth it" ok, that's fine - we can at least get the info somehow.

**Comment by mnadareski** [comment]
Software addressed as of https://github.com/SabreTools/MPF/commit/1dd5c0d6d0b07526a3851d03da2ef73338f17311
Hardware addressed as of https://github.com/SabreTools/MPF/commit/e7c36c104a2813a6b129bbd0b8c6917c63b272c6
