### ISSUE TITLE
[Request] Use 7Z (or other format) for compressed logs in MPF.

### ISSUE THREAD

**Issue by InternalLoss** [SabreTools/MPF#316]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're asking for isn't already in another build.
- Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.

If none of those apply, then continue...

**Is your feature request related to a problem? Please describe.**
As Redump's forum only accepts files under a certain size, a lot of people upload their logs to Discord (which has an 8MB limit for non-paying users), or another cloud storage platform.

**Describe the solution you'd like**
Being able to change the compressed log format from `zip` to `7z` (or another format, if 7z is unsuitable), as zip files are typically not compressed as well as `7z` files.

**Describe alternatives you've considered**
- Manually decompressing and re-compressing to 7Z

This "works", but gets very annoying when you have to do for multiple discs.

**Additional context**
I understand that changing the format for everyone would result in people requiring software to extract their log files (whereas ZIP is supported in most modern OSes), so it might be a better idea to allow users to choose which format they'd like?

**Comment by mnadareski** [comment]
This has been brought up previously, but I am opting to stick with zip-only for the time being. I'll leave this open in case anyone wants to implement this (along with the required new setting to use either 7z or zip).

**Comment by mnadareski** [comment]
Implementing this is not going to be happening. The combination of `zip` for logs and `.gz` for large submission info JSON files is sufficient. There are ways of repacking zips into 7z that can be done locally.
