### ISSUE TITLE
[Request] checking of language list items using only keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/MPF#317]
**Is your feature request related to a problem? Please describe.**

I am mostly dumping Japanese discs so I have to set region (easy using keyboard cursors or letter keys, followed by space bar) and languages (easy to open and select the row of the language, but I cannot check the box using keyboard)

I try to enter all submission data using only keyboard, resorting to mouse slows things down and makes me more error prone.

**Describe the solution you'd like**

Some way to check the language box.

Maybe I need educating in the finer operation of Windows?

**Describe alternatives you've considered**

Use mouse cursor to check it, this is prone to error as my mouse is controlled by touch surface which will sometimes scroll the languages list.

**Comment by mnadareski** [comment]
If this isn't natively supported with the WPF and WinForms code that is already in use, then unfortunately I can't tackle this one.
