### ISSUE TITLE
[Problem] If you close submission info window w/ Enter, you lose text in current field.

### ISSUE THREAD

**Issue by Intothisworld** [SabreTools/MPF#322]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [x] Stable release (2.1)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [x] .NET Framework 4.8 running on (Windows 10, 64-bit)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
I just noticed that some of my !submissionInfo txt files were missing entries that I know I'd punched in. Did some experimentation and realized that if you just press Enter to finalize the submission info window, whatever field you filled in last won't save to the txt file. I suspect that if you tab out of it or click into a new field beforehand, you'd be fine (haven't confirmed), but if you just finish your last entry and immediately press enter, you'll lose whatever text you just punched into that field. So far I've only confirmed this happening with the ringcode fields from audio CDs. I haven't been able to try any other ones, but will do with next disc I dump.

**To Reproduce**
1. Dump a disc.
2. Punch some text into a field (ringcodes are what I've seen myself so far)
3. Hit 'Enter' to close window.
4. Check !submissionInfo text file.

**Expected behavior**
The text to save to the Submission Info file.

**Screenshots**

**Additional context**

**Comment by mnadareski** [comment]
Possibly addressed by https://github.com/SabreTools/MPF/commit/9e4af1d66bf539d5e10d4b9743c7eacaa13f711c
