### ISSUE TITLE
[Request] IRD file creation for PS3 discs

### ISSUE THREAD

**Issue by SamRohod** [SabreTools/MPF#323]
**Is your feature request related to a problem? Please describe.**
Currently, creating IRD files for PS3 discs mostly requires a PS3. The program Redump2IRD ([HERE](http://forum.redump.org/topic/14035/various-ps3-tools/)) can make IRD files from a Redump .iso but needs:
1- Encrypted Disc key (D1)
2- Decrypted Disc ID (D2)
3- PIC data

**Describe the solution you'd like**
The program dumping the PS3 disc to the Redump .iso format with its companion IRD file. Or give the information needed to create the IRD with Redump2IRD.

1- For Encrypted Disc key (D1): Incorporate them into the program or allow the user to provide them (like [PS3 Disc Dumper](https://github.com/13xforever/ps3-disc-dumper)).

2- For Decrypted Disc ID (D2): Maybe through connection to the Redump database which I believe store it or if this could only be extracted with a PS3, set a default value of zeros or {check next section}.

If we set default value to zero's:
Encrypted Disc ID = Decrypted Disc ID
04EC7666382555DE33944D947DD64257 = 00000000000000000000000000000000 

3- For PIC data: I believe that MPF already extracts the needed PIC data since v2.0 as in the changelog it says "Add PIC layerbreak extraction".

**Describe alternatives you've considered**
I'm not an expert but in trying to understand the PS3 Disc ID (D2) I unpacked 2758 IRD files (downloaded from the now down jonnysp.bplaced.net) and all of them have the Data2 be one of the following:

Encrypted Disc ID = Decrypted Disc ID (with Redump2IRD) = Regions of games
04F9E7546E1035B2BDC9A7547553D332 = 00000000000000FF0002000000000000 = BD50(??)
508EA396776D0928E58D57469F30D059 = 00000000000000FF0002000100000001 = Asia / Japan *mostly*
2D1B1AAE18366BD5CE988BF81D6012FB = 00000000000000FF0002000300000001 = US *mostly*
19795F9BFBD8E3B8B317EDBF6071E728 = 00000000000000FF0002000400000001 = Europe *mostly*
6539A28E2D4311BCD16A7A675559305E = 00000000000000FF0002000600000001 = Europe *only*
5EBD7719383C4A0ACE8331FA74D7263E = 00000000000000FF0002000900000001 = US *only*
2647567752CA7A71243A1EEAA61F50C1 = 00000000000000FF0002000A00000001 = Europe *only*

It seems there is a limited number of PS3 Decrypted Disc ID (D2) that might relate to regions.

**Additional context**
What I am really interested in is the ability to convert between Redump .iso and JB format of my backups. The process that I use:

*To make a Redump .iso from JB folder:
1- Use [PS3 ISO Rebuilder](https://archive.org/details/ps3-iso-rebuilder-1.0.4.1) to build a .iso (plain header) with the proper IRD file.
2- Use [PS3Dec](www.romhacking.net/utilities/1456) with the proper Disc key to encrypt the resulting .iso from step 1

*To extract a Redump .iso to JB folder:
1- Use [PS3Dec](www.romhacking.net/utilities/1456) with the proper Disc key to decrypt the Redump .iso
2- Use [PS3 ISO Rebuilder](https://archive.org/details/ps3-iso-rebuilder-1.0.4.1) to extract the resulting .iso from step 1

So, an IRD file is needed. Even if the D2 and PIC data were wrong, Redump2IRD would still be able to create an IRD file that allows disc verification/rebuilding from JB folder (with [PS3 ISO Rebuilder](https://archive.org/details/ps3-iso-rebuilder-1.0.4.1)). But this will contribute to the spreading of these "sudo" IRD files that are useful for disc verification/rebuilding but might have random values for D2 and PIC data. That's why I suggested that the Decrypted Disc ID (D2) is to be set to zero's if the exact value is not obtainable through a PC dump. 

A more secure solution would be to use the last 8b of the IRD file in a new way. Instead of CRC and UID ([LINK](https://www.psdevwiki.com/ps3/Bluray_disc#IRD_file)), the last 8b of the IRD file would be encrypted. This encrypted section will have:

1- CRC of the unencrypted part of the IRD file (the part before the last 8b)
2- MPF signature only known to SabreTools.

A closed source "Checker" tool is to be used to verify:

1- The unencrypted part of the IRD has not been corrupted/modified by checking it against the CRC in the encrypted section.
2- The encrypted section of the IRD was not corrupted/modified by checking the MPF signature.
3- The IRD was created from an actual disc using MPF by checking the MPF signature. 

With this, we don't need to start a new format, just reusing the old format. Starting a new file format just for disc verification/rebuilding is just not worth it. Also, I believe that most programs that use IRD files (like PS3 ISO Rebuilder) will still work just fine since they don't use the last 8b in any important way.

Also, with this method we can easily verify that two dumps are the same by just comparing the two IRD files (because there is no UID). Increasing our confidence it's a correct dump (if they are the same).

[HERE](https://github.com/ifcaro/PS3-ISO-Rebuilder) is what seems to be the code for PS3 ISO Rebuilder (might be useful)

**Comment by mnadareski** [comment]
https://www.psx-place.com/threads/manual-ird-creation.33486/

**Comment by mnadareski** [comment]
https://github.com/Zarh/ManaGunZ/blob/fc38c4e7b46755eefa8bf30e236542506accbfa2/MGZ/source/ird_build.c#L74

**Comment by SamRohod** [comment]
@Deterous Sorry for the late response.
I'm sorry but unfortunately I'm not in anyway an expert in the matter. I just did some reading on the matter.

Here are somethings that might be useful:

- The [ManaGunZ](https://github.com/Zarh/ManaGunZ/releases) project has a database for IRD files [HERE](http://ps3ird.free.fr/) Since v1.41 that doesn't accept IRD files from older versions anymore.
- I used [ird_tools](https://github.com/Zarh/ird_tools) for unpacking IRD files. (it seems that it has been updated but not compiled)
- [THIS](https://www.psx-place.com/threads/jonnysps-ird-library-is-down.35178/) thread might have some interesting information and links regarding IRD files.
- I made [THIS ](https://github.com/ifcaro/PS3-ISO-Rebuilder/issues/1) request for the PS3-ISO-Rebuilder a while ago. I didn't make a request for fixing the rebuilding of "Hybrid Discs" because I don't fully understand them and I'm not sure if the problem with rebuilding them is from PS3-ISO-Rebuilder or from old style IRD files from ManaGunZ. (I believe the previously linked thread has some discussion on them)
- The Redump database for PS3 discs has Disc Key, Disc ID, and PIC in the Metadata section of each disc.

Sorry for not being able to be more helpful.

**Comment by Deterous** [comment]
Progress update: https://github.com/Deterous/LibIRD
- Uses an ISO and a key to generate an IRD, alternatively can accept an ISO and a .getkey.log file
- Deterministically generates all fields in an IRD except the region/file hashes, currently uses Null MD5sums instead.

Ideas for MPF:
- Create IRD using MPF.Check if .getkey.log is present and .ird is not
- Create IRD if (off-by-default) checkbox is selected, user is logged in, and the key can be pulled from redump
- Future: Allow manual key input (hex string message box UI)

**Comment by Deterous** [comment]
@SamRohod I have finished making the [IRD library](https://github.com/Deterous/LibIRD), work will soon be done to integrate it into MPF, towards the end of November.

**Comment by gmipf** [comment]
You could also just use ps3dec for proper iso to iso operations instead of using PS3 Disc Dumper and the rebuilder after that. No one should need to mess with JB folder stuff in this day and age any more since Cobras wide distribution today. Of course there is also RPCS3 which still has no iso support for whatever reason.

**Comment by Deterous** [comment]
> You could also just use ps3dec for proper iso to iso operations instead of using PS3 Disc Dumper and the rebuilder after that. No one should need to mess with JB folder stuff in this day and age any more since Cobras wide distribution today. Of course there is also RPCS3 which still has no iso support for whatever reason.

The main goal here is for integration with NKit (work in progress) which would provide more than just JB<->ISO and ISO<->ISO. RPCS3 is its own beast, hopefully the developers can figure something out. In the mean time, JB folders remain somewhat useful for rare cases of rebuilding scene-only dumps.

**Comment by gmipf** [comment]
> In the mean time, JB folders remain somewhat useful for rare cases of rebuilding scene-only dumps.

Yes there I agree. Also rebuilding isos where we only have redump entries but not the actual dump, rebuilding with ird can sometimes help generating the og iso. Scene releases also sometime has modified eboot with their own intro screens.

**Comment by Deterous** [comment]
@SamRohod 
Finally, I have completed the IRD library such that non-contiguous files are hashed correctly. This is better than 3k3y ISOTools, Redump2IRD and ManaGunZ which all get these file hashes incorrect. It is also much faster than Redump2IRD for large ISOs.

I also have a command-line tool for creating IRDs, printing info about them, and even doing a diff to compare two IRD files: https://github.com/Deterous/LibIRD/releases/tag/0.4.0
You can create IRDs from just the ISO by running `irdkit.exe create game.iso`

There will be a UI window added to MPF soon after MPF 3.1 releases. There will also be an option to enable IRD creation after PS3 dumping, however this won't occur by default.

**Comment by SamRohod** [comment]
@Deterous
Thank you very much for your efforts.

There is no "issues" section on the LibIRD repository, so please excuse the use of this page to mention the following.

I did a test with the LibIRD command-line tool using the ISO of [THIS GAME](http://redump.org/disc/29509/):
I inputted the encrypted .iso file (matching the SHA-1 from Redump) into the tool. This is what I got:
```
C:\IRD TEST>irdkit.exe create "Dragon's Crown (USA).iso"
Creating Dragon's Crown (USA).ird with Key from redump.org: 50A0D50CE393F1DCA504070BC473951A
Split file detected: PS3_GAME\USRDIR\INST\DRACRO.CPK
Dragon's Crown (USA).iso contains split files: detected 11 out of 12 expected files
IRD saved to Dragon's Crown (USA).ird
```
Then I downloaded the IRD file for the same game (BLUS30767) from the [ManaGunZ IRD DATABASE](http://ps3ird.free.fr/)
Using [ird_tools](https://github.com/Zarh/ird_tools) to extract the json files from both IRD files I found that there are mismatches:

1- Mismatches in the values of: MGZ_SIG, MD5, EXTRA_CONFIG, UNIQUE_ID, CRC, DATA2_DEC, DATA2_ENC.
I mentioned all of them because I don't know which ones are expected to be different given the tool's goal of creating deterministic IRD files.

2- Mismatch with the file: "/PS3_GAME/USRDIR/INST/DRACRO.CPK"
I decrypted the ISO with [PS3dec](https://www.romhacking.net/utilities/1456/) then checked the decrypted ISO with [PS3-ISO-Rebuilder](https://archive.org/details/ps3-iso-rebuilder-1.0.4.1) against the two IRD files. It seems the IRD created by the LibIRD tool is the incorrect one. While properly recreating the ISO using the IRD file downloaded from the ManaGunZ IRD Database can be done, the IRD file produced from the LibIRD tool can't be used with PS3-ISO-Rebuilder for this purpose.

**Comment by Deterous** [comment]
@SamRohod 
Thank you for testing it, those ISOs with split files are what needs testing and I only tested one. Likely something I've done to try "fix" non-contiguous files has caused a bad side effect on ISOs that were working.
I've also now enabled the issues tab.

When comparing ISOs, you can also use `irdkit diff game1.ird game2.ird` which will print the different fields.
Actually, ,most of the values you mentioned being different are expected, it is only the file hash that is the problem.
EXTRA_CONFIG: irdkit sets this to 0x0000001 so that you know the IRD was creating using LibIRD.
UNIQUE_ID: As the name suggests, this should be unique. But LibIRD sets this to the CRC of the ISO.
CRC: This is the hash of the IRD itself, will always be different if the IRDs are different
DATA2_DEC/DATA2_ENC: LibIRD uses a fixed value for these currently.

**Comment by Deterous** [comment]
Solved it - an error that only shows up for split files where the split file filesize is not a multiple of 2048.
I'll release a version 0.4.1 which should fix this, thanks for testing!

**Comment by SamRohod** [comment]
@Deterous 
It now works with everything I tested it on!!!!!

* Regarding DATA2/Disc ID:-
**1-** Is it possible to parse the value from Redump.org (like it is done for the keys)? or maybe manually inputted?
since adding the hashes of these IRD files to Redump.org is a goal, we wouldn't want there to be a difference between their contents and the Redump.org database (unless there is a mistake in the database already)
**2-** I'm not sure what is optimal to do with the Disc ID's that end with "XXXXXXXX", which seem to be most of the discs (Exceptions [1](http://redump.org/disc/73076), [2](http://redump.org/disc/12246/)). But I have nothing to say here given that I don't even know why these X's are there. I just wanted to point them out so that we would find some standard for translating them in the IRD deterministically (especially if manual input is to be added).

* Regarding PIC:-
I don't know how relevant this is, but in Redump.org there are extra 34 digits (always zeros?) that all IRD files don't include.


Thank You

**Comment by Deterous** [comment]
Disc ID: Yes, this is something I have been considering, whether to pull from redump, logs, allow manual input. Currently, I set the Data 2 Key for all IRDs created to be a single fixed value for all single layer discs. The reason for this is reproducibility, as a disc from e.g. UK can have a Disc ID of 00000000000000FF00020004XXXXXXXX and a disc from Australia with a matching ISO can have a Disc ID of 00000000000000FF00020006XXXXXXXX So to make a 1:1 correspondence, all single layer discs have a Disc ID of 00000000000000FF00020000XXXXXXXX regardless of their region. If you want to fix this yourself, you choose the region and change that one byte. As for the X's, they exist because those last 4 bytes are unique for each disc, so are redacted
 They are replaced with 00000001 as per the 3k3y standard that ISOTools does when making IRDs.

PIC: The real PIC is actually much larger on real discs, it's just that the useful information (and for PS3, the only non-zero information) is located within the first 100 or so bytes. The IRD standard fixed it to 115 bytes for whatever reason. Redump has it higher, because redump stores more than just PS3 info. In fact, BD-Rs often have non-zero data in the PIC beyond what redump makes visible.

**Comment by mnadareski** [comment]
Not fully complete as of #647
