### ISSUE TITLE
[Request] Special text for CD-i dumping

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#329]
**Is your feature request related to a problem? Please describe.**
When you insert a CD-i disc into the drive, and select the platform, MPF will say that it can't detect a disc in the drive.

**Describe the solution you'd like**
If the CD-i platform is selected, mention that the disc is not detected by the OS, but that that is normal and you can continue if you want. I wasn't sure if MPF/DIC would even dump the disc, but I went ahead and it did it, so this would be helpful for people like me who have no idea it's possible to dump the disc if the host OS can't see it / read it.

**Comment by Whovian9369** [comment]
Text might be good to add for other platform discs, like those with only Mac HFS partitions for example.
