### ISSUE TITLE
[Request] Add an option to create disc file layout 

### ISSUE THREAD

**Issue by SamRohod** [SabreTools/MPF#330]
**Is your feature request related to a problem? Please describe.**
Whenever you extract (for example) a .iso file, putting it back together to recreate the original .iso 1:1 is difficult without the LBA layout of the files in the original .iso. Sometimes this is useful for modding or for emulation.

**Describe the solution you'd like**
Given that MPF probably already has some "understanding" of the discs that it can dump, Three things:

1- An option to create a file that has the layout/LBA data from disc/disc image.
Similar to how [Redump2IRD](http://forum.redump.org/topic/14035/various-ps3-tools/) does that for PS3 disc images

2- An option/side-program that can extract the files from the disc image.
For things like the padding in XBOX discs, the padding would be extracted to it's own file which can be re-merged later.

3- An option/side-program that can recreate the disc image from the extracted disc files using the layout/LBA data file.
For things like the encryption of PS3 discs, the user will have to provide the disc key

**Describe alternatives you've considered**
the latest [IsoBuster](www.isobuster.com) usually is capable of exporting the LBA data for disc image files.
I couldn't find any program that is capable of creating a disc image file based on LBA data. The only exception is [PS3 ISO Rebuilder](https://archive.org/details/ps3-iso-rebuilder-1.0.4.1) with the IRD files.

**Additional context**
Given that MPF extracts a lot of information about the discs while creating the dump, adding the disc layout is valuable.
Also, I made an issue post #323 that is just a specific case of what is in this issue post.

**Comment by mnadareski** [comment]
I like the enthusiasm here, but MPF is very dumb when it comes to the actual data. The programs that it invokes, such as DiscImageCreator and Aaru, do the bulk of the work when it comes to discs themselves.

As such, I don't think that it's within the bounds of this particular project to deal with reconstruction of disc images.
