### ISSUE TITLE
[Info]

### ISSUE THREAD

**Issue by hackwin** [SabreTools/MPF#331]
Please turn off the audio beep noises that occur from a command line pop-up program when image creation is successful.
I was told that it can be done that by adding the /q argument.

![image](https://user-images.githubusercontent.com/1328566/144770156-b33fad32-c560-4888-9900-56eb24d758ea.png)

**Comment by Feathered-Serpent** [comment]
You can disable that already.

Options -> DiscImageCreator -> Quiet Mode. That will add the /q

**Comment by hackwin** [comment]
I suggest making Quiet Mode the default

**Comment by mnadareski** [comment]
Because it's already an option, you can make it the default yourself. I'm not changing the default here.
