### ISSUE TITLE
[Request] MPF does not zip the CSSKey.txt from DVD-Video discs with the rest of the logs

### ISSUE THREAD

**Issue by tehguy** [SabreTools/MPF#333]
**Version**
What version are you using? 

- [X] Stable release 2.1-7f4921a4
- [X] WIP release 2.1-151402dc

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on Windows 10 x64
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
MPF does not zip XXX_CSSKey.txt with the rest of the logs

**To Reproduce**
1. Dump DVD-Video disc

**Expected behavior**
the .txt to be in the zip file

**Comment by mnadareski** [comment]
I'm keeping this open, but for now, this is intentional. There's a few files, like `DMI.bin` that are omitted because they fall in a gray zone.
