### ISSUE TITLE
[Request] More info in !submissionInfo.txt for Xbox 360

### ISSUE THREAD

**Issue by eubrunosilva** [SabreTools/MPF#334]
Hi

It's possible to place this code "US216302W08F11" (that is in DMI file - don't know the name of this - only an example for a code) in comments section in !submissionInfo.txt file?
mods are placing also this info in the comments section

**Comment by mnadareski** [comment]
This is being discussed right now about the best way to include this. This ended up as a slightly larger discussion, so this might stay open for a while.
