### ISSUE TITLE
[Request] Prevent unintended closing of Disc Information window when it opens to foreground

### ISSUE THREAD

**Issue by dutchcow** [SabreTools/MPF#335]
**Is your feature request related to a problem? Please describe.**
When dumping is finished the window to enter Disc Information opens to foreground. 

I had 2 times where the Disc Information window closed immediately because I pressed [enter] (or maybe [escape] or similar) that was intended for a different application in Windows. I did not want it to close but the window just popped up at the wrong moment and immediately handled the keyboard input to close the Disc Information window so I have to manually edit the values in !submissionInfo.txt (or start the dumping again).

**Describe the solution you'd like**
When the Disc Information window opens to foreground, block the input that closes the window like [esc] and [enter] for 0.5 second to prevent immediate unwanted closing of the window. 

**Additional context**
It's just a minor issue and there probably are more important things

**Comment by mnadareski** [comment]
For anyone else who runs into this before any sort of proper change is made, try enabling the "Show Eject Reminder" option so that there's at least a buffer between the dump being done and the submission popping up.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/9e4af1d66bf539d5e10d4b9743c7eacaa13f711c
