### ISSUE TITLE
[Request] Allow "Protection" field to be edited 

### ISSUE THREAD

**Issue by SilasLaspada** [SabreTools/MPF#340]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're asking for isn't already in another build.
- Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.

If none of those apply, then continue...

**Is your feature request related to a problem? Please describe.**
MPF currently offers no way of specifying the protection found field, so you have to manually edit the text file even if no protection is present, to remove the default text.

**Describe the solution you'd like**
I'd like for the "Protection" field to be able to be edited.

**Comment by mnadareski** [comment]
To sync back from Discord, this is going to take some thinking on, since it's not as easy as "just enable the field". I'd prefer if automatic protection data _isn't_ editable but if someone opted to avoid that scan and do it themselves instead it _should_ be.
