### ISSUE TITLE
MPF no longer handles '.' in Output Filename correctly

### ISSUE THREAD

**Issue by cdifan** [SabreTools/MPF#341]
**Version**
What version are you using? 

- [X] Stable release 2.2
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on Windows 10
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
When you type or paste a period '.' in the Output Filename field, MPF 2.2 no longer replaces it with an underscore '_', e.g. it does not change "XXX 1.0" to "XXX 1_0" (MPF 2.1 used to do this). As a result, after running DIC, MPF will complain about not finding output files because it will replace anything after the first period with the expected suffix, e.g. it will look for "XXX 1.cue" and "XXX 1_disc.txt" instead of the correct "XXX 1.0.cue" and "XXX 1.0_disc.txt" which are generated by DIC.

**To Reproduce**
1. Start MPG
2. Type e.g. "XXX 1.0" in the Output Filename field.
3. Insert a dumpable disc.
3. Click on 'Start Dumping'
4. Wait until DIC finishes
4. See red errors about missing DIC output files in Log Output field

**Expected behavior**
Either restore the previous behaviour (replace '.' with '_') in the filename) or (preferred solution) correct the DIC output file search to find the correct files.

**Additional context**
Everything works fine if you use e.g. "XXX 1_0" in the Output Filename. Also, there are no issues with period characters in the Output Directory field.

**Comment by mnadareski** [comment]
I'd like screenshots of both the UI before dumping when this comes up as well as a copy of what the log says after. I have an idea of what could be causing this issue, but I need to see the input before I'm sure.
