### ISSUE TITLE
Wrong Size BD-Rom detected

### ISSUE THREAD

**Issue by 7Seventy7** [SabreTools/MPF#345]
MPF detects BD-50 as BD-100 in media type

Using the latest 2.2 build.

here's my logs https://drive.google.com/file/d/1tHo0bOLUSm0sIZ50yAcKVmZrWq1UxGII/view?usp=sharing

**Comment by mnadareski** [comment]
Looking at the PIC data, there are 2 layerbreaks, as the submissionInfo would have shown if more than one layerbreak were accepted.

Using napkin calculations, I get the following:
```
Layerbreak 1
	Offset           =  131072
	Value            = 1658494
	Total            = 1527424
	Total (Adjusted) = 3,128,164,352

Layerbreak 2
	Offset           = 5767256
	Value            = 9474208
	Total            = 7294682
	Total (Adjusted) = 14,939,508,736

Layerbreak 3
	Offset           = 1010580540
	Value            =          0
	Total            = XXXXXXXXXX
	Total (Adjusted) = XXXXXXXXXX
```

Unfortunately, if the PIC is indicating this, there's not much else I can do. None of the DIC output files seem to have a layerbreak mentioned anywhere. Is it possible for you to rip this with Aaru and see if it comes up with different information?

**Comment by mnadareski** [comment]
When this commit builds, try it: https://github.com/SabreTools/MPF/commit/d83fed16f5804df223920bbc3b8ca9dcb14d8e21
