### ISSUE TITLE
[Request] Check INI Files for languages automatically?

### ISSUE THREAD

**Issue by majorpbx** [SabreTools/MPF#350]
Can MPF check INI files automatically for supported languages?

Example:

Symantec pcAnywhere CD has a "setup.ini" (not in the root directory) that contains sections (example below) for each supported language. Additionally, it has a section for "Languages" and sets the default. In this case "409" is English.

setup.ini example [sections] output:
`
[0x0409]
[0x0407]
[0x040c]
[0x0410]
[0x040a]
[0x041d]
[0x0416]
[0x0c0c]
[0x042d]
[0x0403]
[0x0405]
[0x0406]
[0x0413]
[0x040b]
[0x0408]
[0x040e]
[0x0414]
[0x0415]
[0x0816]
[0x0424]
[0x041b]
[0x0411]
[0x0419]
[0x0804]
[0x0404]
[0x041f]
[0x0401]
[0x041e]
[0x042a]
[0x0412]
[0x040d]
[0x0421]

[Languages]
default=409
`

**Comment by mnadareski** [comment]
Unfortunately, I'm not going to implement this at any point. I'd have to search every single INI on a disc if it's PC/Mac and then hope that developers were consistent about how they used sections. There's too much variation there to make it reasonable to automate, in my opinion.
