### ISSUE TITLE
[Problem] Internal Serial doesn't always generate correctly for Saturn discs

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#354]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release (2.2-794)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
For some Sega Saturn discs that have a slightly longer than "normal" internal serial, MPF is pulling a digit short. 

**To Reproduce**
Dump a saturn disc that has an internal serial of more than 8 digits.
MPF will only generate up to 8 digits.

**Expected behavior**
The full internal serial to generate.

**Screenshots**

**Additional context**
Example: http://redump.org/disc/80138/
The internal serial should be "610602001" as you can see in the Header.  MPF pulls "61060200"
I realize that *typically* saturn serials are 8 digits or less, but there are some like this.

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/MPF/commit/c0f6c072cea4a0c0085dc728900389cea2638ec0
