### ISSUE TITLE
[Problem] DVD Video with Xbox game gets detected as Xbox

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#362]
**Version**
What version are you using? 

- [* ] Stable release (2.3)

**Build**
What runtime version are you using?

- [* ] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
The MPF frontend detected a DVD Video disc (Indiana Jones in the Kingdom of the Crystal Skull, Disc 2 / Special Features) with an Xbox executable and folder as an Xbox 360 disc.

**To Reproduce**
1. Insert disc into drive
2. Click Detect Disc (or have the program do it automatically)
3. Take a drink

**Expected behavior**
In theory it should detect the VIDEO_TS folder and autoselect DVD Video, but since it sees an Xbox executable, it probably goes for Xbox 360 instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/71686027/152710785-07c7c1d7-879c-4d44-aefa-1cca65458b39.png)
![image](https://user-images.githubusercontent.com/71686027/152710795-731b23dc-f175-4768-a1ee-cb743a8a7cc4.png)

**Additional context**
I'm not certain if this also happens with DVDs with Xbox demos. I'll update this if I find a disc to test.

**Comment by mnadareski** [comment]
I'm leaving this open but asking for help. I can't think of any reasonable way to determine if it's just an X360 game that happens to have the `$SystemUpdate` folder on it or if it's a DVD-Video that has a bonus X360 demo.

**Comment by mnadareski** [comment]
Confirming from a second source that 500MB seems like a reasonable cutoff.
