### ISSUE TITLE
[Problem] Double Layer DVD Disc gets detected as Single Layer

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#363]
**Version**
What version are you using? 

- [ ] Stable release 2.3 

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.8 running on Windows 10

**Describe the issue**
I dumped The Penguins of Madagascar DVD [ http://redump.org/disc/87134/ ] to verify the disc, and it worked fine, but when I went to add the ringcode info, it only showed me enough fields for a single layer disc (Data and Label.)

The disc itself is 2.6GB, but it's a double layer disc for some reason. This is correctly detected by DiscImageCheck, and it's listed in the _disc.txt log.

I assume you're using the disc size to determine if the disc has more than one layer, which makes sense.

**To Reproduce**
1. Dump Penguins of Madagascar DVD disc
2. That's it, really

**Expected behavior**
I expected the ring screen to have enough fields for both layers.

**Screenshots**
![image](https://user-images.githubusercontent.com/71686027/152730643-1546d4f6-8035-4e6f-8eac-0179725f0fb5.png)

**Additional context**
Aaru media info:

```
F:\aaru-5.3.0_windows_x64>aaru media info g:
aaru 5.3.0
Copyright c 2011-2021 Natalia Portillo

Media has 1303978 blocks of 2048 bytes/each. (for a total of 2.487 GiB)
PFI:
Disc is a 120mm DVD-ROM version 1
Disc claims conformation to ECMA-267
Disc maximum transfer rate is 10,08 Mbit/sec.
Disc has 2 layers
Layers are in opposite track path
Pitch size is 0,147 µm/bit
Track size is 0,74 µm
Data area starts at PSN 30000h
Data area ends at PSN F7B7A9h
Layer 0 ends at PSN F96FFh

Lead-In CMI:
Disc is encrypted using CSS or CPPM.
Disc can be played in the following regions: 1
Media identified as DVDROM
```
DIC _disc.txt contents (abridged):

```
========== DiscStructure ==========
FormatCode: 00, Sendable:  No, Readable: Yes
FormatLength: 2052
========== PhysicalFormatInformation ==========
	       BookVersion: 1
	          BookType: DVD-ROM
	       MinimumRate: 10.08 Mbps
	          DiskSize: 120mm
	         LayerType: Layer contains embossed data
	         TrackPath: Opposite Track Path
	    NumberOfLayers: Double Layer
	      TrackDensity: 0.74um/track
	     LinearDensity: 0.293um/bit
	StartingDataSector:  196608 (0x30000)
	     EndDataSector: 16234409 (0xf7b7a9)
	EndLayerZeroSector: 1021695 (0xf96ff)
	           BCAFlag: No
```

**Comment by mnadareski** [comment]
Self-reminder: `line.Split`
