### ISSUE TITLE
[Request] Support for Definitive Articles in Titles for Alphabetization

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#365]
List of (known) Definitive Articles that get placed at the end of a dat title for alphabetization in Redump

A
An
The
Der
Die
Das
De
Los
Las
La
El
Il
Des
Du
Le
Les
L'
I (Italian only)

Note: Watch out for stuff like "Lights, Camera, Action" turning into: "A Lights, Cameraction"

**Comment by NovaSAurora** [comment]
Het

**Comment by NovaSAurora** [comment]
En
Ett

**Comment by NovaSAurora** [comment]
Honestly I should just post this link and call it a day
https://en.wikipedia.org/wiki/Article_(grammar)#Definite_article

**Comment by mnadareski** [comment]
Started as of https://github.com/SabreTools/MPF/commit/5870ad06732f3d9f3fc89c67833750ee3d8ce93b
