### ISSUE TITLE
[Request] Show drive make/model in drop-down

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#366]
**Is your feature request related to a problem? Please describe.**
I have multiple drives and often forget which drive letter is which drive.

**Describe the solution you'd like**
It would be lovely if the drop-down drive letter selector could also show the drive make/model, e.g. Plextor W4012TA.

**Describe alternatives you've considered**
Sticky labels on the drives!

**Additional context**
I hope this is not too tricky! Many thanks for this app.

**Comment by mnadareski** [comment]
Current framework makes this near-impossible due to reliance on strangely-written Windows-only libraries in the UI. I'll leave this open as a later suggestion.

**Comment by Feathered-Serpent** [comment]
Couldn't MPF access the Windows WMIC?

Command line:
wmic CDROM get Drive,Name

Result:
Drive  Name
D:     ASUS BW-16D1HT

**Comment by mnadareski** [comment]
This suggestion is being closed due to the nature of currently supported UI framework. If this changes in the future, it can be reopened.
