### ISSUE TITLE
[Bug] dr_ring_0_mo1 and dr_ring_0_mo2 typos?

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#376]
In the submissionInfo.json file, are `dr_ring_0_mo1` and `dr_ring_0_mo2` typos? All the other fieldnames start `d_`.

**Comment by mnadareski** [comment]
The best way to check is to look a the names of the fields in the Redump new disc form. If they don't match, then they're wrong either because the field names changed or I fat-fingered it.

**Comment by JohnVeness** [comment]
Thanks. I checked a New Disc form, but unfortunately they just have a large text box for the ring codes, not separate ones for individual components. In other words, the New Disc form has neither `dr_ring_0_mo1` nor `d_ring_0_mo1`.

**Comment by mnadareski** [comment]
I keep forgetting that the public new disc form is different than the internal one. Long story short: you are correct, it was me fat-fingering and then copy-pasting the names. It'll be fixed in a minute.

**Comment by JohnVeness** [comment]
Lovely, thank you. I am very intrigued about the alternative new disc form, though!

**Comment by mnadareski** [comment]
It's nothing secretive, just the staff gets a different New Disc form that is a bit more comprehensive.

**Comment by JohnVeness** [comment]
Ah OK, thanks. At the moment I'm using nightson's user script to parse the JSON into stuff suitable for the public newdisc form. It would be great if there was a publicly accessible interface to just inject the JSON directly, without all the fiddling!

**Comment by mnadareski** [comment]
Oh, we certainly wish there was either an API or any sort of consistency to it, but unfortunately, getting those changes to the Redump site are difficult at best.

**Comment by JohnVeness** [comment]
I understand. Thanks for your openness, and for your tolerance for this off-topic chat!

**Comment by mnadareski** [comment]
No worries, not all of this is obvious, especially when there's so many layers of abstraction going on between dumping your disc and having the metadata appear on the site.
