### ISSUE TITLE
[Request] Only gzip !submissionInfo.json if "Include Artifacts" ticked

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#379]
**Is your feature request related to a problem? Please describe.**
If "Include Artifacts" is not ticked, the !submissionInfo.json seems to be unnecessarily gzipped, as it's tiny already. If one is using nightson's user script to help fill in a New Disc form, one has to unzip the file first.

**Describe the solution you'd like**
For the !submissionInfo.json file to only be gzipped if "Include Artifacts" is ticked.

**Describe alternatives you've considered**
Continuing as currently, manually unzipping. It's obviously not a big chore, but a small "papercut" when you have to do it for a lot of discs! Thanks.

**Comment by mnadareski** [comment]
I like that as an idea. Thank you for suggesting it. I will very likely implement this.
