### ISSUE TITLE
[Problem] !submissionInfo.json and .txt disagree on DVD-5 vs DVD-9

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#381]
**Version**
What version are you using? 

- [x] Stable release (version 2.3)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on Windows 10

**Describe the issue**
After dumping a single-layer PC DVD-ROM, the two submission info files disagree on the disc type.

**To Reproduce**
1. Dump a single-layer PC DVD-ROM
2. Observe !submissionInfo.txt says `Media Type: DVD-ROM-5`, but !submissionInfo.json says `"d_media": "DVD-9"`.

**Expected behavior**
!submissionInfo.json say `"d_media": "DVD-5"`.

**Comment by mnadareski** [comment]
For better or worse, this isn't currently used anywhere so that information is using generic comparisons. I'll see what I can do to make it more accurate.
