### ISSUE TITLE
[Problem] Underlines removed from Status field

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#382]
**Version**
What version are you using? 

- [x] Stable release (version 2.3)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on Windows 10

**Describe the issue**
A minor cosmetic thing:

The status field removes the first underline symbol from the relevant Log Output line. If you hold down Alt, the letter after where the underline should appear, is underlined. I believe this is a Windows thing where it treats underline characters as shortcut keys. Hopefully there's a way to tell the field to not treat underlines like that.

**To Reproduce**
1. Dump a disc that has filenames containing underlines.
2. Compare Log Output with Status

**Screenshots**
![image](https://user-images.githubusercontent.com/2512915/162641056-b1844b9b-868a-44bd-b7a2-87ac76157097.png)

**Comment by mnadareski** [comment]
That's... an interesting one. I'll see what it takes to use the `_` character in labels.
