### ISSUE TITLE
[Info] What is the bar above the Log Output and below the Status?

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#383]
I'm just wondering what this bar is:

![Screen](https://user-images.githubusercontent.com/2512915/162641366-57f5305a-e3e4-4639-be5d-10153a55e8f4.jpg)

I've never seen anything appear in it...

**Comment by FoxhackDN** [comment]
If you hide the log output by clicking on the little arrow on the left, the text is displayed in that box instead.

**Comment by JohnVeness** [comment]
That doesn't seem to happen for me. If I click on the little arrow to hide the log output, that bar is hidden as well. And the output log text (whether or not the main log box is hidden) appears in the Status field above.

**Comment by mnadareski** [comment]
The bar is only used for when the console output is redirected. That's the only time that it can provide a progress bar. Feel free to ignore it for all other circumstances.
