### ISSUE TITLE
[Request] Include PIC.bin in BD-Video logs.zip

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#385]
At the moment PIC.bin is excluded from being zipped into logs.zip, I am unsure if this is intentional or not, but it feels like a weird exclusion.

**Comment by mnadareski** [comment]
Was intentional, reason doesn't matter anymore, fixed in https://github.com/SabreTools/MPF/commit/1b016e591564804d983a1c08e058f08a44e1c67e
