### ISSUE TITLE
MPF freezes and I have to force-close when inserting certain PS1 discs

### ISSUE THREAD

**Issue by Rot-gut** [SabreTools/MPF#386]
When I put in certain PS1 discs (NTSC-U version of Cool Boarders 3, Lunar: Silver Star Story Complete Discs 1 & 2), MPF freezes completely with a spinning blue circle and I have to force close it. This seems to only happen with CD-ROMs and not DVDs.

Windows is able to "open" disc via Computer and explore the files without an issue.

Drive being used: HL-DT-ST BD-RE WH14NS40 USB Device (LG Blu-ray Writer in USB Enclosure)

This is what I see, but can't be interacted with because it stops responding with spinning blue circle:

![MPF_DiscFreeze](https://user-images.githubusercontent.com/93231997/170535448-095cfa48-467f-4d04-8ebe-67bfd7d2f018.png)

**Comment by FoxhackDN** [comment]
I have a WH16NS40 drive installed on my PC and it doesn't like some discs; it will either hang and not be able to read it or I'll be forced to kill Explorer to get the drive out. DVDs _or_ CDs.

My suggestion is to turn off type and system detect, and just set it manually so MPF doesn't hang like it does right now. The feature gave me a lot of problems so I turned it off ages ago. If the file name is important, then insert the disc, and hit scan for discs, and that _shouldn't_ cause a hang.

**Comment by mnadareski** [comment]
If you get a chance, please try the latest WIP build.

**Comment by Rot-gut** [comment]
> I have a WH16NS40 drive installed on my PC and it doesn't like some discs; it will either hang and not be able to read it or I'll be forced to kill Explorer to get the drive out. DVDs _or_ CDs.
> 
> My suggestion is to turn off type and system detect, and just set it manually so MPF doesn't hang like it does right now. The feature gave me a lot of problems so I turned it off ages ago. If the file name is important, then insert the disc, and hit scan for discs, and that _shouldn't_ cause a hang.

Thanks, skipping the type and system detect seemed to fix the issue. With some CD-ROMs I get the following error followed by a little beep melody. Does that just mean the WH16NS40 doesn't support this type of PS1 CD-ROM ripping?

![MPF_ERRORScreenshot 2022-05-26 121114](https://user-images.githubusercontent.com/93231997/170560262-fafd8e29-7a5c-4f8d-999d-63517e534132.png)

**Comment by FoxhackDN** [comment]
> Thanks, skipping the type and system detect seemed to fix the issue. With some CD-ROMs I get the following error followed by a little beep melody. Does that just mean the WH16NS40 doesn't support this type of PS1 CD-ROM ripping?

Yup. It works for some discs, but doesn't for others, depending on the lead-out. I used it for some verifications and for DVD dumping before I got a Plextor and a separate external drive for DVDs.

**Comment by Rot-gut** [comment]
> > Thanks, skipping the type and system detect seemed to fix the issue. With some CD-ROMs I get the following error followed by a little beep melody. Does that just mean the WH16NS40 doesn't support this type of PS1 CD-ROM ripping?
> 
> Yup. It works for some discs, but doesn't for others, depending on the lead-out. I used it for some verifications and for DVD dumping before I got a Plextor and a separate external drive for DVDs.

Is there an ideal place to get a Plextor? I saw this big list but wasn't sure where to start or where to look.

http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility

**Comment by sadikyo** [comment]
There isn't really any consistently reliable place to buy these as they aren't sold anymore, so you have to buy them from third party markets - ebay, facebook, craigslist, mercari, etc.  Sometimes you can find third-party listings on amazon and such.  If you keep monitoring ebay for a while, eventually you can usually find one for a decent price.

**Comment by mnadareski** [comment]
Unfortunately, this seems like it was a drive-specific error and not really something that I can deal with on the MPF side.
