### ISSUE TITLE
[Request] Auto-update DIC

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#388]
**Is your feature request related to a problem? Please describe.**
The bundled version of DIC gets out of date. MPF has an update notification for the full app, but not of DIC, and there have been several releases of DIC since the last MPF release.

**Describe the solution you'd like**
MPF to detect/notify (and ideally, update to) new releases of DIC.

**Describe alternatives you've considered**
Alternatively, maybe you could release a new version of MPF (with the new bundled DIC) each time there's a new DIC release.

At the moment I maintain and update DIC separately, but I'm thinking about the more casual user.

I'm aware the same could apply to Aaru but I don't use that myself so I don't know how their release cadence compares to MPF's.

**Comment by mnadareski** [comment]
DiscImageCreator has a track record of having breaking changes between versions. I cannot, in good faith, have an auto-update for DIC knowing that there is a high likelihood that flags and/or outputs have changed.

**Comment by JohnVeness** [comment]
That's fair enough. Maybe the maintainer of DIC could give you some heads up before a new release.
