### ISSUE TITLE
There were files missing from the output

### ISSUE THREAD

**Issue by ironsniper1** [SabreTools/MPF#389]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET Core 3.1 and .NET 5.0 have known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [X] Stable release (version here)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.7.2 running on (Operating System)
- [ ] .NET Framework 4.8 running on (Operating System)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
trying to backup some original xbox games and as soon as i click start dumping i get an error about a missing .dat file, i did use mpf to make backups of some ps2 games without issue

**Comment by mnadareski** [comment]
If you don't have a compatible drive for Xbox discs, such as a Kreon-firmware drive or 0800 setup, you will not be able to use MPF or DiscImageCreator (the program that MPF uses to dump by default). See http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility#Xbox_original_.26_Xbox_360 for details.
