### ISSUE TITLE
[Request] Include <b>Filename</b>: in Xbox One dump info

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#390]
Xbox One game files are located in the MSXC folder on the root of an Xbox One disc.
They have no extension, and are the main "Game" file on the disc.
Redump records this info as it does other tags.

![unknown](https://user-images.githubusercontent.com/68273043/175386161-58e0d4f0-1236-49fd-997d-e8346a9d18f2.png)

Example:
[Comments]
<b>Filename</b>: Team17.WormsWMD_1.0.0.3_x64_q1v9gdbbh9x18

**Comment by mnadareski** [comment]
Are they the only files in the root of that folder, generally?

**Comment by NovaSAurora** [comment]
Confirmed: http://redump.org/disc/60729/
Batman2_1.0.0.2_x64__5jz77rkckcm0j
Batman2SeasonPass_1.0.0.0_neutral__5jz77rkckcm0j
Batman202_1.0.0.0_neutral__5jz77rkckcm0j
Batman203_1.0.0.0_neutral__5jz77rkckcm0j
Batman204_1.0.0.0_neutral__5jz77rkckcm0j
Batman205_1.0.0.0_neutral__5jz77rkckcm0j
