### ISSUE TITLE
[Request] fixing submissioninfo.txt output for some systems

### ISSUE THREAD

**Issue by antonioocera** [SabreTools/MPF#392]
As part of the redump moderation staff, i feel like we should fix something in the submissioninfo output file, too many database entries needs extra work from our part because people submit incorrect or unneeded data, especially for new dumps.
My three small requests to be implemented, if possible:
-Adding a "+" before any positive value for CDs offset. I guess that sarami removed that from the _disc.txt file, for whatever reason.
-Removing version number and layerbreak for XBOX and XBOX360 discs (DVD-9) - layerbreak should always be default, plus the data field is hidden to the members that use the new disc form, and version number is also unused, we use Rev 1, Rev 2, etc. to distinguish between different game revisions.
-Removing PVD section for XBOX (DVD-9) - all the discs should have the exact same PVD
Thanks as always for your help!

**Comment by mnadareski** [comment]
Remaining work in:
https://github.com/SabreTools/MPF/commit/ee76d49e564fd1f40626ac31f49d370abf1d45eb
https://github.com/SabreTools/MPF/commit/ab0b569798f10f5b4e98a3588859f6e9ab3e7f61
https://github.com/SabreTools/MPF/commit/5d176408a28aa1a36224b6e4c1e3a17444c9c0d9
https://github.com/SabreTools/MPF/commit/5db87566397c622a313f1d20a56fa6b8a60f04f1
