### ISSUE TITLE
[Request] Include "CD-R" in comments when disc is a CD-R

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#395]
Suggestion:
Include "CD-R" in the submissioninfo.txt comments field when the disc is detected as a CD-R in the *_disc.txt file.
It's included under:

![image](https://user-images.githubusercontent.com/68273043/182207566-a73535aa-24d5-48dd-a51b-11c83ebb2a05.png)

Perhaps do the same for DVD-Rs but I do not have a reference for this.

**Comment by sadikyo** [comment]
Yes please - this would be very helpful!

**Comment by Intothisworld** [comment]
+1. Great idea

**Comment by mnadareski** [comment]
Should be done as of https://github.com/SabreTools/MPF/commit/0903855d5cd61c0fe1eacee6f0dc69d247c9cff4 and https://github.com/SabreTools/MPF/commit/709d980b678750940d0ce9898a445438aab3429f

**Comment by mnadareski** [comment]
Multiple instances of the DiscType in DIC logs should be fixed as of https://github.com/SabreTools/MPF/commit/c391dbd3c88035609d00f24bd296896aee3e724c

**Comment by mnadareski** [comment]
Confirmed working with the above for normal DVD and CD as well as DVD-R and CD-R. All of the cases that we were concerned about with this.
