### ISSUE TITLE
[Request] iXL System Detection

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#396]
Mattel Fisher-Price iXL discs have a hidden "iXL" folder on the root of the disc.
Inside this folder is also a file titled "iXLUpdater.exe" which could be used to prevent against false positives.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/471bc60ed7bd2d47c51087fc8148eabc5455ff41
