### ISSUE TITLE
[Problem] dual-layer PS4 and XBOXONE discs detected as single-layer, PIC not populated in !submissionInfo.txt

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#399]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release (2.3-907)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.7.2 running on (Operating System)
- [X] .NET Framework 4.8 running on (Windows 7 Home Premium, 64-bit)
- [ ] .NET Core 3.1 running on (Operating System)

**Describe the issue**
When dumping a dual-layer (BD-50) PS4 disc, the Ringcodes dialog box does not show entries for both inner and outer layers. Instead, it shows a single Mastering Ring entry for Data Side and Label Side.

Also, the !submissionInfo.txt file that is produced does not contain PIC bytes extracted from name_PIC.bin, and the Media Type is incorrectly detected as BD-ROM-25 instead of BD-ROM-50. See attached.

**To Reproduce**
1. Use MPF to dump a Sony PlayStation 4 disc that has two layers.
2. Populate Disc Information when prompted.
3. Click Accept.

**Expected behavior**
Media Type should be detected correctly, Ringcodes dialog box should contain fields for both data side layers, and !submissionInfo.txt should contain data for PIC.

**Screenshots**
![image](https://user-images.githubusercontent.com/20304619/186818212-c0993608-c2a2-4be5-9adb-0c902cea5e58.png)

**Additional context**
[!submissionInfo.txt](https://github.com/SabreTools/MPF/files/9429733/submissionInfo.txt)

**Comment by tjanas** [comment]
[Last of Us, The - Part II (USA) (En,Fr,Es,Pt) (Data Disc)_PIC.zip](https://github.com/SabreTools/MPF/files/9435247/Last.of.Us.The.-.Part.II.USA.En.Fr.Es.Pt.Data.Disc._PIC.zip)

**Comment by mnadareski** [comment]
I tested directly with the PIC and it correctly detected multiple layers from the PIC. So that's telling me that the PIC path, though it _should be correct_ is not.

**Comment by mnadareski** [comment]
I need someone to test DIC directly. The PIC path that's expected is inside the output folder but if that's changed recently in DIC, then that needs to be accounted for.

**Comment by mnadareski** [comment]
Please try https://github.com/SabreTools/MPF/commit/40bbd422b7835d6c26db132f8b049ed2665a05e7, that may have fixed this.

**Comment by mnadareski** [comment]
According to two other people who tested this, it is working. Closing this.
