### ISSUE TITLE
[Request] - Separate profiles for Dreamcast Low Density and High Density dumps (or combine together).

### ISSUE THREAD

**Issue by ehw** [SabreTools/MPF#403]
**Is your feature request related to a problem? Please describe.**
Dreamcast GD-ROMs and GD-Rs contain two separate regions that must be dumped - a low density (LD) and a high density (HD) region. DiscImageCreator can currently dump both regions with in two separate modes. The low density tracks are dumped like a traditional CD-ROM/CD-R, while the high density are dumped with the "GD" mode. Currently, MPF has a "Sega Dreamcast" profile that can dump only the high density tracks with the "GD" mode in DiscImageCreator. However, there is no formal profile for the low density.

Another issue is the fact that currently there has to be two profiles for each density. More likely than not, users will most likely need two separate drives to dump Dreamcast discs - A Plextor for the low density, and a TSST (or other non-DIC supported drive) for the high density. It would be convenient if there was a profile in MPF that could handle both, but this would be very difficult to implement for a few reasons.

- As stated before, most users will most likely use two separate drives to dump the low and high density tracks. MPF only recognizes one drive at a time.
- The low density and high density dumps will have to be kept separate. Since MPF applies a given file name for all file names for the current dump, MPF would have to amend an additional part to the filename to differentiate between the low density and high density outputs, while allowing the individual tracks to be named properly. Or, alternatively, they can be separated into individual folders.
- DIC currently outputs a GDI with all the track information for the entire disc, not a Redump .cue. It outputs cues of course, but they have to be mended together and include the REM parts to make them work. I put in a feature request to sarami to have a Redump .cue be output as well, so MPF might not have to do this.
- Because low density and high density would be dumped separately with two separate profiles, the procedures for packing and creating the submission would be done twice rather than once. This is a little tedious.
- DIC is currently outputting some useless files. We don't need a .img, .ccd, or maybe even a .sub with anything. When packing files we need to exclude these. I'm putting a feature request to sarami to consider not outputting these when GD mode is used.

**Describe the solution you'd like**
The simplest solution that can be implemented right now is to create two profiles for the Dreamcast - one explicitly marked for low density and another for high density. Both that run the appropriate commands to make it work.

**Describe alternatives you've considered**
To make one singular profile for Dreamcast, a lot more work has to be put in that will definitely break in the future. This would also be very involved for the user as there are a lot of ways the procedure can go.

- 1.) When the Sega Dreamcast profile is selected, spawn another selection for a **secondary drive.** This gives the user the ability to choose another drive that might be connected, or use the same drive letter if by happenstance it picks the same letter when they swap drives using one connector. This also takes care of the event that one drive can actually dump both regions, like a PX-708A.
- 2.) Dump the low density as normal. This requires a Plextor or a flashed LG/ASUS drive. Mark all file names except for the tracks themselves with an additional "LD" to mark that all the logs are specifically for the low density. If this fails for any reason, stop everything and quit - don't move on to dumping the HD.
- 3.) When low density dumping is complete, prompt the user to insert the audio trap disc into the **secondary drive**. Once the OS recognizes the trap disc, run "discimagecreator.exe stop **"drive letter**". 
- 4.) Once the drive has been stopped, prompt the user to swap the disc with the GD-ROM. Once they hit "OK" after swapping, proceed with the current Dreamcast profile operation. Only this time, mark the filenames for everything except for the track names with "HD" to mark that all the logs are specifically for the high density.
- 5.) Then, pack everything up, prompt for submission info, etc. 

I would hold off on implementing any of this straight away as its possible that sarami might want to change certain things with DIC in the near future. But I'm filling out a feature request just for record keeping.

**Comment by mnadareski** [comment]
Both of these are difficult, to say the least. The ideal solution would be for DIC (or other dumping programs) to handle the high/low mix themselves and not have to rely on a third-party solution (MPF) to do the work.

That being said, there's at least a band-aid solution for part of this, which as discussed in Discord, is not immediately apparent. Dumping a GD-ROM as a "CD-ROM" handles only the low-density area and dumping as a "GD-ROM" only does the high-density area. Each of the systems that support GD-ROM should have an associated CD-ROM profile already. I may look into a secondary internal profile specific to GD-ROM low-density area (and maybe rename the current "GD-ROM" to "GD-ROM HD Area" or something).

**Comment by mnadareski** [comment]
Tied at the moment to https://github.com/SabreTools/MPF/issues/527

**Comment by Deterous** [comment]
I don't think there is much benefit to renaming the media type, even if it is a simple change.
The [GD-ROM dumping guide](http://wiki.redump.org/index.php?title=GD-ROM_Dumping_Guide) explicitly mentions dumping LD Area with MPF by selecting CD-ROM as the media type.
Most people dumping the HD Area probably won't use MPF, but if they do they can select GD-ROM.

MPF doing two dumps automatically requires sweeping changes to the code (as you've listed) and adds too much complexity for something that 0.001% of users will be doing.

If in the future DIC or Redumper supports dumping both areas in one command, then MPF could add a new Media Type to support this (renaming the current GD-ROM system to "GD-ROM (High Density Area)")

**Comment by mnadareski** [comment]
For better or worse, I'm going to count this as completed. The dumping programs themselves need more work before this would make sense to change.
