### ISSUE TITLE
[Problem] Exception Opening File when scanning on latest WIP

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#406]
**Version**
What version are you using? 
- [X] WIP release (2.3-911)

**Build**
What runtime version are you using?
- [X] .NET Framework 4.8 running on (W10)

**Describe the issue**
Copy protection scan after dumping only shows [Exception Opening File] for every file.
This does not happen on Stable (2.3)
This does not happen on latest BOS WIP (2.3.0-557-gwclepsc)

**Comment by mnadareski** [comment]
Exceptions are usually due to Windows doing dumb things while the disc is getting scanned. Does BOS standalone produce the same output?

**Comment by mnadareski** [comment]
Fixed as of https://github.com/SabreTools/MPF/commit/0c1486bbce46b4e8b030c4cb0d1cb7ccabf0e17f
