### ISSUE TITLE
[Problem] Ring Code Guide images do not load in current WIP

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#407]
**Version**
What version are you using? 

- [X] WIP release (2.3-911)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on Windows 10

**Describe the issue**
I dumped a disc, I pressed the Ring Code Guide button to see the images, but they did not load.

**To Reproduce**
1. Dump a disc
2. Go to the Ringcodes tab
3. Press Ring Code Guide button

**Expected behavior**
We're supposed to see the example ring code images

**Screenshots**
![image](https://user-images.githubusercontent.com/71686027/192693785-317c1fb2-1999-45f3-ac33-88263e6246be.png)

**Comment by FoxhackDN** [comment]
Oh, I think I know what the problem is. Imgur made hotlinking images work differently, so the old links used in the Wiki now redirect to a full page instead of loading the image on its own. The link -still works-, but it just won't load as a standalone image anymore.

**Comment by mnadareski** [comment]
Path probably broken when creating the core UI library.
