### ISSUE TITLE
[Request] Move "Dumping Info" section of submissioninfo.txt down to the very bottom (or top)

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#415]
**Is your feature request related to a problem? Please describe.**
Not a problem - just a processing efficiency proposal

**Describe the solution you'd like**
I'd like to see the "Dumping Info" section of the submissioninfo.txt file moved to the very bottom (or top).  

**Describe alternatives you've considered**
Dealing with it.

**Additional context**
The info is currently placed in between standard dump info (comments, version, etc.).  I think it makes more sense to have the software/hardware dumping info at the very bottom of the file.

**Comment by Whovian9369** [comment]
Why not have it in the comments directly?

**Comment by sadikyo** [comment]
Because we currently don't record that in the database.
