### ISSUE TITLE
[Problem] Error generating submissioninfo txt when dumping an Audio CD

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#417]
**Version**
- [X] WIP release (2.3-950)

**Build**
- [X] .NET Framework 4.8 running on (W10)

**Describe the issue**
Error generating submissioninfo txt when dumping an Audio CD

> Writing information to !submissionInfo.txt...
> Writing could not complete!

**Comment by mnadareski** [comment]
Logging around submission info writing added as of https://github.com/SabreTools/MPF/commit/e199e5a08cb1286045300ea47673ec0ffd13f55f

**Comment by mnadareski** [comment]
Logging around submission info formatting added as of https://github.com/SabreTools/MPF/commit/4d5b8baf6f46c4eab37387d9ad9c564667d1fae9

**Comment by mnadareski** [comment]
Issue identified:
```
Error formatting submission info: System.NullReferenceException: Object reference not set to an instance of an object.
   at MPF.Library.InfoTool.FormatOutputData(SubmissionInfo info) in C:\projects\mpf\MPF.Library\InfoTool.cs:line 823
Writing information to !submissionInfo.txt...
No formatted data found to write!
```

**Comment by mnadareski** [comment]
Fixed as of the above.
