### ISSUE TITLE
[Problem] Error reporting BD-R disc type 

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#418]
**Version**
What version are you using? 

- [*] WIP release (2.3-949 / 2.3-952)

**Build**
What runtime version are you using?

- [*] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
I burned a BD-R to test MPF's work in progress disc type detection and display in the submissioninfo file. This failed with this BD-R. The _disc.txt file output by DiscImageCheck correctly displayed "DiscTypeIdentifier: BDR", but the submission info said "Reported Disc Type: ecific: 00".

This bug was fixed in 2.3-952, but now MPF reports the following: "Reported Disc Type: 00, BDR, 00, BDR, 00, BDR, 00, BDR"

The reason is that the _disc.txt file as generated by DiscImageCreator has the disc information ... four times. Even if it's a single layer disc.

**To Reproduce**
1. Dump a BD-R
2. Get wrong info in submissioninfo.txt due to badly formatted _disc.txt file

**Expected behavior**
Disc Type should say 00, BDR once.

**Comment by mnadareski** [comment]
Mentioned offline but this won't be fixed for next stable. Possibly in the future (or generated directly from the PIC.

**Comment by mnadareski** [comment]
Try this out when it's built: https://github.com/SabreTools/MPF/commit/7bfe174680d381baad05e4606e489351e18f23c8

**Comment by mnadareski** [comment]
Fully fixed by https://github.com/SabreTools/MPF/commit/4d520d7d6317e2a8ccfbdde7c1640834fd9f7227
