### ISSUE TITLE
[Problem] partial regression of issue 399: dual-layer PS4 detected as single-layer

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#419]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release (2.3-956)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 7 Home Premium, 64-bit)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
When dumping a dual-layer (BD-50) PS4 disc, the Ringcodes dialog box does not show entries for both inner and outer layers. Instead, it shows a single Mastering Ring entry for Data Side and Label Side.

**To Reproduce**
1. Use MPF to dump a Sony PlayStation 4 disc that has two layers.
2. Populate Disc Information when prompted.
3. Click Accept.

**Expected behavior**
Media Type should be detected correctly, Ringcodes dialog box should contain fields for both data side layers.

**Screenshots**
![image](https://user-images.githubusercontent.com/20304619/197225147-1447a9a3-7160-4d72-92f8-837380b03008.png)

**Additional context**
Partial regression of https://github.com/SabreTools/MPF/issues/399. PIC is populated in submissionInfo.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/6cccf20b03a4c7caddddbccaad3c57751149cca7
