### ISSUE TITLE
[T:VOL] bug in submission.txt

### ISSUE THREAD

**Issue by eubrunosilva** [SabreTools/MPF#430]
- [X] Stable release (2.4)
- [X] .NET Framework 4.8 running on Windows 10

If we dump a cd/dvd that MPF output [T:VOL] to submission.txt  (example: VCD) and if we dump after a cd/dvd that (I think) doesn't have [T:VOL] (example: CDI), the submission.txt will have the last [T:VOL] that was read before.
CDi should have not [T:VOL]

**Comment by mnadareski** [comment]
I believe that this comes from cached drive values (when people don't scan for discs and just use the filename). I'll see what I can do.

**Comment by mnadareski** [comment]
@eubrunosilva please try the latest WIP based on the `frontend-over` branch. See if that fixes your issue.

**Comment by eubrunosilva** [comment]
still happens in [21b0c9a0](https://github.com/SabreTools/MPF/commit/21b0c9a08df81e8533f1e992cfab1b9d455ceef5)
