### ISSUE TITLE
[Problem] MPF crashes each time, when parameters are empty and checkbox is unticked

### ISSUE THREAD

**Issue by Feathered-Serpent** [SabreTools/MPF#437]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET 6.0 has known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
- [X] Stable release (Version 2.4-c4ef14ea)
- [X] WIP release (Version 2.4-1e55b8b8)

**Build**
What runtime version are you using?
- [X] .NET Framework 4.8 running on Windows 10 Pro 21H2
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
When the parameters field is empty and you uncheck the checkbox, MPF crashes

**To Reproduce**
1. select **No system selected** on the **System/Media Type**
2. Click on the checkbox right of the **Parameters** (which would be empty at this point)
3. Click on the checkbox again
4. MPF crashes

**Expected behavior**
Nothing should happen (except the parameters field becomes visible-only again)

**Comment by mnadareski** [comment]
@Feathered-Serpent please try the latest WIP based on the `frontend-over` branch. See if that fixes your issue.
