### ISSUE TITLE
[Problem] Dual-layer discs not properly detected by MPF 

### ISSUE THREAD

**Issue by InternalLoss** [SabreTools/MPF#451]
**Version**
What version are you using? 

- [X] Stable release 2.4
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on Windows 10
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
MPF does not show 

**To Reproduce**
1. Dump a DVD-9 disc (in this case, an XBOX disc)
2. Wait until disc has completed dumping, open Ringcodes tab

**Expected behavior**
Two data-side boxes for each layer (outer and inner).

**Screenshots**
![image](https://user-images.githubusercontent.com/30775249/218348726-baaaf738-a3ef-4c30-984e-0a92c3f95a90.png)
![image](https://user-images.githubusercontent.com/30775249/218348735-b925b4c6-ad6f-4d01-90b7-1b8a6e2085a7.png)

**Comment by mnadareski** [comment]
This was fixed at some point since last stable. WIP builds work as expected.
