### ISSUE TITLE
[Request] Redumper / Audio CD - additional comment fields required

### ISSUE THREAD

**Issue by halftheisland2019** [SabreTools/MPF#456]
redumper supports a number of additional features with regards to Audio CDs. These require some additional processing of redumper logs and generation of comment fields to be added to redump entries for such items.

**Universal Hash**

Will be found in redumper logs under section **MODE: Split and look as follows:

`Universal Hash (SHA-1): 33142665aa901c08210785c6802885768b4660d1`

Should be added to !submissionInfo.txt output under Comments as follows:

`<b>Universal Hash (SHA-1)</b>: 33142665aa901c08210785c6802885768b4660d1`

**Non-zero data start**

Found in redumper logs under section **MODE: Split and will need to be extracted from the following:

`non-zero data sample range: [      -11 .. +93464352]`

Should be added to !submissionInfo.txt output under Comments as follows:
`<b>Ring non-zero data start</b>: -11`

**Disc Write Offset**

Found in redumper logs under section **MODE: Split and will appear one of two ways:

`detecting offset`<br>
`audio silence detection... done`<br>
`Perfect Audio Offset (silence level: 0): -12`<br>
`Perfect Audio Offset applied`<br>
`disc write offset: -12`

Or

`detecting offset`<br>
`audio silence detection... done`<br>
`Perfect Audio Offset (silence level: 1): [-5384 .. +6991]`<br>
`warning: fallback offset 0 applied`<br>
`disc write offset: +0`

Should be added to !submissionInfo.txt output as a Write offset as normal e.g.:

`Write offset: -12`

**Lead-in / lead-out - Track 0 / Track A/AA.bin**

Where discs have non-zero data in the lead-in or lead-out this will result in the generation of additional Track 0 or Track A/AA.bin files. The information for these can be found in redumper logs under the "dat" heading and will appear as e.g.

`<rom name="GoW III (Track 00).bin" size="2352" crc="46f91175" md5="f43c1e89009ffb2f4f0fd04f5c3a3e34" sha1="1cee51d5e1c12873cce9aca7736792bc87812113" />` for lead-in

or

`<rom name="GoW III (Track A).bin" size="2352" crc="46f91175" md5="f43c1e89009ffb2f4f0fd04f5c3a3e34" sha1="1cee51d5e1c12873cce9aca7736792bc87812113" />`

They should be processed and output to !submissionInfo.txt comments as follows:

`<xmp><rom name="leadin.bin" size="2352" crc="46f91175" md5="f43c1e89009ffb2f4f0fd04f5c3a3e34" sha1="1cee51d5e1c12873cce9aca7736792bc87812113" /></xmp>`

or

`<xmp><rom name="leadout.bin" size="2352" crc="46f91175" md5="f43c1e89009ffb2f4f0fd04f5c3a3e34" sha1="1cee51d5e1c12873cce9aca7736792bc87812113" /></xmp>`

Example redump entries:
- Universal Hash / non-zero data start: http://redump.org/disc/86271/
- Lead-in / Lead-out http://redump.org/disc/93557/
- Write offset http://redump.org/disc/101599/

**Comment by mnadareski** [comment]
Universal Hash: https://github.com/SabreTools/MPF/commit/0e0ff0cb80c647126ff2f2340a233185d52ec461
Non-zero data start: https://github.com/SabreTools/MPF/commit/1cbe81fba661ac77f56295dd280a19f6d766de46
Disc Write Offset: https://github.com/SabreTools/MPF/commit/420e356f343cb2c6ab55f2c31abce57b0ff3b0c7
Lead-in / lead-out: Pending

**Comment by mnadareski** [comment]
The lead-in/lead-out seems to be rare enough that this should not be necessary right now. If this becomes more pressing in the future, please open a new issue for just that.
