### ISSUE TITLE
[Request] System as part of output path

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/MPF#458]
Add a new option (disabled by default) to include the shortname OR longname of the system in the output path. This may be useful for... someone.

**Comment by IcySon55** [comment]
Tag on Media Type as an optional path component as well for those that care. ^_^ (default off, default after system, can it be toggled to before system? up for discussion.)

**Comment by mnadareski** [comment]
I mentioned this in Discord, but I'd prefer to have a static order to the output, so "SYSTEM/MEDIA" with either being toggleable. Not intending on getting this looked at until after next stable at earliest.

**Comment by IcySon55** [comment]
I may have some other ideas about this as well. ^_^

**Comment by Deterous** [comment]
The user being able to input variables into the Output Path box seems the best approach. The following could be evaluated once dumping has started to determine the output path:
- `%SYSTEM%` (e.g. /PlayStation 2/)
- `%SHORT_SYSTEM%` (e.g. /PS2/)
- `%MEDIA%` (e.g. /CD-ROM/)
- `%PROGRAM%` (e.g. /Redumper/)
- `%DATE%` (e.g. /20240108/)

The output path also contains the filename, which could be set to variables as well:
- `%VOLUME_LABEL%`
- `%SERIAL%` (for supported systems as mentioned in #494 
- `%TITLE%` (If the file gets renamed after the Disc Information Window is closed)

The default output path could then be as complex as e.g. `ISO/%SHORT_SYSTEM%/%MEDIA%/%PROGRAM%/%DATE%`
