### ISSUE TITLE
[Problem] Autofill bug when pulling info from Redump.org

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#461]
**Version**
- [X] WIP release (2.4-e17ad8e4)

**Build**
- [X] .NET Framework 4.8 running on (W10)

**Describe the issue**
After dumping http://redump.org/disc/26293/ (IBM PC) successfully, I dumped http://redump.org/disc/82698/ (MAC)
the Volume Label pulled from the site for the Mac disc was the IBM PC label for some reason.

https://media.discordapp.net/attachments/461797735427735562/1081061790378631238/image.png

**Comment by mnadareski** [comment]
Not an autofill bug, it's an internal thing only. Likely the disc was updated without a full rescan or something. I'll try looking into this again as it's happened before.

**Comment by mnadareski** [comment]
Seems to have been related to a disc not detected by Windows. Should be easy.
