### ISSUE TITLE
[Request] GUI for MPF Check

### ISSUE THREAD

**Issue by Whovian9369** [SabreTools/MPF#466]
**Is your feature request related to a problem? Please describe.**
Check does not have a GUI available for those that don't know how to use a command prompt.

**Describe the solution you'd like**
I would like a GUI please.

**Describe alternatives you've considered**
Teaching new users how to use the command line.

**Comment by mnadareski** [comment]
I am not actively pursuing this, but the gist of the required work is as follows:
- Create a new executable project copied from `MPF.Check`
- Target it at `Microsoft.NET.Sdk.WindowsDesktop` instead
- Add the disc information window as a callback after the data was parsed

**Comment by mnadareski** [comment]
Another option would be to add a Check-like feature to the main UI, though that will heavily depend on a new window to account for the various options that are normally commandline parameters. Suggested by @sadikyo
