### ISSUE TITLE
[Problem] MPF no longer runs in Windows 7

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#468]
**Version**
What version are you using? 

- [X] Stable release (2.5)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 7 Home Premium 64-bit)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
At startup, MPF throws a System.IO.FileLoadException after `Scanning for drives..`

**To Reproduce**
1. Run MPF

**Expected behavior**
Same behavior as MPF 2.4

**Comment by mnadareski** [comment]
I will not be actively pursuing the changes required to support this. The culprit is `Microsoft.Management.Interface`, the recommended replacement to `System.Management`, used by MPF for drive polling. If somebody else is willing to put in the effort to debug and enable support, I will gladly review their pull request.

**Comment by tjanas** [comment]
Additional details on the point of failure:
```
System.IO.FileLoadException
  HResult=0x8013141A
  Message=Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
  Source=MPF.Core
  StackTrace:
   at MPF.Core.Data.Drive.GetDriveList(Boolean ignoreFixedDrives) in C:\Source\Repos\MPF\MPF.Core\Data\Drive.cs:line 635
   at MPF.Core.Data.Drive.CreateListOfDrives(Boolean ignoreFixedDrives) in C:\Source\Repos\MPF\MPF.Core\Data\Drive.cs:line 165
   at MPF.UI.ViewModels.MainViewModel.PopulateDrives() in C:\Source\Repos\MPF\MPF\ViewModels\MainViewModel.cs:line 112
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

Inner Exception 1:
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by mnadareski** [comment]
Strong name validation being disabled and https://github.com/SabreTools/MPF/commit/43cf8e1a450ea299905bf9629a72ecfb6ff57d49 appears to have fixed this, somehow. I'm considering this closed.
