### ISSUE TITLE
[Request] Allow to queue multiple drives/discs

### ISSUE THREAD

**Issue by Intothisworld** [SabreTools/MPF#472]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but would be a huge time-saver. I work all day, but have 4 disc drives. I could get a disc ready in each drive, set up the right output settings for each disc/drive in a queue, press go and have it dump them all in succession while I'm at work (or running errands, making dinner, etc.)

**Describe the solution you'd like**
Perhaps it could work using the regular output setup screen, but with an added extra button that says "add to queue" or something instead. And once the button is pressed, the current configuration is added to a queue, and the screen clears in preparation for another config to be added. Once you press "start," the first disc starts to dump, and when it finishes (presumably the submissionInfo.txt would simply remain blank for the time being), the logs would zip, and MPF would move on to the next drive/disc in the queue.

**Describe alternatives you've considered**
I also have a remote desktop app on my phone with which I can accomplish a similar thing (if I have opportunities to check my phone), or I can come home from work on my lunch if necessary. But a queue feature would be a really neat, much more succinct and efficient way to do this.

**Additional context**
None.

**Comment by mnadareski** [comment]
I am flat out denying this request as the main dev. Here's a quick list of why:
- Retooling the internals to allow for multiple "environments" as well as keeping track of them would require basically a full rewrite of the UI code
- Allow for graceful cancellation of any dump in the "queue" gets messy at best, especially given how the default dumping program behaves
- Multiple queued dumps that intentionally or accidentally use the same drive becomes difficult as I don't hook into any Windows APIs to know if a drive has been cycled or not
- Alternatively "filtering" the list of available drives based on the queue adds UI complexity that I do not want to have to account for
- Having multiple consecutive dumps can end up overwriting and, from experience and observation, can lead to mistakes when filling out media information

I am going to be keeping this open, like the other requests that I have similarly denied, if some enterprising dev wants to take this challenge on.
