### ISSUE TITLE
Size 0 & checksum fails

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#477]
**Version**
What version are you using? 

- [x] WIP release 2.5-1076

**Build**
- [x] .NET Framework 4.8 running on Win 11, 22H2

**Describe the issue**
After I'm done with a PS3 disc, checksum seems to fail. Don't find a match with redump, and output in submission textfile is:
```
Size & Checksum:
	Size: 0
```

**To Reproduce**
1. Dump a PS3 disc (probably any disc)
2. Check size & checksum in output

**Expected behavior**
Size & checksum should be there.

**Comment by Ragowit** [comment]
Going back to 1074 and it works again.

**Comment by mnadareski** [comment]
Cool, that means either the new DIC is broken, changed something, or both.

**Comment by mnadareski** [comment]
Can you please attach logs for just the newer build? That should help narrow down any issues.

**Comment by Whovian9369** [comment]
> Cool, that means either the new DIC is broken, changed something, or both.

I'm personally erring on DIC being broken, since an Audio CD dump (done without any "oddities" in the directory or file name) fails with an error of `[F:OutputHash][L:199] GetLastError: 2, The system cannot find the file specified.` and doesn't have checksums in the `dat` file.

**Comment by Ragowit** [comment]
[SPACEMARINE_logs.zip](https://github.com/SabreTools/MPF/files/11132830/SPACEMARINE_logs.zip)
[!submissionInfo.txt](https://github.com/SabreTools/MPF/files/11132831/submissionInfo.txt)

Attached files.

**Comment by Ragowit** [comment]
https://github.com/saramibreak/DiscImageCreator/commit/6e78601b3ad9f0add7cbc11cb254ea713e14192c works for me.

**Comment by mnadareski** [comment]
For anyone following along who isn't in VGPC, this was caused by a faulty DIC update and not anything in the MPF code. Even though this is still an issue with latest WIP, it will be cleared up whenever DIC gets a new stable.
