### ISSUE TITLE
[Problem] Special chars isn't trimmed from Output Path

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#480]
**Version**
- [x] WIP release 2.5-1d151d21

**Build**
- [x] .NET Framework 4.8 running on Win 11 22H2

**Describe the issue**
A disc title can have the char ™, which isn't trimmed in MPF, causing errors in DIC.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/31790/231833011-7007dffb-1a7b-4add-aac6-1cf726897d70.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/31790/231833059-764d6abc-9c27-4dfd-aec7-cbaf5fd8c62a.png">

This is what you see in MPF, the ™ is in the Output Path, but not visible.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/31790/231833330-a6cb3e58-27d6-4ffb-a80b-e48c764a6c07.png">

**To Reproduce**
1. Insert PS3 disc "UEFA Euro 2008™"
2. Start MPF
3. Press "Start Dumping"

**Expected behavior**
Since ™ is not allowed anyway, remove it (and any other special chars) from that Output Path altogether.

**Additional context**
A workaround is to simply rewrite the Output Path yourself if you encounter this error.

**Comment by mnadareski** [comment]
This is an issue with DIC and not with MPF. Those characters are not prohibited in file paths so if there are issues, then they stem directly from lack of handling for anything but extended ASCII in DIC. Please open an issue on DIC here: https://github.com/saramibreak/DiscImageCreator/issues
