### ISSUE TITLE
[Request] Support for new SUB files generated by latest DIC

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#483]
Add support for the new .sub files generated by the latest version of DIC (20230413) and include in log zipping.

![image](https://user-images.githubusercontent.com/68273043/233814097-fae9e9fa-212c-4096-a840-e868f42edd89.png)

**Comment by fuzz6001** [comment]
@mnadareski 
No offense, but...

```
Audio CD (Track 0).sub
Audio CD (Track 1)(-LBA).sub
```
