### ISSUE TITLE
[Problem] PS5 Media Type wrongly detected

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#485]
**Version**
- [x] WIP release 2.5-1108

**Build**
- [x] .NET Framework 4.8 running on Win 11 22H2
- [x] .NET 6.0 running on Win 11 22H2

I tried both versions for this issue.

**Describe the issue**
MPF says Media Type of PS5 disc is BD-ROM-25, when it really is BD-ROM-66. Besides outputting wrong info in the submission info, it also messes up the ringcode information field since MPF believes it's only one layer and not two.

**To Reproduce**
Dump "Hades (Europe)" or "Back 4 Blood (Europe)" PS5 discs.

Logs can be seen here:
https://github.com/Ragowit/redump-submissions/tree/main/PS5/H/Hades%20(Europe)/20230425_185758
https://github.com/Ragowit/redump-submissions/tree/main/PS5/B/Back%204%20Blood%20(Europe)/20230426_074014

**Expected behavior**
I expect it to tell it's a BD-ROM-66, with two layers of ringcode information.

**Additional context**
To my knowledge, the only two valid Media Types for PS5 is BD-ROM-66 (two layers) and BD-ROM-100 (three layers).

**Comment by mnadareski** [comment]
It looks like BD-66 and BD-100 use the identifier `BDU` instead of the original `BDO` for pressed discs. https://github.com/SabreTools/MPF/commit/088f1b8545b47a6b7adbf80fab4b4ab21cc3cce3 should fix this.

**Comment by mnadareski** [comment]
My local tests were relying on my assumption I was doing certain checks in only one place. The other place has been fixed as of https://github.com/SabreTools/MPF/commit/1ecf0ad1fafccd87ccb71ac5ffa457f2b8299b9f

**Comment by Ragowit** [comment]
Tried 1113 Check on my Death's Door again, and it said BD-ROM-66 this time around.
