### ISSUE TITLE
[Problem]

### ISSUE THREAD

**Issue by LuxKiller65** [SabreTools/MPF#489]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET 6.0 has known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [x] Stable release (version here)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on (Operating System)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
MPF 5 crashes on startup.
Tested MPF 4 just after and it works fine.
Running Windows 7 Pro 64 bit
Program runs from C:\Program Files (x68)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Error log:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MPF.exe
  Problem Signature 02:	2.5.0.0
  Problem Signature 03:	9a2d45d5
  Problem Signature 04:	MPF.Core
  Problem Signature 05:	2.5.0.0
  Problem Signature 06:	b17d0c4c
  Problem Signature 07:	55
  Problem Signature 08:	1
  Problem Signature 09:	System.IO.FileLoadException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by mnadareski** [comment]
Windows 7 has known issues and a known workaround. Please look at the main README in the repo for more details.
