### ISSUE TITLE
[Request] Use PS2 disc ID (e.g. SCES-12345) as folder/ISO name, if no volume name

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#494]
**Is your feature request related to a problem? Please describe.**
When dumping PS2 games, if there is no volume name present, the folder and ISO name "track" is used. This is awkward if you are dumping multiple PS2 discs with the same no-volume name.

**Describe the solution you'd like**
The disc ID used instead (only in situations where you would otherwise use "track"), i.e. the thing like SCES-12345. I believe this is relatively easily obtained from the files on the disc.

**Describe alternatives you've considered**
At the moment I rename the "track" folder after each dump, which works, but is slightly annoying.

**Additional context**
Presumably this could apply to other systems too, but it's PS2 discs that I'm working on at the moment.

**Comment by Deterous** [comment]
This is being implemented for PS1 and PS2 only.
PS3/4/5 are not being implemented at this time, as they always have a volume label ("PS3VOLUME" is the default for PS3, etc).
If you know of any other system that regularly has no volume label, let me know.
A better general solution to this issue, with custom default output paths will be worked on for #458
