### ISSUE TITLE
[Problem] Parameters field is empty (redumper+DVD)

### ISSUE THREAD

**Issue by fuzz6001** [SabreTools/MPF#498]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [x] WIP release (2.5-5c2dce78 / 2.5-1125)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on (Windows 10 x64)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
Parameters field is empty.

**To Reproduce**
1. Insert a DVD disc into the drive.
2. Start MPF.
3.  Select System and Media Type. (PC/DVD)
4.  Select redumper.

**Expected behavior**
The parameters field is filled with the appropriate arguments.

**Screenshots**
![screenshot 1686382696](https://github.com/SabreTools/MPF/assets/2080945/813805b8-6c3a-4f1b-ac3c-d9b93790028c)

**Comment by mnadareski** [comment]
Should be fixed by https://github.com/SabreTools/MPF/commit/e483e1cdc6b0fa913761e2b7ccffb986fc10b32a
