### ISSUE TITLE
[Problem] File size, checksums, etc. not picked up from redumper DVD output

### ISSUE THREAD

**Issue by DopefishJustin** [SabreTools/MPF#501]
What version are you using? 

- [x] WIP release 2.5-1130

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on Windows 10

**Describe the issue**
After doing a redumper DVD dump, the !submissionInfo.txt output from MPF includes the following:
```
Size & Checksum:
	Size: 0
```
instead of the expected size and checksums.

**To Reproduce**
1. Insert a DVD (I used IBM PC compatible ones)
2. Scan for discs
3. Select redumper as the dumping program
4. Start the dump
5. Wait for the dump to complete
6. Examine the resulting !submissionInfo.txt

**Expected behavior**
File size, checksums, layer break, and matching redump IDs are included in the !submissionInfo.txt

**Additional context**
Logs: [LEGO_MOVIE_logs.zip](https://github.com/SabreTools/MPF/files/11713847/LEGO_MOVIE_logs.zip) (http://redump.org/disc/103394/)
Same behaviour for both single- and double-layer discs.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/ab598d8377ad2283d0cb49f806a52ae7c6cb71da

**Comment by DopefishJustin** [comment]
Confirmed fixed

```
Size & Checksum:
	Layerbreak: 2065728
	Size: 7493056512
	CRC32: a2561510
	MD5: 977a128ef24f2932d2cbaf90c662fc63
	SHA1: 8d618ca6ee3edad59267e24417ab04b23137ea55
```
