### ISSUE TITLE
[Problem] Missing data from submissioninfo.txt for PS1 discs with Redumper

### ISSUE THREAD

**Issue by TonyLizard** [SabreTools/MPF#503]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET 6.0 has known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X ] WIP release (version here)

**Build**
What runtime version are you using?

- [X ] .NET Framework 4.8 running on (Windows 11 22H2)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
Submissioninfo.txt file is missing some data when you're dumping a PS1 disc using redumper. 
EDC always says: "EDC: Yes/No", Anti-Modchip scan and LibCrypt scan are always missing from the file.

**To Reproduce**
Dump a PS1 disc with redumper.

**Expected behavior**
submissioninfo file should get the data from redumper logs.

**Screenshots**
![immagine](https://github.com/SabreTools/MPF/assets/70547375/ba211ece-8b41-4f83-bde0-8186c2e19da6)
![immagine](https://github.com/SabreTools/MPF/assets/70547375/11d943e6-ff08-4228-a118-263cbdf91b05)

**Additional context**
[SCED-02646_logs.zip](https://github.com/SabreTools/MPF/files/11726079/SCED-02646_logs.zip)

**Comment by mnadareski** [comment]
Should be fixed by a combination of https://github.com/SabreTools/MPF/commit/f43aafc00d57d2e533ec945e6104fb1d98c92a75 and https://github.com/SabreTools/MPF/commit/6ceffce63d7733be7da6a70cd13c1311070478c2
