### ISSUE TITLE
[Request] Update to latest Redumper + Add CSS Parsing + Update overall parsing

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#504]
Latest version of Redumper adds CSS dumping support, and the output will need to be parsed

Update to overall parsing: Replace spaces with colons in keys to follow internet standard

VTS_01_1.VOB: C7 DC 7C E9 99
VTS_01_2.VOB: C7 DC 7C E9 99

->

VTS_01_1.VOB: C7:DC:7C:E9:99
VTS_01_2.VOB: C7:DC:7C:E9:99

**Comment by mnadareski** [comment]
Updated to newest Redumper as of https://github.com/SabreTools/MPF/commit/c6ebfcd6d9613792808603b5e477b5ac3a54f55b

**Comment by mnadareski** [comment]
Initial support for CSS outputs without extra formatting as of https://github.com/SabreTools/MPF/commit/56cf8f3574733a2cab3e63fefab16e703b3bd79d

**Comment by mnadareski** [comment]
Preliminary hookup as of https://github.com/SabreTools/MPF/commit/07ec821e9a4f6d7928e7cdb2b3213dabd892b963

**Comment by mnadareski** [comment]
Slightly newer Redumper as of https://github.com/SabreTools/MPF/commit/998bf5d5fa5a2a11a96248e70f078dd8f9b8b183
Supported `cd` synonym support (including `dvd`) as of https://github.com/SabreTools/MPF/commit/16ec54f389710dfebd849617926df9bb8530c82e

**Comment by mnadareski** [comment]
All but reformatting works as of https://github.com/SabreTools/MPF/commit/8695d2981e07c80dc6025d97cb957b83738df35a
