### ISSUE TITLE
[Problem] Multiple EAIDs not picked up

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#505]
**Version**
What version are you using? 

- [X] Stable release (2.5)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
If a redump entry has multiple EAIDs, only one is picked up by MPF.

**To Reproduce**
1. Dump disc FIFA Football 2002 (http://redump.org/disc/4516/)
2. Wait for submission form
3. View Electronic Arts ID field

**Expected behavior**
Field should say something like: "(PLEASE VERIFY) Electronic Arts ID: EAX03403558D (disc)
Electronic Arts ID: EAEX3403558IS (cover)
Electronic Arts ID: EAEX3403558M (manual)"

**Observed behavior**
Field says something like: "(PLEASE VERIFY) Electronic Arts ID: EAX03403558D (disc)"

**Additional context**
I assume the problem is that there are multiple EAID lines in the redump database for this particular disc, compared to, for example, entry http://redump.org/disc/84986/ where all the EAIDs are in one field separated by spaces.

I don't know what the redump moderation rules say about this, but from a quick browse it's not just disc http://redump.org/disc/4516/ that is affected.

I assume the same problem will happen with other fields too, if the redump database has multiple fields.

**Comment by mnadareski** [comment]
I dislike that this is an issue at all with Redump. I'll consider a fix for this on the MPF side.
