### ISSUE TITLE
[Problem] PS3 Media Type always preset to DVD-ROM

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#510]
**Version**
- [ ] WIP release (MPF_net6.0_win10-x64, 1148)

**Build**
- [ ] .NET 6.0 running on (Win 11)

**Describe the issue**
A PS3 disc is BD-ROM, however the pre-selected value is always DVD-ROM.

**To Reproduce**
1. Insert a PS3 disc
2. Start MPF
3. Notice that System is correctly set to "Sony PlayStation 3", but Media Type is wrongly set to "DVD-ROM"

**Expected behavior**
I expect the Media Type to be "BD-ROM"

**Screenshots**
![image](https://github.com/SabreTools/MPF/assets/31790/114c1376-7921-4db0-a541-d9ccbc3d2a6b)

**Comment by mnadareski** [comment]
Known issue with .NET 6, it can't determine media types. Not fixing.
