### ISSUE TITLE
[Request] Option to play a jingle when a dump has finished

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#520]
Mainly for Redumper, but Superg isn't keen on adding it to Redumper itself as it's a CLI program.

Please add an option to play a jingle when a dump has finished. Thank you :disgruntled:

**Comment by Whovian9369** [comment]
Agreed, this would be a large quality of life boon for us all.

**Comment by FoxhackDN** [comment]
doit.gif

**Comment by Flashfire42** [comment]
![Do it](https://github.com/SabreTools/MPF/assets/40415824/2c726675-978c-4838-8c27-9b5b22b732e1)

**Comment by mnadareski** [comment]
https://en.wikipedia.org/wiki/Groupthink

**Comment by mnadareski** [comment]
I'm officially closing this as the method to produce speaker sounds, `Console.Beep` is limited to Windows for C#.
