### ISSUE TITLE
[Problem] Output Path changes on initial edit to redumper Parameters

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#525]
**Version**
What version are you using? 

- [ ] Stable release (version here)
- [X] WIP release (2.6.1-1170)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Windows 7 Home Premium)
- [ ] .NET 6.0 running on (Operating System)

**Describe the issue**
On startup, without a disc loaded, MPF may have an Output Path as the following once selecting a System/Media Type:
`ISO\Disc Not Detected\Disc Not Detected.bin`

Upon editing the Parameters to add a valid parameter, the output path changes from a relative path to an absolute path, and the file extension is dropped:
`C:\MPF\ISO\Disc Not Detected\Disc Not Detected`

**To Reproduce**
1. Start MPF without a disc loaded.
2. Choose a CD-based System/Media Type
3. Add a valid parameter to Parameters for the selected Dumping Program

**Expected behavior**
Do not make any changes to Output Path.

**Comment by mnadareski** [comment]
Does this happen for both DIC and Redumper?

**Comment by mnadareski** [comment]
That's interesting that switching the program after startup causes it to work properly. Maybe more specifically: on startup, if you have DIC as the default or Redumper as the default, does it have the same behavior?

**Comment by tjanas** [comment]
If I make DiscImageCreator the default dumping program, the file extension is not dropped when restarting MPF and repeating the above steps.

**Comment by tjanas** [comment]
Would it be possible to preserve the relative Output Path? If so, should that be its own Feature Request issue?

**Comment by mnadareski** [comment]
Separate request for that. The full path makes things less ambiguous in the code.
