### ISSUE TITLE
[Request] CD Projekt ID field

### ISSUE THREAD

**Issue by CookiePLMonster** [SabreTools/MPF#530]
**Is your feature request related to a problem? Please describe.**
At the moment, on Redump there are 20-something submissions with a serial in format `P_xxxxx_yyA_region` ([EXAMPLE](http://redump.org/disc/103321/)). After a discussion on the VGPC Discord, it's been determined that these serials are specific to CD Projekt and are in use since circa 2007. An Excel spreadsheet with all games with this serial can be found [HERE](https://cdn.discordapp.com/attachments/418896419986997249/1134078494452744342/Silent.xls).

**Describe the solution you'd like**
A new `CD Projekt ID` field that includes the serial in the comments, much like it is done for many other IDs right now.

**Describe alternatives you've considered**
Putting `<b>CD Projekt ID:</b> x` manually is easy, but same could be said for most existing vendor IDs available in MPF - and my guess is that adding another one is a low cost solution. This screen already has a scrollbar too, so effectively no layout changes are needed.

**Comment by mnadareski** [comment]
I'm going to be talking with the Redump moderators before I add yet another ID field. It's trivial from the code side, but it does mean another pseudo-field to have to support.
