### ISSUE TITLE
MPF.check does not process PSP dumps from UIC correctly

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#532]
What version are you using? 

- [X] WIP release (2.6.2-1185)

**Build**

- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
When using MPF.check on a PSP dump from UmdImageCreator, the process fails because it looks for a _drive.txt file.  This log is not produced by UIC.

**To Reproduce**
Dump PSP umd with UIC, then run MPF.check

**Expected behavior**
Process just like normal

**Additional context**
I suppose one could create a dummy _drive.txt file, but it'd be nice if the -u UmdImageCreator parameter would correct the need for a _drive.txt file in order to process correctly.

**Comment by mnadareski** [comment]
What version of UIC are you using?

**Comment by sadikyo** [comment]
I don't know how to tell what version it is.  It doesn't show anything on PSP.  The filedate on the eboot.pbp file on my device is 1/31/22.

The command I used is:
mpf.check umd psp -u umdimagecreator [output path]

**Comment by mnadareski** [comment]
Okay, I don't see that file being explicitly used for anything except being zipped up, so I'll remove it as required.

**Comment by sadikyo** [comment]
It looks like 1.5 version does produce the _drive.txt, but older versions don't.  So if it isn't required, that seems good anyway.  I'm assuming even if you change this, it will still zip it up?

**Comment by mnadareski** [comment]
Yep, it just marks the file as not required on detection but will still zip it up and include in artifacts.
