### ISSUE TITLE
[Problem] MPF is not always accurately detecting the region from PS2 Discs.  I suggest this feature be altered or removed.

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#538]
- [X] Stable release (2.6.3)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
MPF is detecting PS2 Region from the serial, which is not always accurate, especially for non-USA regions.   For example, SLPM 64537 "looks" like a Japan region and MPF detects it as such simply based on the serial, but this is actually a Korea region disc.  The same issue occurs for some Asia region discs as well.  

We could alter / refine the detection process, if I knew exactly the model you were using for determining region.  There are some subsets of serials that do more commonly belong to certain regions.  For example, SLPM 64xxx is typically korea.  I imagine your current detection is more broad and might assume either SLPM or SLPM 6 or something, is Japan.  I am happy to help here or we could investigate more accurate detection methods.

**To Reproduce**
Dump PS2 disc, see what region MPF detects.

**Expected behavior**
Either no detection or an accurate region

**Comment by sadikyo** [comment]
The other problem with serial-based detection, is that if you are using internal serial (my assumption?), if there is a different region that matches the Japan region, that verification / other disc would also be misdetected.  There are several cases where multiple different regions match and have the same internal serial.

**Comment by mnadareski** [comment]
All automatic detections, from media and system type to region, are based on conventions and may not always be accurate. I place the onus of verification on the users. As previously discussed, I cannot have a "VERIFY THIS" tag on the region because of the strict set of regions and odd region codes used by Redump. I'm open to discuss this, but as I see it, this is a valid first-pass way of detecting regions.

**Comment by sadikyo** [comment]
Can you provide more information or point me to the direction of the convention it is currently using to detect the region for PS2 media?  I may be able to help improve it (using the same system you are using now).

**Comment by mnadareski** [comment]
https://github.com/SabreTools/MPF/blob/master/MPF.Modules/BaseParameters.cs#L1840

**Comment by mnadareski** [comment]
You are correct, hence my comment above about "first pass attempt". There's no way for MPF to read the external serial of a disc or reasonably detect things like languages to make better guesses.
