### ISSUE TITLE
[Problem] MPF does not pass the speed parameter to Aaru

### ISSUE THREAD

**Issue by CookiePLMonster** [SabreTools/MPF#539]
**Version**
What version are you using? 

- [x] Stable release (2.6.3) - at the time of submitting this report it's equivalent to the WIP release

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on **Windows 10**

**Describe the issue**
When dumping CD-ROM, the `--speed` parameter does not get passed from MPF to Aaru, despite appearing in the **Parameters** field. Although tests have been performed with the `--private` flag, this issue happens irrespectively of it.

**To Reproduce**
1. Open MPF. In my test, the dumping drive is `"E:"` and the output path is `"C:\Redump\Dumps\test-speed\test-mpf.aaruf"`.
2. Set Aaru as the dumping program, set Speed to 8.
3. Observe that the **Parameters** field says `media dump --force True --private True --speed 8 --retry-passes 500 "E:" "C:\Redump\Dumps\test-speed\test-mpf.aaruf"`.
4. Start dumping, notice it starts dumping at MAX speed. Cancel dumping and inspect Aaru's log to find the following - passed command line parameters lack the `--speed` param:
```
################# Program information ################
Aaru 5.3.2+f4fef21d
Running in 64-bit
Running as superuser: No
Command line: aaru.dll media dump --force True --private True --retry-passes 500  test-mpf.aaruf
```
5. Repeat the above steps but using `aaru.exe` from the command line. Notice that it starts dumping at 8x speed. Cancel dumping and inspect the log again to find all command line parameters passed properly:
```
################# Program information ################
Aaru 5.3.2+f4fef21d
Running in 64-bit
Running as superuser: No
Command line: aaru.dll media dump --force True --private True --speed 8 --retry-passes 500  test-cli.aaruf
```

**Expected behavior**
The `--speed` parameter gets passed to Aaru correctly.

**Comment by mnadareski** [comment]
Did this only occur with a single disc or with multiple? And what sort of disc(s) did you try to use?

**Comment by mnadareski** [comment]
Disregard. The issue has been identified.
