### ISSUE TITLE
[Problem] MPF does not default to .aaruf extension when using Aaru

### ISSUE THREAD

**Issue by CookiePLMonster** [SabreTools/MPF#540]
**Version**
What version are you using? 

- [x] Stable release (2.6.3) - at the time of submitting this report it's equivalent to the WIP release

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on **Windows 10**

**Describe the issue**
Aaru requires that the output file extension is `.aaruf` and not `.bin.` Supplying a path with a wrong extension will make Aaru refuse to dump the disc. I vaguely recall that MPF used to supply a correct extension when selecting Aaru, but this is not the case anymore.

**To Reproduce**
1. Open MPF.
2. Set Aaru as the dumping program. Observe that the output path in the **Parameters** field points to a `.bin` file.
3. Start dumping, notice Aaru refuses to dump the file.
4. Change the output path to point to an `.aaruf` file and start dumping again.
5. Notice dumping proceeds as expected.

**Expected behavior**
MPF defaults to a correct `.aaruf` extension when using Aaru as the dumping program.

**Comment by mnadareski** [comment]
Please expand on point 2. Do you mean "change to Aaru using the drop-box in the main UI" or "change to Aaru using the Options menu"? This is a critical difference.

**Comment by mnadareski** [comment]
If it is the former, try https://github.com/SabreTools/MPF/commit/d92a1d566dc14ca90878fed030d3456e39612bcf to see if it fixes your issues.

**Comment by CookiePLMonster** [comment]
> Please expand on point 2. Do you mean "change to Aaru using the drop-box in the main UI" or "change to Aaru using the Options menu"? This is a critical difference.

Yes, it is the former, apologies for not clarifying.

However, on the latest WIP build the issue still persists. Changing to Aaru using the dropdown in the main UI does not change the extension from `.bin` to `.aaruf`, at least not when you have changed the output filename to a custom one already. Ideally, the extension (and only the extension) should change regardless of whether the output path has been left at default, or modified by the user beforehand.

**Comment by mnadareski** [comment]
Try out https://github.com/SabreTools/MPF/commit/0912b78568cd41a8b060fcba2699494450cb3c3e to see if it fixes your issues.

**Comment by CookiePLMonster** [comment]
> Try out [0912b78](https://github.com/SabreTools/MPF/commit/0912b78568cd41a8b060fcba2699494450cb3c3e) to see if it fixes your issues.

Almost - the order of operations is wrong, because now changing the dumping program influences not the current extension, but the **future** one - as if it first checked the dumping program, then the dropdown option change took effect.

Try it with the following:
* Start with DIC selected - gives an extension `.bin`.
* Switch to Aaru - extension stays at `.bin.`
* Switch to dd, redumper or DIC - extension changes to `.aaruf`.

**Comment by CookiePLMonster** [comment]
I meant "future" as in "the current selected UI option is going to influence the next (future) output path", which indeed is equivalent to "the past UI option influenced the current output path".

Regardless, it works fine now. Thanks!
