### ISSUE TITLE
[Problem] Dump Already Exists warning appears when using DD + FDD

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#541]
**Version**
What version are you using? 

- [X] Stable release (2.6.3)

**Build**
What runtime version are you using?

- [X] .NET Framework 4.8 running on (W10)

**Describe the issue**
Pop-up appears warning that a dump already exists when using dd to dump a Floppy Disk with a Floppy Disk Drive, even when a dump as not been completed with the same name.
Default parameters are used (of="D:\MPF\ISO\track\track.img)

**Comment by NovaSAurora** [comment]
Addendum: No dump was completed at all, this may be a deeper issue, or an issue on my end.

**Comment by NovaSAurora** [comment]
Addendum 2: 
Error is caused by "\\?\A:" being used in parameters field instead of "\\.\A:"
Manually changing this does not work (likely due to how MPF parses it)

**Comment by mnadareski** [comment]
At least partially fixed by https://github.com/SabreTools/MPF/commit/6baaf132a7c47ab27d7ca4d0c1c7939702c17806
