### ISSUE TITLE
[Problem] MPF misattributes issue numbers as Disc Title

### ISSUE THREAD

**Issue by CookiePLMonster** [SabreTools/MPF#543]
If all of those fail, then continue...

**Version**
What version are you using? 

- [x] WIP release (MPF.Check 6baaf132a7c47ab27d7ca4d0c1c7939702c17806)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on **Windows 10**

**Describe the issue**
Many covermounts have their issue numbers written in parenthesis as part of the Title. When pre-filling `!submissioninfo.txt` with verification data from Redump, MPF (and MPF.Check) misattributes this part of the Title as Disc Title.

My test case is **Kaczor Donald 51-52/2006 (581)**: <http://redump.org/disc/47147/>
Its current datname is `Kaczor Donald 51-52-2006 (581) (Poland)`, because `(581)` is part of the Title. However, with MPF moving it to the Disc Title, a submission processed exactly as MPF suggests would be datted as `Kaczor Donald 51-52-2006 (Poland) (581)`.

This [has been pointed out on Redump](http://forum.redump.org/post/111489/#p111489) when a fix was being processed.

**To Reproduce**
1. Take a verification of any submission that has an issue number in the title. In this example it's <http://redump.org/disc/47147>.
2. Run `MPF.Check` on the dump, or dump it again via `MPF`.
3. Notice that the issue number (in this case, `581`) has been pre-filled as Disc Title:
```
Common Disc Info:
    Title: Kaczor Donald 51-52/2006
    Foreign Title (Non-latin): Mad Tracks
    Disc Number / Letter: (OPTIONAL)
    Disc Title: 581
    System: IBM PC compatible
    Media Type: CD-ROM
    Category: Coverdiscs
    Fully Matching ID: 47147
    Region: Poland
    Languages: SILENCE! (CHANGE THIS)
    Disc Serial: (REQUIRED, IF EXISTS)
```

**Expected behavior**
The issue number should stay part of the Title.

**Comment by mnadareski** [comment]
There's literally no way to tell since they're formatted identically. I can't fix this.

**Comment by CookiePLMonster** [comment]
Do you parse those from datnames or other data? If it is datnames, then a rule that Disc Letter and/or Disc Title must be after the Region might help resolve this.

**Comment by CookiePLMonster** [comment]
I see, so you effectively receive what is equivalent to Redump's display name, e.g. `Kaczor Donald 52-53/2005 (529)`. I can see that being problematic indeed, with the only idea being maybe to filter out Disc Titles that are numeric only not to be treated as Disc Titles.

**Comment by mnadareski** [comment]
I cannot guarantee that a disc title would not be purely numeric at any point.

**Comment by CookiePLMonster** [comment]
True - but you are trading off a relatively frequent false positive (issue number treated as a Disc Title) into a much more uncommon false negative (Disc Title treated as a part of the Title). It's still a win.

**Comment by mnadareski** [comment]
I'll consider it.
