### ISSUE TITLE
[Request] Add option for BE drive reading for Redumper

### ISSUE THREAD

**Issue by TheRogueArchivist** [SabreTools/MPF#545]
**Is your feature request related to a problem? Please describe.**
When dumping with Redumper, you need to specify if you want to use BE drive reading with "--drive-read-method=BE_CDDA" in order to produce a proper dump, unlike Plextors which are automatically detected by Redumper.

**Describe the solution you'd like**
A setting in MPF to toggle adding "--drive-read-method=BE_CDDA" to the command.

**Comment by mnadareski** [comment]
Only a toggle on/off for this. Not a freeform field nor a dropdown to select different values.

**Comment by FoxhackDN** [comment]
Mentioned in discord, but ideally, this command line setting would be ignored by Redumper if it detects the drive is a Plextor.

A toggle would work fine, "only turn it on if needed".

**Comment by TheRogueArchivist** [comment]
> Only a toggle on/off for this. Not a freeform field nor a dropdown to select different values.

Definitely agree, I don't even think there are multiple relevant settings for that due to it autodetecting Plextors.
