### ISSUE TITLE
[Request] Only grab "Common Disc Info" from Redump

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#552]
**Is your feature request related to a problem? Please describe.**
Humans are lazy, thus also users. A lazy user who haven't removed the "faulty" data submits an invalid verification. A lazy user who haven't filled out all the extra info still submits a valid verification.

MPF pre-fills a lot of data from Redump if a match is found. A user is very unlikely to remove "faulty" data, making it harder for verification team to handle the verification submission data.

Also, when a verifier points out to a user that its submission is faulty, it feels odd since the user have just submitted the output data from the app.

**Describe the solution you'd like**
Only pre-fill "Common Disc Info" (and "Fully Matched ID"). The rest should be up to the user to fill out.

Again: A lazy user who haven't removed the "faulty" data submits an invalid verification. A lazy user who haven't filled out all the extra info still submits a valid verification.

**Describe alternatives you've considered**
Point out to every user that they have to remove unnecessary data. But this is already done in red text at the settings page for login data to Redump, and isn't fail-safe.

**Comment by sadikyo** [comment]
I STRONGLY agree with this.

In my personal opinion, none of the comments should ever pull in.  That is where I see a lot of faulty / extraneous information.   Many comments are specific to a particular disc, and don't always apply to others. 

I think significantly less should be pulled in - just about anything that is disc / release specific.  Publisher IDs for example. 

I personally think only Title, Foreign Title, and Languages should be pulled.  Most other information is very subject to change depending on the region, release, disc variant, etc.
