### ISSUE TITLE
[Problem] MPF Doesn't seem to correctly pull EDC Yes/No information for PS1 Discs dumped with redumper

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#556]
- [X] Stable release (2.6.5)
- [X] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
When dumping PS1 discs with redumper, redumper correctly detects whether EDC should be marked Yes or No.  This information is not being pulled correctly into MPF.

**Additional context**
In the redumper log, it is in this section:
CD-ROM [SLPM-80582 (Track 01).bin]:
  sectors count: 10890
  mode2 sectors: 10890
  mode2 (form 1) sectors: 10766
  mode2 (form 2) sectors: 124
  mode2 (form 2) EDC: yes

specifically, if it says "mode2 (form 2) EDC: yes" in the redumper log, then MPF should treat EDC as Yes in the submission info.  Conversely, if it is not detected, the redumper log will say mode2 (form 2) EDC: no

I've attached the redumper log, and the MPF submissioninfo file, for a recent dump I did where EDC should be Yes but MPF says no.  Let me know if any other information is needed.

[!submissionInfo.txt](https://github.com/SabreTools/MPF/files/12755481/submissionInfo.txt)

[SLPM-80582.log](https://github.com/SabreTools/MPF/files/12755492/SLPM-80582.log)

**Comment by mnadareski** [comment]
Oh I see, it changed a little. The current code assumes a line that just has `EDC: yes/no` and not with the prefix.
