### ISSUE TITLE
[Problem] Output Path read-only

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#567]
**Version**
MPF_1303_net7.0_win-x64_debug.zip

**Build**
.NET 7, build 1303

**Describe the issue**
Output Path is read-only, I can't alter it.

**To Reproduce**
Open MPF, notice Output Path is read-only.

**Expected behavior**
I expect to be able to change the Output Path.

**Screenshots**
![image](https://github.com/SabreTools/MPF/assets/31790/52370e70-3afe-4c43-806a-4ace8a76c860)

**Additional context**
I had .NET 7 build 1294 before, and it worked there. I'm reverting to that for the time being.

**Comment by FoxhackDN** [comment]
This problem is also present in the Net 4.8 build.

**Comment by mnadareski** [comment]
Fixed as a part of https://github.com/SabreTools/MPF/commit/06491a6611789d3d5925a235c7f513c519a04e1a
