### ISSUE TITLE
[Info] Wiki needs updating

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#570]
https://github.com/SabreTools/MPF/wiki/Overview

~~The table for dumping programs needs updating: dd for Windows is gone from MPF, and redumper is good~~ DONE

~~While you're at it, updating https://github.com/SabreTools/MPF/wiki/Build-a-Local-Copy to mention VS 2022 and .NET 6/7~~ DONE

**Comment by mnadareski** [comment]
The wiki is pretty far out of date across multiple places at this point. I'll keep this in mind the next time I can take a swing at it.

**Comment by mnadareski** [comment]
This is in progress. Some old information was removed and references to things like Redumper were added. Most of the UI screenshots and Check flags need to be updated still.

**Comment by Deterous** [comment]
@mnadareski I have edited the MPF and MPF.Check pages, have a look

**Comment by mnadareski** [comment]
Looks good. Thank you for updating those. I'm going to consider this item done.
