### ISSUE TITLE
[Problem] `MPF.Check` on UmdImageCreator image errors out

### ISSUE THREAD

**Issue by FakeShemp** [SabreTools/MPF#575]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET 6.0 has known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [x] Stable release (2.7.1)
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.8 running on (Operating System)
- [x] .NET 7.0 running on (Fedora 38)

**Describe the issue**
I'm running `./MPF.Check umd psp -u uic UmdImageCreator/ULES-00329.iso` and getting `uic does not exist`.

`./MPF.Check umd psp -u UmdImageCreator UmdImageCreator/ULES-00329.iso` results in `UmdImageCreator does not exist`

**To Reproduce**
1. Run `./MPF.Check umd psp -u uic path/to/file.iso` on a UmdImageCreator image
2. See error

**Expected behavior**
submissionInfo.txt to be created.

**Screenshots**

**Additional context**

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/705b5f10499bf51636cc784b234c91c56fe3b0f1
