### ISSUE TITLE
[Request] Enhance Volume Label detection and output in !submissioninfo.txt

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#579]
At the moment MPF appears to prioritize the ISO9660 volume label to output into !submissioninfo.
My suggestion is to output all present volume labels (ISO, Joliet, HFS, UDF, Rock Ridge, etc)

Example:
[T:VOL]
GAMENAME123 (ISO9660)
GameName123 (Joliet)
GameName12345 (HFS)
GameNameABCD (UDF)
...

**Comment by mnadareski** [comment]
I believe that I would need a `[T:VOL]` for every line given that it's not typically a multi-line field, similar to things like alternative titles.

**Comment by NovaSAurora** [comment]
We could do away with the [T:VOL] tag and use custom tags:

<b>Volume Label (ISO)</b>:
<b>Volume Label (HFS)</b>:
<b>Volume Label (UDF)</b>
...

So we're at least not reusing tags, at it'll look cleaner.

**Comment by mnadareski** [comment]
Pseudo-tags make me sad.

**Comment by Deterous** [comment]
MPF currently gets whatever volume label Windows sees (typically the ISO9660 label as you mentioned, but sometimes UDF). MPF is not privy to the volume type for this label.
MPF directly reading volume labels from disc is likely out of scope, instead will be limited to whatever labels are available in the dumping program's logs.
As far as I can tell, DIC logs provide the ISO9660 and Joliet volume labels, Redumper logs currently have only the ISO9660 label, and I haven't looked into Aaru.

So the best that can be done so far is DIC outputting the Joliet volume label as well as the existing ISO9660 one. Also, if Windows sees a UDF label that differs from ISO9660 label, then MPF could output the ISO9660 label to the submission info. The work for this would mean it should be easy to add other label types if dumping programs support them in the future.
