### ISSUE TITLE
[Problem] MPF.Check Path argument doesn't work properly with Linux paths due to lack of drive letters

### ISSUE THREAD

**Issue by HeroponRikiBestest** [SabreTools/MPF#581]
**Before You Submit**
- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed.
- Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
- .NET 6.0 has known issues, please try using another build to reproduce the error
- Check multiple discs to help narrow down the issue
- Check the Options to see if changing any of those affects your issue.

If all of those fail, then continue...

**Version**
What version are you using? 

- [ ] Stable release (version here)
- [x] WIP release 2.7.1.1

**Build**
What runtime version are you using?

- [ ] .NET Framework 4.8 running on (Operating System)
- [x] .NET 6.0 running on Linux Mint 21.2

**Describe the issue**
When specifying drive path on MPF.Check on Linux, it fails with `/:\ is not a directory or file, skipping...` due to Linux not having drive paths.

**To Reproduce**
Attempt to specify drive path on linux.

**Expected behavior**
I expected path to accept the drive path and output relevant info.

**Screenshots**

**Additional context**

**Comment by mnadareski** [comment]
May be fixed as of https://github.com/SabreTools/MPF/commit/d68175db4eb64e2805bc98a41ae851d7a62a74fb
