### ISSUE TITLE
[Problem] PS5 Version autofill issue

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#588]
**Version**
MPF_1371_net6.0_win-x64_debug.zip

**Build**
- [x] .NET 6.0 running on (Win 11, 22H2)

**Describe the issue**
After dumping "Metal Gear Solid Master Collection: Volume 1" so is the Version field filled as "   },"

**To Reproduce**
Dump "Metal Gear Solid Master Collection: Volume 1" (EU)
Look at Version field.

**Expected behavior**
Version to be something along "01.00"

**Screenshots**
![image](https://github.com/SabreTools/MPF/assets/31790/6a83acb0-201a-4a85-a7d5-fb1f480e03ed)

**Additional context**
The param.json file from the disc: [param.json](https://github.com/SabreTools/MPF/files/13169779/param.json)

**Comment by Ragowit** [comment]
Noticed that TISN becomes wrong as well.

**Comment by mnadareski** [comment]
Please check to see if https://github.com/SabreTools/MPF/commit/dc35b08624e830365b869cbe71944fdc027cf91b worked for this

**Comment by Ragowit** [comment]
Tried two PS5 discs (Metal Gear Master Collection and Diablo 4) with MPF_1377_net6.0_win-x64_debug and it works fine now, thanks.
