### ISSUE TITLE
[Request] Give the user a warning when the folder they are dumping to is not empty

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#595]
**Is your feature request related to a problem? Please describe.**
When new users use MPF, they don't think to change the folder after dumping their first disc. Inevitably, they run into an error when dumping a disc in the same folder as a previous dump.

**Describe the solution you'd like**
Give a warning Yes/No pop-up to the user when the folder they are requesting to dump to is not empty, which may cause errors.

**Describe alternatives you've considered**
Automatically rename the folder that MPF decides on if the current one is not empty

**Additional context**
A general solution is desirable for #494 and #458

**Comment by mnadareski** [comment]
To be more specific, this would be for the case where someone dumps with one program and then dumps with another, possibly with intersecting filenames. The case where a completed dump of the same program already exists is already handled by the code.
