### ISSUE TITLE
[Problem] DIC does not detect the /be raw command when I set it in MPF

### ISSUE THREAD

**Issue by MrPepka** [SabreTools/MPF#606]
**Version**
2.7.5 stable
**Build**
NET 7.0
**Describe the issue**
When I enter the /be raw command in Parameters (I will remove the /c2, /sf, /ns etc. commands from there) and start dumping the disc, DIC does not detect this command

**To Reproduce**
1. Insert disc
2. Launch MPF and set system to "IBM PC Compatible"
3. In Parameters delete commands /sf, /ns and /c2
4. Enter command /be raw
5. Start dumping (make sure DIC is set as the disc dumper)
6. DIC does not see this command and switches to Pack mode

**Expected behavior**
DIC should detect the /be raw command and (despite the lack of /c2) start dumping in raw mode

**Screenshots**

<img width="446" alt="Zrzut ekranu 2023-11-10 183928" src="https://github.com/SabreTools/MPF/assets/38865931/dcf08799-9c5a-4b2c-ab63-0de723a85db9">
[LPM2000_20231109T224638.txt](https://github.com/SabreTools/MPF/files/13321966/LPM2000_20231109T224638.txt)

**Additional context**
I have a rather problematic disc with erroneous sectors and I need to dump it without /c2 to see what hashes will be generated by different drives, I also want to dump these problematic sectors in data mode in all drives I have to determine whether all drives generate identical hashes for these sectors. I need the /be raw command because one of my drives (BW-16D1HT) does not support Pack mode, so dumping a disc without /c2 is significantly slower

**Comment by Deterous** [comment]
Just to check it's an MPF issue, have you tried running DIC with `/be raw` via the command line?

**Comment by MrPepka** [comment]
Yes and works
