### ISSUE TITLE
MPF 2.7.5 NET4.8 Crush 

### ISSUE THREAD

**Issue by Mason2Wavy** [SabreTools/MPF#610]
I am using the last version that support Win7 and When I open the MPF software it immediately crush, the screen shows MPF stop working and then the program close. I am using Win7 SP1 and what should I do?

**Comment by Mason2Wavy** [comment]
![IMG_5063](https://github.com/SabreTools/MPF/assets/151894138/d751d503-214e-4ba6-b11f-dc299729df32)Here is the error message and my laptop only install one language sorry for the inconvenience, it says there is a problem with MPF, MPF stop working.

**Comment by mnadareski** [comment]
Try looking at the recommendations from the Legacy project: https://github.com/Deterous/MPF-Legacy Those may help you. Officially, Windows 8 was the oldest OS I was supporting with .NET Framework 4.8.

**Comment by mnadareski** [comment]
Since there has been no reply on this, I am closing the issue. If the issue persists, then unfortunately it is on the user to find a solution for unsupported platforms.
