### ISSUE TITLE
redumper (Track X).skeleton files not added to logs archive

### ISSUE THREAD

**Issue by mictlantecuhtle** [SabreTools/MPF#615]
**Version**
What version are you using?

- [X] Stable release (3.0.3)

**Build**
What runtime version are you using?

- [X] .NET 6.0 running on Windows 10

**Describe the issue**
Where a .skeleton file is generated for a multi-track disc, the (Track X).skeleton is not zipped and added to the logs as expected. I have only been able to verify this with a (Track 1) file but assume the issue holds true for any given number.

**To Reproduce**

1. Dump a disc using redumper, with at least two tracks, where one is data and expected to generate a .skeleton file
2. The generated file is not zipped and added to the logs

**Expected behavior**

The file should be added to the logs archive as it currently is with .skeleton files for single data track discs.

**Screenshots**
![temp](https://github.com/SabreTools/MPF/assets/50200766/89179cf3-e218-47bf-bd78-0960b8027710)

**Comment by superg** [comment]
I'll just update that the same applies to the .hash file which contains SHA-1 checksums of excluded skeleton areas.
