### ISSUE TITLE
[Problem] MPF it's crashed when I use "--skip-fill" option

### ISSUE THREAD

**Issue by MrPepka** [SabreTools/MPF#630]
**Version**
Latest WIP version (3.0.3-1507 or something)

**Build**
NET 8.0

**Describe the issue**
I need to use the "--skip-fill" option on one disc to fill incorrect sectors with 0x55 filler, but when I want to use this option, after entering it and unchecking the checkbox, the program crashes

**To Reproduce**
1. Check "Parameters" box
2. Write "--skip-fill=" and enter the sectors you want to skip
3.  Uncheck box
4. Program crash

**Expected behavior**
The program should run after entering the desired option

**Comment by mnadareski** [comment]
What dumping program are you using? DIC or Redumper?

**Comment by MrPepka** [comment]
I forgot to mention. I use Redumper
