### ISSUE TITLE
[Problem] MPF.Check: Dumping Program not detected

### ISSUE THREAD

**Issue by tjanas** [SabreTools/MPF#636]
**Version**
MPF.Check 3.0.3

- [X] Stable release
- [ ] WIP release

**Describe the issue**
When the redumper log file contains the following string on line 2:
warning: drive read offset not found in the database

it seems to result in "Dumping Program: Redumper Unknown Version"
[logs.zip](https://github.com/SabreTools/MPF/files/14039966/logs.zip)

**Comment by mnadareski** [comment]
Should be fixed by https://github.com/SabreTools/MPF/commit/9e8e4f6e36966fcfdb30e909de4f857110548ec9

**Comment by tjanas** [comment]
This issue may also be present when using DiscImageCreator as the dumping program, not sure if that commit would address this
![image](https://github.com/SabreTools/MPF/assets/20304619/3bbe7632-c335-4548-8275-536871c3015f)

**Comment by mnadareski** [comment]
This commit only addresses Redumper. If this issue is also happening with DIC, please open a new issue and include DIC logs so it can be fixed
