### ISSUE TITLE
[Request] Make Redumper the default program

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/MPF#638]
After 3.1.0 is released, make Redumper the default program for new instances of MPF. This will help avoid many of the issues that new users have with having to change it from DIC for a large number of common systems.

**Comment by Deterous** [comment]
In addition, make Redumper the default program selected for the new MPF.Check GUI.
i.e. change order of https://github.com/SabreTools/MPF/blob/747ac4ea3bda5bedcd511923d61b9be1f4834283/MPF.Core/UI/ViewModels/CheckDumpViewModel.cs#L357
