### ISSUE TITLE
[Problem] MPF includes AA.2 track generated by Redumper when looking for Redump matches

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#640]
**Version**
What version are you using?

- [X] Stable release (3.0.3)

**Build**
What runtime version are you using?

- [X] .NET 6.0 running on (W11)

**Describe the issue**
When dumping a multisession disc with Redumper and a AA.2 track is generated, MPF includes this when looking for db matches on Redump.org

**Screenshots**
![image](https://github.com/SabreTools/MPF/assets/68273043/9e0418d8-4d6e-4215-bbc2-7b58128ee47b)
![image](https://github.com/SabreTools/MPF/assets/68273043/8eb49f24-770b-4bde-a030-e530efb210ba)

**Comment by Deterous** [comment]
Expected functionality is that only tracks with positive numbers should be checked against redump.org?
i.e. Track 1, 2, 3, ... only?
not: Track 0, A, AA1, B, 2B, whatever, etc?

**Comment by mnadareski** [comment]
The `.X` at the end is the session number. There are generally a max of 2 sessions on a disc, so I think it's safe to do so.

**Comment by Deterous** [comment]
**Current:** `0`, `0.2`, `00`, `00.2`, `A`, `AA`
**Add:** `AA.2`
What about `A.2`? Is there anything else you can conceive occurring?

**Comment by mnadareski** [comment]
Basically every variant can optionally have a `.2` suffix. In theory, if there was a disc with more sessions, those would be suffixed with their respective session numbers. Given that `.2` is rare enough and I haven't personally seen a `.3`, I think it's safe to just hardcode a new value in the list for now. If there's a reason to make it more extensible in the future, then we can do so.
