### ISSUE TITLE
[Request] Scan PS3 like BD-Video

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#648]
Opened per request of Sabre

Scan PS3 like BD-Video
BD-Video with PS3 demos get detected as PS3 system, scan these like BD-Video

**Comment by mnadareski** [comment]
First pass through seems like we don't have any auto checks for BD-Video. Which seems wrong. At the very least, having AACS and BD+ checks would probably be good. Stay tuned.

**Comment by Deterous** [comment]
Legitimate PS3 discs can have BDMV and AACS folders, so finding the exclusive folders/files for BD-Video may be trickier

**Comment by mnadareski** [comment]
I'm going to mark this as _technically_ done as no checks are being done to scan BD-Video at the moment. In the future, if/when additional information is done for BD-Video, they will be added for PS3 as well.
