### ISSUE TITLE
[Request] Additional information in 'Dumping Info' section of submissioninfo: C2 errors and MPF Build

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#666]
Requesting if possible some additional information to be populated in the 'Dumping Info' section of the submissioninfo txt file:

1. C2 error count (if redumper is used)
-----This could be helpful in identifying if a disc should be dumped twice to verify hashes or if we need to inspect logs a bit closer
2. MPF Build
-----This could be helpful in tracking and resolving issues if they are quirks in particular builds.

I believe these both would potentially help the mods in identifying and correcting issues, and noticing them a bit easier.

**Comment by mnadareski** [comment]
This has to be updated in SabreTools.RedumpLib first and then it can be added to MPF.

**Comment by mnadareski** [comment]
https://github.com/SabreTools/SabreTools.RedumpLib/commit/f69c7e6bb2e65af7b3dc431641654131d37f0d3d has added the required fields to the library. Once a new minor release of that package goes out, then MPF can be updated to take advantage.

**Comment by mnadareski** [comment]
RedumpLib has been updated.
