### ISSUE TITLE
[Problem] MPF is parsing titles a bit strange when it includes The, A, An, etc etc

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#667]
- [X] Stable release (3.1.2)
- [X] .NET 8.0 running on (Windows 10)

**Describe the issue**
MPF is parsing titles strangely when it includes an Article in the beginning like A, An, The, etc.

For example, it currently parses:
The Sims 2: Pets
into:
Sims 2:, ThePets

I have not tested all other articles but can do so if needed later.

**Expected behavior**
Correct Parsing for redump purposes

**Additional context**
Example:
http://forum.redump.org/topic/53848/ibm-pc-the-sims-2-pets-expansion-pack/

**Comment by Deterous** [comment]
Currently the only punctuation that definitive articles is being placed before is colon and hyphen, i.e.

`The Sims 2: Pets` -> `Sims 2, The: Pets`
`The Sims 2 - Pets` -> `Sims 2, The - Pets`
but, other punctuation:
`The Sims 2, Pets`  -> `Sims 2, Pets, The`
`The Sims 2= Pets` -> `Sims 2= Pets, The`
