### ISSUE TITLE
[Request] Better XboxOne / XSX detection/parsing

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#675]
Currently, XboxOne is detected through the presence of a /MSXC folder
XSX discs look very similar to XboxOne, leading to users commonly dumping one as the other.
MPF should be able to parse /MSXC/Metadata/catalog.js file that is present on all XboxOne + XSX discs as far as I am aware, and contains fields such as "version", "type", and "generation" that may be good to use for system detection, and potentiall parse as extra submission info.

**Comment by Deterous** [comment]
Example XboxOne catalog.js: `{"version":"2.0","launchPackage":{"contentId":"3e75d001-67b1-46de-b3bf-8f3bc3896800"},"packages":[{"packageName":"Package0.xvc","productId":"579a1338-7240-4de6-9212-162f333d205f","contentId":"3e75d001-67b1-46de-b3bf-8f3bc3896800","titleId":"1DD9017C","titles":[{"locale":"default","title":"OCCULTIC;NINE"}],"vui":[{"locale":"default","title":"OCCULTIC;NINE"}],"images":[{"size":"100x100","image":"100x100_1.png"},{"size":"208x208","image":"208x208_1.png"},{"size":"480x480","image":"480x480_1.png"}],"ratings":[{"system":"PEGI","value":"Unrated"},{"system":"USK","value":"Unrated"},{"system":"ESRB","value":"Unrated"},{"system":"OFLC","value":"Unrated"},{"system":"PEGIPortugal","value":"Unrated"},{"system":"CSRR","value":"Unrated"},{"system":"China","value":"3+"},{"system":"CERO","value":"D"},{"system":"PCBP","value":"Unrated"},{"system":"DJCTQ","value":"Unrated"},{"system":"GRB","value":"Unrated"},{"system":"COB","value":"Unrated"}],"size":4441960448,"type":"Game"}]}`

Example XSX catalog.js: `{"version":"4.0","packages":[{"xboxProductId":"464b5039-4c32-3044-c046-5058544e6c00","oneStoreProductId":"9PKF2LDFPXTN","contentId":"7b914176-0bdc-4877-ac7a-4bace9f84281","titleId":"71EF4D9A","titles":[{"locale":"sv","title":"RoboCop: Rogue City"},{"locale":"ko","title":"RoboCop: Rogue City"},{"locale":"nl","title":"RoboCop: Rogue City"},{"locale":"nb","title":"RoboCop: Rogue City"},{"locale":"ru","title":"RoboCop: Rogue City"},{"locale":"pl","title":"RoboCop: Rogue City"},{"locale":"fr","title":"RoboCop: Rogue City"},{"locale":"pt-pt","title":"RoboCop: Rogue City"},{"locale":"pt","title":"RoboCop: Rogue City"},{"locale":"de","title":"RoboCop: Rogue City"},{"locale":"it","title":"RoboCop: Rogue City"},{"locale":"tr","title":"RoboCop: Rogue City"},{"locale":"fi","title":"RoboCop: Rogue City"},{"locale":"da","title":"RoboCop: Rogue City"},{"locale":"ja","title":"RoboCop: Rogue City"},{"locale":"es","title":"RoboCop: Rogue City"},{"locale":"en","title":"RoboCop: Rogue City"},{"locale":"zh","title":"RoboCop: Rogue City"},{"locale":"ar","title":"RoboCop: Rogue City"},{"locale":"cs","title":"RoboCop: Rogue City"},{"locale":"th","title":"RoboCop: Rogue City"},{"locale":"uk","title":"RoboCop: Rogue City"}],"vui":[{"locale":"sv","title":"RoboCop: Rogue City"},{"locale":"ko","title":"RoboCop: Rogue City"},{"locale":"nl","title":"RoboCop: Rogue City"},{"locale":"nb","title":"RoboCop: Rogue City"},{"locale":"ru","title":"RoboCop: Rogue City"},{"locale":"pl","title":"RoboCop: Rogue City"},{"locale":"fr","title":"RoboCop: Rogue City"},{"locale":"pt-pt","title":"RoboCop: Rogue City"},{"locale":"pt","title":"RoboCop: Rogue City"},{"locale":"de","title":"RoboCop: Rogue City"},{"locale":"it","title":"RoboCop: Rogue City"},{"locale":"tr","title":"RoboCop: Rogue City"},{"locale":"fi","title":"RoboCop: Rogue City"},{"locale":"da","title":"RoboCop: Rogue City"},{"locale":"ja","title":"RoboCop: Rogue City"},{"locale":"es","title":"RoboCop: Rogue City"},{"locale":"en","title":"RoboCop: Rogue City"},{"locale":"zh","title":"RoboCop: Rogue City"},{"locale":"ar","title":"RoboCop: Rogue City"},{"locale":"cs","title":"RoboCop: Rogue City"},{"locale":"th","title":"RoboCop: Rogue City"},{"locale":"uk","title":"RoboCop: Rogue City"}],"images":[{"size":"100x100","image":"BigbenInteractiveSA.RoboCopRogueCity_1.0.3.0_neutral__tqjv3vrxr8ppw_xs.100.png"},{"size":"208x208","image":"BigbenInteractiveSA.RoboCopRogueCity_1.0.3.0_neutral__tqjv3vrxr8ppw_xs.208.png"},{"size":"480x480","image":"BigbenInteractiveSA.RoboCopRogueCity_1.0.3.0_neutral__tqjv3vrxr8ppw_xs.480.png"}],"ratings":[{"system":"COB-AU","value":"COB-AU:R18"},{"system":"GCAM","value":"GCAM:18"},{"system":"OFLC-NZ","value":"OFLC-NZ:R16"},{"system":"USK","value":"USK:18"},{"system":"CSRR","value":"CSRR:R"},{"system":"ESRB","value":"ESRB:M"},{"system":"PEGI","value":"PEGI:18"},{"system":"PCBP","value":"PCBP:18"}],"type":"Game","generation":"9","packageName":"BigbenInteractiveSA.RoboCopRogueCity_1.0.3.0_neutral__tqjv3vrxr8ppw_xs","attributes":[{"supports4k":false,"supportsHdr":false,"isXboxOneXEnhanced":false}]}]}`

**Comment by Randy2727** [comment]
Example Xbox One with Smart Delivery enhancement for Series X:
`{"version":"2.1","packages":[{"packageName":"5733EF57.ELDENRING_1.0.0.5_neutral_WW_rd9nrpbe1455p_x","productId":"00000000-0000-0000-0000-000070c95f35","contentId":"f20d9853-e108-4573-8214-0f4a4bc30f43","titleId":"70C95F35","titles":[{"locale":"zh-hans","title":"艾尔登法环"},{"locale":"zh-hant","title":"艾爾登法環"},{"locale":"ko","title":"ELDEN RING"},{"locale":"en","title":"ELDEN RING"},{"locale":"ar","title":"ELDEN RING"},{"locale":"da","title":"ELDEN RING"},{"locale":"nl","title":"ELDEN RING"},{"locale":"fi","title":"ELDEN RING"},{"locale":"no","title":"ELDEN RING"},{"locale":"pl","title":"ELDEN RING"},{"locale":"en-ca","title":"ELDEN RING"},{"locale":"en-us","title":"ELDEN RING"},{"locale":"fr-ca","title":"ELDEN RING"},{"locale":"pt-br","title":"ELDEN RING"},{"locale":"ja","title":"ELDEN RING"},{"locale":"fr","title":"ELDEN RING"},{"locale":"de","title":"ELDEN RING"},{"locale":"it","title":"ELDEN RING"},{"locale":"pt","title":"ELDEN RING"},{"locale":"ru","title":"ELDEN RING"},{"locale":"es","title":"ELDEN RING"},{"locale":"es-es","title":"ELDEN RING"},{"locale":"sv","title":"ELDEN RING"},{"locale":"tr","title":"ELDEN RING"},{"locale":"en-sg","title":"ELDEN RING"}],"vui":[{"locale":"zh-hans","title":"艾尔登法环"},{"locale":"zh-hant","title":"艾爾登法環"},{"locale":"ko","title":"ELDEN RING"},{"locale":"en","title":"ELDEN RING"},{"locale":"ar","title":"ELDEN RING"},{"locale":"da","title":"ELDEN RING"},{"locale":"nl","title":"ELDEN RING"},{"locale":"fi","title":"ELDEN RING"},{"locale":"no","title":"ELDEN RING"},{"locale":"pl","title":"ELDEN RING"},{"locale":"en-ca","title":"Elden Ring, ER"},{"locale":"en-us","title":"Elden Ring, ER"},{"locale":"fr-ca","title":"Elden Ring, ER"},{"locale":"pt-br","title":"Elden Ring, ER"},{"locale":"ja","title":"ELDEN RING"},{"locale":"fr","title":"ELDEN RING"},{"locale":"de","title":"ELDEN RING"},{"locale":"it","title":"ELDEN RING"},{"locale":"pt","title":"ELDEN RING"},{"locale":"ru","title":"ELDEN RING"},{"locale":"es","title":"Elden Ring, ER"},{"locale":"es-es","title":"ELDEN RING"},{"locale":"sv","title":"ELDEN RING"},{"locale":"tr","title":"ELDEN RING"},{"locale":"en-sg","title":"ELDEN RING"}],"images":[{"size":"100x100","image":"5733EF57.ELDENRING_1.0.0.5_neutral_WW_rd9nrpbe1455p_x.100.png"},{"size":"208x208","image":"5733EF57.ELDENRING_1.0.0.5_neutral_WW_rd9nrpbe1455p_x.208.png"},{"size":"480x480","image":"5733EF57.ELDENRING_1.0.0.5_neutral_WW_rd9nrpbe1455p_x.480.png"}],"ratings":[{"system":"ESRB","value":"ESRB:M"},{"system":"CSRR","value":"CSRR:R"},{"system":"GRB","value":"GRB:18"},{"system":"COB-AU","value":"COB-AU:MA"},{"system":"FPB","value":"FPB:16"},{"system":"GCAM","value":"GCAM:18"},{"system":"OFLC-NZ","value":"OFLC-NZ:R13"},{"system":"PCBP","value":"PCBP:16"},{"system":"PEGI","value":"PEGI:16"},{"system":"USK","value":"USK:16"},{"system":"CERO","value":"CERO:D"},{"system":"DJCTQ","value":"DJCTQ:16"}],"attributes":[{"supports4k":false,"supportsHdr":false,"isXboxOneXEnhanced":false}],"size":31963430912,"type":"Game"}]}`

**Comment by Deterous** [comment]
So far:
- "generation":"9" only exists for XSX, in fact "generation" itself only exists for XSX
- "version":"4.0" is for XSX, "2.0" and "2.1" for XboxOne
- "PackageName" ends in `_xs` for XSX, `_x` for smart delivery XSX, and neither for XboxOne

**Comment by Deterous** [comment]
Another XSX: `{"version":"4.0","discNumber":1,"discCount":2,"discSetId":"00007BDC","bundle":{"xboxProductId":"31395039-4c50-3053-c04c-5a424b576c00","oneStoreProductId":"9P91PLSLZBKW","titles":[{"locale":"en","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"ar","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"cs","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"da","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"nl","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"fi","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"fr","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"de","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"it","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"no","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"pl","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"pt","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"ru","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"sk","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"es","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"sv","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"tr","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"es-es","title":"Tales of Arise Cross-Gen Bundle"},{"locale":"zh-hans","title":"破晓传奇 (Xbox Series X|S & Xbox One)"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox Series X|S & Xbox One)"},{"locale":"ja","title":"Tales of Arise (Xbox Series X|S & Xbox One)"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox Series X|S & Xbox One)"},{"locale":"pt-br","title":"Tales of Arise Cross-Gen Bundle"}],"vui":[{"locale":"en","title":"Tales of Arise"},{"locale":"ar","title":"Tales of Arise"},{"locale":"cs","title":"Tales of Arise"},{"locale":"da","title":"Tales of Arise"},{"locale":"nl","title":"Tales of Arise"},{"locale":"fi","title":"Tales of Arise"},{"locale":"fr","title":"Tales of Arise"},{"locale":"de","title":"Tales of Arise"},{"locale":"it","title":"Tales of Arise"},{"locale":"no","title":"Tales of Arise"},{"locale":"pl","title":"Tales of Arise"},{"locale":"pt","title":"Tales of Arise"},{"locale":"ru","title":"Tales of Arise"},{"locale":"sk","title":"Tales of Arise"},{"locale":"es","title":"Tales of Arise"},{"locale":"sv","title":"Tales of Arise"},{"locale":"tr","title":"Tales of Arise"},{"locale":"es-es","title":"Tales of Arise"},{"locale":"zh-hans","title":"破晓传奇 (Xbox Series X|S & Xbox One)"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox Series X|S & Xbox One)"},{"locale":"ja","title":"ているずおぶあらいず"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox Series X|S & Xbox One)"},{"locale":"pt-br","title":"Tales of Arise"}],"images":[{"size":"100x100","image":"bundle.100.png"},{"size":"208x208","image":"bundle.208.png"},{"size":"480x480","image":"bundle.480.png"}]},"packages":[{"xboxProductId":"09c6679a-d5bb-4908-85c2-fb4724e080d9","oneStoreProductId":"BSJ53LGG6STB","contentId":"87b2fc31-77ca-45d6-a049-4b65ea17f14e","titleId":"3B07E56F","titles":[{"locale":"en","title":"Tales of Arise (Xbox One)"},{"locale":"ja","title":"Tales of Arise (Xbox One)"},{"locale":"ar","title":"Tales of Arise (Xbox One)"},{"locale":"cs","title":"Tales of Arise (Xbox One)"},{"locale":"da","title":"Tales of Arise (Xbox One)"},{"locale":"nl","title":"Tales of Arise (Xbox One)"},{"locale":"fi","title":"Tales of Arise (Xbox One)"},{"locale":"fr","title":"Tales of Arise (Xbox One)"},{"locale":"de","title":"Tales of Arise (Xbox One)"},{"locale":"it","title":"Tales of Arise (Xbox One)"},{"locale":"no","title":"Tales of Arise (Xbox One)"},{"locale":"pl","title":"Tales of Arise (Xbox One)"},{"locale":"pt","title":"Tales of Arise (Xbox One)"},{"locale":"ru","title":"Tales of Arise (Xbox One)"},{"locale":"sk","title":"Tales of Arise (Xbox One)"},{"locale":"es","title":"Tales of Arise (Xbox One)"},{"locale":"sv","title":"Tales of Arise (Xbox One)"},{"locale":"tr","title":"Tales of Arise (Xbox One)"},{"locale":"es-es","title":"Tales of Arise (Xbox One)"},{"locale":"en-ca","title":"Tales of Arise (Xbox One)"},{"locale":"en-us","title":"Tales of Arise (Xbox One)"},{"locale":"fr-ca","title":"Tales of Arise (Xbox One)"},{"locale":"pt-br","title":"Tales of Arise (Xbox One)"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox One)"},{"locale":"zh-hans","title":"破晓传奇 (Xbox One)"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox One)"}],"vui":[{"locale":"en","title":"Tales of Arise"},{"locale":"ja","title":"ているずおぶあらいず"},{"locale":"ar","title":"Tales of Arise"},{"locale":"cs","title":"Tales of Arise"},{"locale":"da","title":"Tales of Arise"},{"locale":"nl","title":"Tales of Arise"},{"locale":"fi","title":"Tales of Arise"},{"locale":"fr","title":"Tales of Arise"},{"locale":"de","title":"Tales of Arise"},{"locale":"it","title":"Tales of Arise"},{"locale":"no","title":"Tales of Arise"},{"locale":"pl","title":"Tales of Arise"},{"locale":"pt","title":"Tales of Arise"},{"locale":"ru","title":"Tales of Arise"},{"locale":"sk","title":"Tales of Arise"},{"locale":"es","title":"Tales of Arise"},{"locale":"sv","title":"Tales of Arise"},{"locale":"tr","title":"Tales of Arise"},{"locale":"es-es","title":"Tales of Arise"},{"locale":"en-ca","title":"Tales of Arise"},{"locale":"en-us","title":"Tales of Arise"},{"locale":"fr-ca","title":"Tales of Arise"},{"locale":"pt-br","title":"Tales of Arise"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox One)"},{"locale":"zh-hans","title":"破晓传奇 (Xbox One)"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox One)"}],"images":[{"size":"100x100","image":"Arise_1.0.0.1_neutral__6ftx19d9rjm7g.CompDisc.1.100.png"},{"size":"208x208","image":"Arise_1.0.0.1_neutral__6ftx19d9rjm7g.CompDisc.1.208.png"},{"size":"480x480","image":"Arise_1.0.0.1_neutral__6ftx19d9rjm7g.CompDisc.1.480.png"}],"ratings":[{"system":"COB-AU","value":"COB-AU:M"},{"system":"CERO","value":"CERO:C"},{"system":"CSRR","value":"CSRR:PG15"},{"system":"DJCTQ","value":"DJCTQ:14"},{"system":"ESRB","value":"ESRB:T"},{"system":"GCAM","value":"GCAM:16"},{"system":"GRB","value":"GRB:12"},{"system":"OFLC-NZ","value":"OFLC-NZ:M"},{"system":"PCBP","value":"PCBP:12"},{"system":"PEGI","value":"PEGI:12"},{"system":"USK","value":"USK:12"},{"system":"FPB","value":"FPB:16"},{"system":"Microsoft","value":"Microsoft:16"}],"type":"Game","generation":"8","packageName":"Arise_1.0.0.1_neutral__6ftx19d9rjm7g.CompDisc.1","attributes":[{"supports4k":false,"supportsHdr":false,"isXboxOneXEnhanced":false}]},{"xboxProductId":"35465039-5143-3033-c035-4d5232421300","oneStoreProductId":"9PF5CQ35MR2B","contentId":"98ac98de-26c6-4752-bca1-5d7df3c9c442","titleId":"6FA021EA","titles":[{"locale":"ar","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"cs","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"da","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"nl","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"en","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"fi","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"fr","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"de","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"it","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"no","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"pl","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"pt","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"ja","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"ru","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"sk","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"es","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"sv","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"en-ca","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"pt-br","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"tr","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"fr-ca","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"es-es","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"en-us","title":"Tales of Arise (Xbox Series X|S)"},{"locale":"zh-hans","title":"破晓传奇 (Xbox Series X|S)"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox Series X|S)"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox Series X|S)"}],"vui":[{"locale":"ar","title":"Tales of Arise"},{"locale":"cs","title":"Tales of Arise"},{"locale":"da","title":"Tales of Arise"},{"locale":"nl","title":"Tales of Arise"},{"locale":"en","title":"Tales of Arise"},{"locale":"fi","title":"Tales of Arise"},{"locale":"fr","title":"Tales of Arise"},{"locale":"de","title":"Tales of Arise"},{"locale":"it","title":"Tales of Arise"},{"locale":"no","title":"Tales of Arise"},{"locale":"pl","title":"Tales of Arise"},{"locale":"pt","title":"Tales of Arise"},{"locale":"ja","title":"ているずおぶあらいず"},{"locale":"ru","title":"Tales of Arise"},{"locale":"sk","title":"Tales of Arise"},{"locale":"es","title":"Tales of Arise"},{"locale":"sv","title":"Tales of Arise"},{"locale":"en-ca","title":"Tales of Arise"},{"locale":"pt-br","title":"Tales of Arise"},{"locale":"tr","title":"Tales of Arise"},{"locale":"fr-ca","title":"Tales of Arise"},{"locale":"es-es","title":"Tales of Arise"},{"locale":"en-us","title":"Tales of Arise"},{"locale":"zh-hans","title":"破晓传奇 (Xbox Series X|S)"},{"locale":"zh-hant","title":"破曉傳奇 (Xbox Series X|S)"},{"locale":"ko","title":"테일즈 오브 어라이즈 (Xbox Series X|S)"}],"images":[{"size":"100x100","image":"NAMCOBANDAIGamesInc.TalesofAriseXSXBaseGame_1.0.1.0_neutral__gdy2aq6ez762w_xs.CompD.100.png"},{"size":"208x208","image":"NAMCOBANDAIGamesInc.TalesofAriseXSXBaseGame_1.0.1.0_neutral__gdy2aq6ez762w_xs.CompD.208.png"},{"size":"480x480","image":"NAMCOBANDAIGamesInc.TalesofAriseXSXBaseGame_1.0.1.0_neutral__gdy2aq6ez762w_xs.CompD.480.png"}],"ratings":[{"system":"COB-AU","value":"COB-AU:M"},{"system":"CERO","value":"CERO:C"},{"system":"CSRR","value":"CSRR:PG15"},{"system":"DJCTQ","value":"DJCTQ:14"},{"system":"ESRB","value":"ESRB:T"},{"system":"FPB","value":"FPB:16"},{"system":"GCAM","value":"GCAM:16"},{"system":"GRB","value":"GRB:12"},{"system":"OFLC-NZ","value":"OFLC-NZ:M"},{"system":"PCBP","value":"PCBP:12"},{"system":"PEGI","value":"PEGI:12"},{"system":"USK","value":"USK:12"},{"system":"Microsoft","value":"Microsoft:16"}],"type":"Game","generation":"9","packageName":"NAMCOBANDAIGamesInc.TalesofAriseXSXBaseGame_1.0.1.0_neutral__gdy2aq6ez762w_xs.CompDisc.1","attributes":[{"supports4k":false,"supportsHdr":false,"isXboxOneXEnhanced":false}]}],"siblings":[["NAMCOBANDAIGamesInc.TalesofAriseXSXBaseGame_1.0.1.0_neutral__gdy2aq6ez762w_xs.CompDisc.1","Arise_1.0.0.1_neutral__6ftx19d9rjm7g.CompDisc.1"]]}`

**Comment by Deterous** [comment]
More info here:

https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/packaging/creating-cross-gen-test-discs

https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/packaging/creating-test-compilation-discs

**Comment by mnadareski** [comment]
The work for parsing this is going to be offloaded to both SabreTools.Models and SabreTools.Serialization while the checks will be done in MPF.

**Comment by Deterous** [comment]
For research purposes, a v1.0 catalog.js example:
`{"version":"1.0","productId":"988b4862-9b7e-40d8-b720-4984624986a8","contentId":"d24104b1-b391-4fc7-a479-d34a5f874d7c","titleId":"7619D2FB","titles":[{"locale":"default","title":"Wolfenstein: The New Order"}],"vui":[{"locale":"default","title":"Wolfenstein The New Order"}],"images":[{"size":"100x100","image":"100x100_1.png"},{"size":"208x208","image":"208x208_1.png"},{"size":"480x480","image":"480x480_1.png"}],"ratings":[{"system":"OFLC","value":"R18"},{"system":"DJCTQ","value":"18"},{"system":"PEGI","value":"A18p"},{"system":"USK","value":"18"},{"system":"ESRB","value":"M"},{"system":"COB","value":"R18"}],"size":47841271808,"type":"Game"}`
