### ISSUE TITLE
[Bug] CD-ROM Dumping causes string_to_enum failed, Error 

### ISSUE THREAD

**Issue by Con-Rez** [SabreTools/MPF#676]
- [ ] Stable release v3.1.2
- [ ] .NET 6.0.25 running on Windows 11

**Describe the issue**
Cannot use anything other than DiscImageCreator for dumping CD-ROMs using "PLEXTOR DVDR   PX-716A USB Device" as labeled in Device Manager on latest CD-Drive Firmware. Reproduced on fresh install. Tested on three discs. Error from log below:

**To Reproduce**

1. Insert any CD-ROM, ensure it is set properly to CD-ROM in Media Type.
2. Attempt Dump
3. Immediately stops with confirmation of failure to create files in Console. No other Errors.
4. Checking the Log File in the generated Folder for the dump shows the following Error

=== 2024-03-14 22:08:44 ========================================================
error: string_to_enum failed, no such value in dictionary (possible values: GENERIC, PLEXTOR, LG_ASU8A, LG_ASU8B, LG_ASU8C, LG_ASU3, LG_ASU2)

**Expected behavior**
To Dump the CD without immediately cancelling the dump and outputting an error log without further context in the console on what went wrong.

**Additional context**
- Using USB Drive adapter linked here: https://www.amazon.com/dp/B00BIE996S?psc=1&ref=ppx_yo2ov_dt_b_product_details
- No Issues when using this same drive for DVD dumping. So my theory is that it isn't detecting my Plextor drive properly despite being listed on http://wiki.redump.org/index.php?title=Optical_Disc_Drive_Compatibility for this work.

**Comment by Deterous** [comment]
This sounds like a Redumper issue: https://github.com/superg/redumper

**Comment by Con-Rez** [comment]
It seems to work only when the Launch Parameter for drive-type is changed to PLEXTOR. Maybe a drop-down should be added to select drive-type beforehand, or further clarification in the error regarding what to do. I'll edit the title and issue accordingly.

**Comment by Deterous** [comment]
> It seems to work only when the Launch Parameter for drive-type is changed to PLEXTOR. Maybe a drop-down should be added to select drive-type beforehand, or further clarification in the error regarding what to do. I'll edit the title and issue accordingly.

Selecting the drive type is not required, redumper automatically detects this. The issue is that redumper does not recognise your drive. Do you have the latest firmware installed for your drive?

**Comment by Con-Rez** [comment]
The one listed as up-to-date on Redump: http://wiki.redump.org/index.php?title=Optical_Disc_Drive_Compatibility#CD-ROM_.2F_CD-Audio

I thought MPF handled drive detection for the launch options? 

Here's a picture of the drive (i'm embarrassed by the blur):
![20240315_000836](https://github.com/SabreTools/MPF/assets/55933973/0e78e13f-6bf1-402e-8f25-d29eefe12457)

**Comment by Deterous** [comment]
Thank you for the confirmation, just ensure you have firmware version 1.11 in the device manager.
MPF detects the drive letter, but not the model. Redumper is what detects the drive type.
I'm not sure why Redumper doesn't detect it, I think you'll have to raise an issue there https://github.com/superg/redumper/issues

**Comment by Con-Rez** [comment]
It is, the event logs list it as "Device USBSTOR\CdRom&Ven_PLEXTOR&Prod_DVDR___PX-716A&Rev_1.11" I'll mark this as closed then.

**Comment by Con-Rez** [comment]
I've found the issue, and its specific to MPF!
By default drive-type is set to "--drive-type=Generic". It should be set to "--drive-type=GENERIC". Capitalization was the issue!

**Comment by Deterous** [comment]
https://github.com/SabreTools/MPF/blob/ef7510804ef29658d789677561610e8c8abe2967/MPF.Core/Modules/Redumper/Parameters.cs#L1095
Good find! I will fix that.
Does that mean you have "RedumperUseGenericDriveType" set to true in MPF options?
It should be false by default. Try unticking that option and see if it works for you.

**Comment by Con-Rez** [comment]
Yea, I had it set to true! I was attempting to use a unsupported Blu-Ray drive a year earlier for PS3 stuff. I thought that option would've been wiped deleting the previous MPF and using a fresh download though. Setting "RedumperUseGenericDriveType" to false fixed my other dump issues as well using the drive. Thanks! I'll mark this as resolved again, this time for real!

**Comment by Deterous** [comment]
If you install new MPF versions by extracting over the top (as we expect you to) then the options are retained via the config.json file, hence why the option was still true
