### ISSUE TITLE
[Request] Auto select "Audio" category when dumping Enhanced CD

### ISSUE THREAD

**Issue by FoxhackDN** [SabreTools/MPF#688]
**Is your feature request related to a problem? Please describe.**
I just dumped a CD, selected Enhanced CD as the platform, but the disc information window had autoselected "Games" as the category.

**Describe the solution you'd like**
Have the program select "Audio" as the category by default.

**Describe alternatives you've considered**
N/A

**Additional context**
No context needed.

**Comment by sadikyo** [comment]
Here are some others:
These should all be Video category by default:
--DVD-Video
--BD-Video
--HDDVD
--VCD
--Tomy Kiss-Site
--VideoNow
--VideoNow Jr.
--VideoNow Color

These should be Multimedia category by default:
--VideoNow XP
--Photo CD
--Sony Electronic Book
