### ISSUE TITLE
[Request] PS4: parse Internal Name from param.sfo

### ISSUE THREAD

**Issue by bikerspade** [SabreTools/MPF#694]
**Is your feature request related to a problem? Please describe.**
Parse the TITLE field from param.sfo.

**Describe the solution you'd like**
Add the parsed UTF-8 title to comments as a value for `<b>Internal Name</b>: `

**Describe alternatives you've considered**
Do nothing.

In the param.sfo example below, the parsed Internal Name would be `Deathsmiles I・II`
![image](https://github.com/SabreTools/MPF/assets/161802532/18698ce7-0f74-49ad-b757-c73e81b3000c)

**Comment by Deterous** [comment]
The scope on this is quite large: PS3, PS4, PS5. Have to search ps3_disc.sfb to see if it is a multi-package system, and print internal name for each package. Some param.sfo have multi-lang titles, or titles with newline characters in them.
Is this really data we want collected in redump?

**Comment by Deterous** [comment]
It was determined that the scope for this is too large for MPF to be doing anything automatically. Some entries may warrant the internal name being added (e.g. multi-package discs or it is significantly different to the redump name) but this would be done manually.
