### ISSUE TITLE
[Problem] MPF Crash with AOE III

### ISSUE THREAD

**Issue by eingrossfilou** [SabreTools/MPF#695]
**Before You Submit**

- Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the issue has already been addressed. 

-> No artifact newer than the stable version available

- Is it copy protection related? If so, report the issue [here](hhttps://github.com/SabreTools/BinaryObjectScanner/issues) instead.

Maybe (there is a typo in the template -> hhttps)

**Version**
What version are you using?

- [x] Stable release (version 3.17)
- [ ] WIP release (version here)  ->  No artifact newer than the stable version available

**Build**
What runtime version are you using?

- [x] .NET 8.0 running on Windows 10

**Describe the issue**
MPF unexpectedly quit when search for protection in disc file.

I observe in the past that this step copies the scanned file in MPF directory. Maybe there is a collision between a file on CD and files in MPF directory. Even if it is not the case, I think it is a bad practice.

**To Reproduce**

1. Put AOE III CD 1 in drive
2. Dump with default parameters (Either DIC or redumper)

**Expected behavior**
Finish protection scanning and ask for disc information 

**Screenshots**
It just quit

**Additional context**

Nothing really informative in event manager apart log the crash dotnet crash

Maybe not related, but older version of MPF that were working few weeks ago crash at startup.
Event manager indicates an exception with OpenClipboard:
```
Exception Info: System.Runtime.InteropServices.COMException (0x800401D0): Échec de OpenClipboard (0x800401D0 (CLIPBRD_E_CANT_OPEN))
```
Look like an update of dotnet breaks some things

**Comment by CookiePLMonster** [comment]
Same issue here - after dumping and scanning of `Speed Pack (Poland)` is done, MPF v3.1.7 simply crashes.

**Comment by mnadareski** [comment]
> Maybe not related, but older version of MPF that were working few weeks ago crash at startup.
Event manager indicates an exception with OpenClipboard

Unrelated.

**Comment by mnadareski** [comment]
Both of you should try the latest WIP here: https://github.com/SabreTools/MPF/releases/tag/rolling. Not every file will get a perfect scan since some executables are obfuscated, but it should not crash the entire dump.

**Comment by CookiePLMonster** [comment]
> Not every file will get a perfect scan since some executables are obfuscated, but it should not crash the entire dump.

I posted the test results of the latest rolling BOS release on Discord, as it was requested there.

**Comment by mnadareski** [comment]
It appears as though it's a standard obfuscated file, especially with the presence of the repeated "expected X got Y" messages. Those usually indicate data that has been deliberately messed with. I'm glad it did not crash. This particular issue is not unique to recent versions of BOS as every executable/library, obfuscated or not, is treated the same and has been for a long time.

More samples of these obfuscated executables are needed to try to avoid the glut of messages, but that particular part of the issue is not likely to change for a while.

**Comment by mnadareski** [comment]
Can either of you confirm if this issue is still happening? I believe that this has been accounted for with the various sets of fixes that have gone into the last release.

**Comment by eingrossfilou** [comment]
Copy protection scan complete (and dump) ends successfully bu using  
`MPF_net8.0-windows_win-x64_debug.zip` built from commit b4d47aea37b2eb8a5141801267f4727e472f35b4 with AOE III CD1
