### ISSUE TITLE
[Request] Dump with multiple tools in one job 

### ISSUE THREAD

**Issue by eingrossfilou** [SabreTools/MPF#699]
It would be useful to be able to select multiple dump tools when dumping a disc. It will help to:
- identify inconsistency between different dump tools (based on hashes),
- avoid to fill the submission info many time for redump.org (and errors), as it is asked now to use both DIC and redumper when dumping. Creating an archive containing both dumps logs will be also useful.

**Comment by Deterous** [comment]
@mnadareski will have the final say, but I suggest that this is out of scope and not a desired feature of MPF.
1. Redump does not require a dump from both DIC and Redumper. Usually, one or the other is fine (currently Audio CD is Redumper only).
2. If you do want to dump using two programs, you can do it twice in MPF and leave the disc submission info empty for the second dump. Assuming the hashes match, you would discard all but the second program's log.
3. This would add a ton of complexity for little to not benefit.

**Comment by mnadareski** [comment]
Please see the following issues for more information as to why this request is not going to be added:
- https://github.com/SabreTools/MPF/issues/183
- https://github.com/SabreTools/MPF/issues/240
- https://github.com/SabreTools/MPF/issues/472
