### ISSUE TITLE
[Problem] PS2 information not pulled (redumper only)

### ISSUE THREAD

**Issue by fuzz6001** [SabreTools/MPF#706]
# Version
- [x] Stable release 3.1.9a (3.1.9-70114ee59e42811664dce687b81da967d88fbf62)

# Build
- [x] .NET 8.0 running on Windows 11

# Describe the issue
Region, EXE Date, ISN and Version are not pulled for PS2.
This problem occurs only with redumper and works fine with dic.

# To Reproduce
1. Dump the PS2 disc
2. Run MPF.Check
```
MPF.Check dvd ps2 --use redumper --path n:\ dump.iso
```

# Expected behavior
Pull information.

# Additional context
<details>
<summary>!submissionInfo.txt</summary>

```
Users who wish to submit this information to Redump must ensure that all of the fields below are accurate for the exact media they have.
Please double-check to ensure that there are no fields that need verification, such as the version or copy protection.
If there are no fields in need of verification or all fields are accurate, this preamble can be removed before submission.

Common Disc Info:
	Title: (REQUIRED)
	Foreign Title (Non-latin): (OPTIONAL)
	Disc Number / Letter: (OPTIONAL)
	Disc Title: (OPTIONAL)
	System: Sony PlayStation 2
	Media Type: DVD-ROM-5
	Category: Games
	Region: SPACE! (CHANGE THIS)
	Languages: SILENCE! (CHANGE THIS)
	Disc Serial: (REQUIRED, IF EXISTS)

	Ringcode Information:

Data Side Mastering Code (laser branded/etched): (REQUIRED, IF EXISTS)
Data Side Mastering SID Code: (REQUIRED, IF EXISTS)
Data Side Toolstamp or Mastering Code (engraved/stamped): (REQUIRED, IF EXISTS)
Data Side Mould SID Code: (REQUIRED, IF EXISTS)
Data Side Additional Mould: (REQUIRED, IF EXISTS)
Label Side Mould SID Code: (REQUIRED, IF EXISTS)

	Barcode: (OPTIONAL)
	Comments: (OPTIONAL)
	Contents: (OPTIONAL)

Version and Editions:
	Version: 
	Edition/Release: (VERIFY THIS) Original

Extras:
	Primary Volume Descriptor (PVD):

0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 32 30 30                200
0330 : 32 30 32 31 36 31 30 30  30 30 30 30 30 24 30 30   2021610000000$00
0340 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 00 30   00000000000000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

Size & Checksum:
	Size: 4220256256
	CRC32: 6e48da5c
	MD5: 13e0764d8c90a71a0afb9a4325474971
	SHA1: 003fc1b60a28ed64ccc3b700b1a127e00fa156c3

Dumping Info:
	Frontend Version: 3.1.9-70114ee59e42811664dce687b81da967d88fbf62
	Dumping Program: Redumper v2024.05.18 build_329
	Date: 2024-05-27 11:27:46
	Manufacturer: ASUS
	Model: BW-16D1HT
	Firmware: 3.02 (W000800KLGK8LF2132)
	Reported Disc Type: DVD-ROM
```
</details>

<details>
<summary>redumper .log</summary>

```
=== 2024-05-27 20:21:58 ========================================================
redumper v2024.05.18 build_329 [May 18 2024, 19:40:51]

arguments: dvd --verbose --drive=n: --speed=16 --retries=20 --image-name=dump

drive path: n:
drive: ASUS - BW-16D1HT (revision level: 3.02, vendor specific: W000800KLGK8LF2132)
drive configuration: LG_ASU3 (read offset: +6, C2 shift: 0, pre-gap start: -135, read method: BE_CDDA, sector order: DATA_C2_SUB)
drive read speed: 22160 KB

current profile: DVD-ROM

image path: .
image name: dump

*** DUMP

disc structure:
  layer 0 { embossed }
    data { LBA: [196608 .. 2257279], length: 2060672, hLBA: [0x030000 .. 0x22717F] }
    book type: DVD-ROM
    part version: 1
    disc size: 120mm
    maximum rate: 10.08 mbps
    layers count: 1
    track path: parallel
    linear density: 0.267 um/bit
    track density: 0.74 um/track
    BCA: no

                                                     

media errors: 
  SCSI: 0

*** REFINE (time check: 274s)


*** DVDKEY

copyright: 
  protection system type: <none>
  region management information: 1 2 3 4 5 6 7 8

*** HASH

dat:
<rom name="dump.iso" size="4220256256" crc="6e48da5c" md5="13e0764d8c90a71a0afb9a4325474971" sha1="003fc1b60a28ed64ccc3b700b1a127e00fa156c3" />

*** INFO

ISO9660 [dump.iso]:
  PVD:
0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 32 30 30                200
0330 : 32 30 32 31 36 31 30 30  30 30 30 30 30 24 30 30   2021610000000$00
0340 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 00 30   00000000000000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

PS2 [dump.iso]:
  EXE: SLPS_251.04
  EXE date: 2002-02-16
  version: 1.05
  serial: SLPS-25104
  region: Japan

*** SKELETON


*** END (time check: 70s)
```
</details>

**Comment by Deterous** [comment]
What does the `*** INFO` section of the redumper log say?

It may be a problem with only partial information obtained from redumper log:
https://github.com/SabreTools/MPF/blob/70114ee59e42811664dce687b81da967d88fbf62/MPF.Core/Modules/Redumper/Parameters.cs#L427
The "fallback" method does not run even if the redumper log is missing some info.

**Comment by fuzz6001** [comment]
> What does the *** INFO section of the redumper log say?

Added .log to the first post.

```
*** INFO

ISO9660 [dump.iso]:
  PVD:
0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 32 30 30                200
0330 : 32 30 32 31 36 31 30 30  30 30 30 30 30 24 30 30   2021610000000$00
0340 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 00 30   00000000000000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

PS2 [dump.iso]:
  EXE: SLPS_251.04
  EXE date: 2002-02-16
  version: 1.05
  serial: SLPS-25104
  region: Japan
```

**Comment by mnadareski** [comment]
Fixed in massive set of changes.

**Comment by JohnVeness** [comment]
Hi. I don't know if it's a partially lingering example of this bug, but I notice that even in 3.2.0, with a PS2 DVD I dump with redumper, MPF.UI (in Windows) correctly puts the region into submissioninfo, but MPF.Check does not (both in Windows and Linux).
[SLES-51252.log](https://github.com/user-attachments/files/16120140/SLES-51252.log)
[!submissionInfo-from-windows-MPFUI.txt](https://github.com/user-attachments/files/16120143/submissionInfo-from-windows-MPFUI.txt)
[!submissionInfo-from-windows-MPFCheck.txt](https://github.com/user-attachments/files/16120144/submissionInfo-from-windows-MPFCheck.txt)
[!submissionInfo-from-linux-MPFCheck.txt](https://github.com/user-attachments/files/16120145/submissionInfo-from-linux-MPFCheck.txt)

**Comment by Deterous** [comment]
> Hi. I don't know if it's a partially lingering example of this bug, but I notice that even in 3.2.0, with a PS2 DVD I dump with redumper, MPF.UI (in Windows) correctly puts the region into submissioninfo, but MPF.Check does not (both in Windows and Linux). [SLES-51252.log](https://github.com/user-attachments/files/16120140/SLES-51252.log) [!submissionInfo-from-windows-MPFUI.txt](https://github.com/user-attachments/files/16120143/submissionInfo-from-windows-MPFUI.txt) [!submissionInfo-from-windows-MPFCheck.txt](https://github.com/user-attachments/files/16120144/submissionInfo-from-windows-MPFCheck.txt) [!submissionInfo-from-linux-MPFCheck.txt](https://github.com/user-attachments/files/16120145/submissionInfo-from-linux-MPFCheck.txt)

MPF does it's own region detection, however it relies on the disc being mounted. That's why Check can't get the region, as Check is passive (only reads logs). Regardless you should be double checking your region manually for redump submissions anyway.

**Comment by JohnVeness** [comment]
Ah thanks. I've just tested further and I see that MPF.Check in Windows *will* detect the region if I add "-p d:" to the command-line while the disc is still in the ODD. However, MPF.Check in Linux still *won't* detect the region even if I do the equivalent (i.e. mount the disc and pass the folder name, like "-p /run/media/john/333d3c3734333d32" in this particular disc's case). I can add this as a separate issue if desired.

Any particular reason you don't parse the region info from the redumper log? Is redumper less accurate?

**Comment by Deterous** [comment]
Yes, the region information from redumper log is not considered to be worthwhile keeping.
