### ISSUE TITLE
[Problem] Wrong matching with Redump.org discs

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#708]
**Version**
What version are you using?

- [X] Stable release (3.1.9a)

**Build**
What runtime version are you using?

- [X] .NET 8.0 running on (W11)

**Describe the issue**
MPF detects a "match" when part of a dump matches one disc and the other part matches another.
i.e. Track 1 matches Disc A, but Tracks 2-11 match Disc B. It detects a match for Disc B, and a partial match for Disc A.

Finding disc matches on Redump...
There were matching ID(s) found for track with SHA-1 of '4b98fff90069ed8fb99493967bf5084cd6f6283c'
There were matching ID(s) found for track with SHA-1 of 'faece86cee40fa62edc8fc85cbe48f2150557619'
There were matching ID(s) found for track with SHA-1 of '6ad10b746c1333e766a6d6041411e5c4b7dc2eed'
There were matching ID(s) found for track with SHA-1 of 'c29c35d0680b45472df5ba218130f13bebd4b64a'
There were matching ID(s) found for track with SHA-1 of 'd06bed076c764525bfd8acee3f52e86bf1b20e98'
There were matching ID(s) found for track with SHA-1 of 'e5e1308bb475ab5d627b2676ed2ed7664c6fe68a'
There were matching ID(s) found for track with SHA-1 of '2f61b8f2603063c0e95f0741fa60c68e2689ba93'
There were matching ID(s) found for track with SHA-1 of 'f10dfe8d3e1835c6f018b02fc6def688d24d497f'
There were matching ID(s) found for track with SHA-1 of '0c269b917cfbd914893c57504c59ae925d6d6c6c'
There were matching ID(s) found for track with SHA-1 of '34547d88d599255356b53b1b0710688e831509d7'
There were matching ID(s) found for track with SHA-1 of 'd9edaf344318674d86e493bebe862b4e65456929'
Match finding complete! Fully Matched IDs: 62721
Filling fields from existing ID 62721...

Track 1 matches http://redump.org/disc/26281/
Tracks 2-11 match http://redump.org/disc/62721/

**Comment by NovaSAurora** [comment]
Replicated on latest WIP

**Comment by mnadareski** [comment]
Should finally be fixed as of https://github.com/SabreTools/MPF/commit/9d5dfaaa68251997bd4386e3e61827b9c2f993cf

**Comment by NovaSAurora** [comment]
Confirmed fixed
