### ISSUE TITLE
[Request] Add dumping tool command / flags to submission info

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#714]
**Is your feature request related to a problem? Please describe.**
Getting info about the dumping tool flags used requires opening the redumper log. Would be nice to have this info more readily available.

**Describe the solution you'd like**
Dumping tool command/flags mentioned in the `Dumping Info:` section of the !submissionInfo.txt file

**Additional context**
Requires an update to RedumpLib. Worth timing this with the potential pseudo-tag mentioned in #713

**Comment by mnadareski** [comment]
Apparently I have had `DumpingParameters` next to `DumpingProgram` for an incredibl ylong time and forgot. So it's available in RedumpLib already. It just needs to be populated in the relevant places, if possible.

**Comment by Deterous** [comment]
Enabled for Redumper and DIC, the two programs that this was requested for.
Support for other dumping programs can be added where needed in the future.
