### ISSUE TITLE
[Problem] When dumping original XBox discs, SS.bin appears in wrong location.

### ISSUE THREAD

**Issue by Emumaddog** [SabreTools/MPF#715]
I have been dumping my original Xbox discs and noticed a relatively minor but weird issue.

SS.bin is always put one level "up" from the dump directory.
So, if I dump e.g. Halo to D:\MPF\ISO\Halo, all dump files are in that directory EXCEPT SS.bin which appears in D:\MPF\ISO and I have to manually put it in the dump directory. PFI and DMI are in the correct directory.

I suppose this is an MPF bug. I don't have any X360 discs to check, but happens with all original XBOX discs I tried. Using latest MPF.UI_3.2.0_net8.0-windows_win-x64_release but bug seems to exist long time, as I tried a few older versions and the same thing happens.

**Comment by Deterous** [comment]
This is supposedly due to DIC, but could you provide logs? I don't see an open issue for DIC about this so will have to tell sarami
