### ISSUE TITLE
[Request] Allow credentials to be loaded from a file

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#718]
**Is your feature request related to a problem? Please describe.**
It's awkward having to add my redump.org username and password to each run of MPF.Check. It's also a little insecure having it visible on the screen.

**Describe the solution you'd like**
I'd like the ability to store the credentials in a file, e.g. ~/.MPF.Check.ini or something. I realise they would still be in plain text so anyone with physical access to the machine will still be able to read them, but at least they won't be easily visible if someone is looking over your shoulder.

**Describe alternatives you've considered**
I guess a small wrapper bash file or similar. Not really looked into it.

**Comment by JohnVeness** [comment]
Actually, should probably be ~/.config/MPF.Check.ini or $XDG_CONFIG_HOME/MPF.Check.ini or equivalent on Windows and macOS. And the file format could be extended to contain other config options too if desired, obviously.

**Comment by mnadareski** [comment]
I am not going to be adding the ability to do this in Check. Check is meant to be scriptable with the intent of using in custom workflows. MPF.CLI takes a full configuration if you need to go that route.

**Comment by JohnVeness** [comment]
Ah thanks, I had completely overlooked MPF.CLI. That looks like it will suit my needs.
