### ISSUE TITLE
[Request] MPF.Check: Add an option to include artifacts

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#726]
**Is your feature request related to a problem? Please describe.**
MPF.Check doesn't have the option to include artifacts in the !submissionInfo.json file, unlike MPF.UI.

**Describe the solution you'd like**
A command-line option to include artifacts, e.g. --include-artifacts.

**Describe alternatives you've considered**
To be honest, I never used the include artifacts option in MPF.UI so this doesn't affect me personally, but I just noticed the inconsistency and thought it worth mentioning!

**Comment by Deterous** [comment]
There's nothing wrong with this per se, but the JSON and artifacts feature is a forward-thinking approach, redump does not yet support it.
