### ISSUE TITLE
[Info] Unsure how to use --load-seed feature in MPF.Check

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#730]
Hi. I am investigating the --load-seed feature in MPF.Check, which at first glance sounds like it will be useful for entering barcodes, ringcodes etc., but I am unsure if I am using it correctly.

I have created a file called !submissionSeed.json containing:
```
{
  "schema_version": 3,
  "common_disc_info": {
    "d_number": "",
    "d_label": "",
    "d_languages": [],
    "d_languages_selection": [],
    "d_serial": "SLES-52017",
    "d_ring_0_ma1": "Sony DADC   A0100486277-A511   17",
    "d_ring_0_ma1_sid": "IFPI L557",
    "d_ring_0_ts1": "B1",
    "d_ring_0_mo1_sid": "IFPI 941Z",
    "d_ring_0_mo1": null,
    "d_ring_0_ma2": null,
    "d_ring_0_mo2_sid": null,
    "d_ring_0_ma3": null,
    "d_ring_0_ma4": null,
    "d_ring_0_offsets": "1",
    "d_ring_count": "1",
    "d_barcode": "5 030930 035105",
    "d_comments": "[T:ISN] SLES-52017\n[T:EAID] EAE03404473IS (Cover), EAE03404073D (Disc), EAE03404073M (Manual)",
    "d_contents": "(I haven't checked this)"
  },
  "versions_and_editions": {
    "d_editions_text": "Original"
  }
}
```

and done:

`MPF.Check dvd ps2 -u redumper -l \!submissionSeed.json LOTRRK.log`

but the resultant !submissionInfo.txt and !submissionInfo.json files are the same as if I hadn't included the -l option, that is, they still have "(REQUIRED, IF EXISTS)" instead of the ringcodes etc. I put in the seed file.

Have I got the format of the seed file correct? Am I doing something wrong? Can the --load-seed feature be documented somewhere?

**Comment by Deterous** [comment]
#731 should enable it but it'll need testing.

**Comment by JohnVeness** [comment]
Thanks. Tested now, but no difference :(

Here's a zip of the output from Redumper (not including the .iso) I'm trying to work with, and the seed file I created, if you want to test yourself:

[LOTRRK.zip](https://github.com/user-attachments/files/16351980/LOTRRK.zip)

**Comment by JohnVeness** [comment]
I've been debugging a little. It seems that `Builder.CreateFromFile(seedInfo)` is returning null, even though seedInfo has the correct filename. I haven't been able to step into that code (I'll probably need to download more source).

**Comment by Deterous** [comment]
RedumpLib will need to be updated to fix this.

**Comment by Deterous** [comment]
@JohnVeness please test this build: https://github.com/Deterous/MPF/releases/tag/rolling

**Comment by JohnVeness** [comment]
Thanks, that seems to be working quite well :)
