### ISSUE TITLE
[Request] MPF.Check: Add seed JSON to compressed log files

### ISSUE THREAD

**Issue by JohnVeness** [SabreTools/MPF#732]
**Is your feature request related to a problem? Please describe.**
Many thanks for recently enabling the seed JSON feature for MPF.Check. I find it very useful to be able to fill in and document the physical attributes of the disc that cannot be determined by redumper, e.g. disc serial, ringcodes etc. Being able to keep it in a file for future reuses of MPF.Check is very useful, e.g. if I dump the same disc on a different drive, or dump it again after an improvement in Redumper or MPF.

The one thing I'd like that isn't currently present is for the seed JSON to be included in the list of files that is zipped up if the -z option is used. This way the file would be "preserved" (e.g. if I upload the logs to archive.org) in the same way that the redumper logs are preserved, making it easier to see in the future which bits of the !submissionInfo.txt/json file came from redumper and which bits were typed in manually by me.

(As I type this I realise that also some bits of !submissionInfo.txt/json file come neither from redumper nor from the seed file, but are pulled from redump.org, and this currently isn't logged in detail anywhere.... maybe it should be, which would presumably require an MPF log file in general).

**Describe the solution you'd like**
The seed JSON file included in the .zip if -z is used in MPF.Check. This might be a little complicated if the seed file is in a different folder than the other log files (that isn't the case for my dumping, but could happen). I'm in two minds as to whether the seed file should be deleted afterwards or not - probably not, to be the same as !submissionInfo.txt/json.

**Describe alternatives you've considered**
Manually adding the seed file to the zip after MPF creates it. This is easy enough, but automation is better!

**Comment by mnadareski** [comment]
Request denied.

**Comment by JohnVeness** [comment]
I see it a bit like a "source" file, in the same way we zip up all the various logs and hashes and skeletons and so on. But as you wish!

**Comment by mnadareski** [comment]
The files you mention are generated by the dumping program. All of the info in a seed JSON ends up in the submission info.
