### ISSUE TITLE
[Request] remove ":\" from --drive redumper parameter

### ISSUE THREAD

**Issue by bikerspade** [SabreTools/MPF#734]
**Is your feature request related to a problem? Please describe.**
Not a problem. Just use of correct syntax.

**Describe the solution you'd like**
Instead of populating the redumper parameters as `--drive=X:\`, populate it as `--drive=X`

**Comment by mnadareski** [comment]
Unless this ends up being a breaking issue with Redumper, we will not be pursuing a fix to this.
