### ISSUE TITLE
[Request] Detect BEE BD-Video Protection

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#735]
BEE (Bus Encryption Enabled) is a feature on certain drives that encrypts the audio-visual files present on certain blu-ray discs.
The data on the disc itself is not encrypted, so it is useful for MPF to detect whether a disc has BEE enabled and if so, print it to the submission info.

Of note for redump, we would be able to see this BEE flag and check with the drive model and with the dumper as to whether the BD-Video dump is good (no encryption, identical to disc) or bad (has been encrypted by the drive).

Detection can be done by checking whether the first bit of the second byte of `AACS/Content000.cer` is 1 (enabled) or 0 (disabled). If `AACS/Content000.cer` is not present or has size=0bytes, then the same check can be run on `AACS/Content001.cer`
That is, MPF needs to open `AACS/Content000.cer` file (`AACS/Content001.cer` if 000 size=0), read the second byte (`data[1]`). If `> 127` then BEE is enabled, otherwise it is not.

**Comment by mnadareski** [comment]
Addressed by https://github.com/SabreTools/MPF/commit/33c35b63d7bc08084d235d67fba1954afdb12f06, https://github.com/SabreTools/MPF/commit/cfc75ca84d232140b47ca22776ab3cf187ca2443, and https://github.com/SabreTools/MPF/commit/135bb43cdfa878213c1c61ac745959c84b775cc6
