### ISSUE TITLE
[Request] UmdImageCreator extra support

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#742]
Newer versions of UIC output a _PFI.bin file so this can be uncommented: (and any other instances for optional output files)
https://github.com/SabreTools/MPF/blob/135bb43cdfa878213c1c61ac745959c84b775cc6/MPF.Processors/UmdImageCreator.cs#L64-L65

Also, UmdImageCreator has internal serial in *_disc.txt that needs parsing e.g.
```
disc0:/PSP_GAME/PARAM.SFO
	magic: PSF
	version: 1.01
	APP_VER: 01.00
	BOOTABLE: 1
	CATEGORY: UG
	DISC_ID: ULJM05692
	DISC_NUMBER: 1
	DISC_TOTAL: 1
...
```
DISC_ID: ULJM05692 needs a hyphen inserted, ULJM-05692

**Comment by mnadareski** [comment]
PFI is commented out in artifacts in DIC as well. It's already included in the zip.
