### ISSUE TITLE
[Request] Ignore useless volume labels

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#744]
Currently MPF outputs ISO volume labels that are useless, e.g. `[T:VOL] Young, YOUNG (ISO)` or `[T:VOL] LIVINGFACTORY (ISO), LivingFactory (Joliet)`

TODO: Add logic to delete useless volume labels. Compare them after removing spaces/underscores and normalising case. Drop empty volume labels after this. And ensure that if only one volume label is left, don't add the brackets

e.g. the output after this should be 
`[T:VOL] Young` and ``[T:VOL] LivingFactory`

**Comment by NovaSAurora** [comment]
Strongly request a toggle in options to include them anyway. I'd like to still have them and having it off by default will let the mods be happy.

**Comment by mnadareski** [comment]
Is there a preferred order to the "accepted" labels? Like does Windows always take precedence over Joliet? Or if they match (ignoring case), is it always the one that includes at least one lower-case character?

**Comment by Deterous** [comment]
Windows > UDF > ISO > Joliet
Honestly I've only seen bad results from the joliet label. Maybe it's coded wrong for DIC log parsing..? (my fault if so)

**Comment by mnadareski** [comment]
The current formatting code doesn't take into account where the labels are coming from when formatting. It just assumes that they're organized properly. That is, there is no actual distinction between UDF, ISO, and Joliet when the formatting happens. If we go with the hierarchy, that will require special checking cases. Also worth noting that it actually doesn't do any sort of comparisons between labels at the moment.

**Comment by mnadareski** [comment]
As discussed in Discord, part of the issue here is needing to rebuild the current mapping dictionary based on the "correct" labels. For a human user, this is nearly trivial to point out, regardless of what the source of the label is. For a computer, it's a bit harder, since either the key in the dictionary needs to be normalized OR a separate mapping needs to be made from the key to the "real label". Neither of these are trivial to implement and neither scales particularly well.

**Comment by Deterous** [comment]
Currently, `labels` exists as a mapping of actual volume labels to zero or more filesystem names ("ISO", "Joliet", "UDF", "UNKNOWN")
It should be possible to compare the volume labels and pick the one with the better filesystem. There is no need to determine which is better through heuristics (which has case sensitivity, etc).

For example:
`labels` = a mapping of "EXAMPLE_DISC" = (ISO, Joliet) and "Example Disc" = (UDF)
1. Drop all underscores, spaces, and unicode (foreign language characters) from both labels
2. Compare without case sensitivity `string.Equals(a, b, StringComparison.OrdinalIgnoreCase)`
3. If they are equal, look at the filesystems that the labels are attached to and drop the one that is lower in the heirarchy, in this case UDF is kept over ISO+Joliet. If a label does not have a filesystem, that one is chosen (i.e. it is the Windows one).
4. Repeat for all remaining labels in the mapping

**Comment by mnadareski** [comment]
You're proposing a static readonly list that defines the hierarchy. It also seems like you're suggesting the "highest ranked" out of each set of label sources would be considered.

**Comment by Deterous** [comment]
Another request as part of this: don't put *any* volume labels in submissionInfo for Xbox/Xbox360.

**Comment by mnadareski** [comment]
Initial filtering has been added. Additional, smarter filtering taking the source into account is needed.

**Comment by Deterous** [comment]
#780 / #781 has implemented what I wanted, so I'm closing this issue. A TODO remains in the code if someone wants to do this "properly", but the cases where the current implementation falls short are currently rare and will not occur with Redumper logs at all.

In cases where the ISO9660 volume label is superficially different, it will no longer appear in the submission info, but the Redumper .log file still has the ISO9660 volume label if this is ever desired.
