### ISSUE TITLE
[Problem] Audio|Data Multisession Mac CDs detect as Audio CD

### ISSUE THREAD

**Issue by NovaSAurora** [SabreTools/MPF#751]
**Version**
What version are you using?

- [X] Stable release (3.2.2)

**Build**
What runtime version are you using?

- [X] .NET 6.0 running on (W11)

**Describe the issue**
When dumping a Mac CD that is formatted as a Multisession CD, if the data partition is HFS, MPF doesn't see it, and sets system as Audio CD.

e.g.:
Session 1
Track 1: Audio
Track 2: Audio
Track 3: Audio
Session 2
Track 4: Data (HFS)

**Comment by mnadareski** [comment]
Unfortunately, unless Windows can see a data partition, it will automatically create a "label" of `Audio CD`. There is basically nothing that I can do to get around this without circumventing Windows, which would be a massive effort.
