### ISSUE TITLE
[Problem/Request] Trimmed Saturn header

### ISSUE THREAD

**Issue by fuzz6001** [SabreTools/MPF#754]
better not to trim
Rolling Release 172a0fb

# redumper log
![panzer_redumper](https://github.com/user-attachments/assets/33150d43-684a-4bbe-bb90-d86539d21b74)

# !submissionInfo.txt

![panzer_mpf](https://github.com/user-attachments/assets/26fbb6bf-36d5-4cd8-8ae4-4e6242c3e191)

**Comment by mnadareski** [comment]
Both of those images appear to be identical? I'm assuming the second is supposed to be different.

**Comment by Deterous** [comment]
> Both of those images appear to be identical? I'm assuming the second is supposed to be different.

The second one (MPF output) trims the whitespace in the ASCII area

**Comment by mnadareski** [comment]
I could barely notice that. Thank you for the clarification.

**Comment by fuzz6001** [comment]
I'm sorry I didn't explain it enough. 
Thank you for the correction.
