### ISSUE TITLE
[Request] Change default value of Submission Text for Languages

### ISSUE THREAD

**Issue by 7Seventy7** [SabreTools/MPF#756]
Change the default value of Submission Text for Langauges from "SILENCE..." to "ADD LANGUAGES HERE (ONLY IF YOU TESTED)"

**Comment by Deterous** [comment]
@mnadareski is this something you would consider changing? 
If so, RedumpLib will need changing:
https://github.com/SabreTools/SabreTools.RedumpLib/blob/2b75eb44cda1527a4b098bb4880d2fe85b3701c6/SabreTools.RedumpLib/Formatter.cs#L271
https://github.com/SabreTools/SabreTools.RedumpLib/blob/2b75eb44cda1527a4b098bb4880d2fe85b3701c6/SabreTools.RedumpLib.Test/FormatterTests.cs#L25

**Comment by mnadareski** [comment]
Since I'm updating the library anyway, I have added this as of https://github.com/SabreTools/SabreTools.RedumpLib/commit/8b147f2041d9b52fdc4b34083c387f9d542668a2
