### ISSUE TITLE
[Discussion] Skeleton by default for non-bluray

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#758]
Now that redumper does not create skeletons by default, MPF should probably append skeleton to the redumper command. Not creating skeletons by default for blu-ray discs will avoid long dumping times and bad skeletons with UDF. Additionally, DVD-Video is also currently known to create bad skeletons. There may be more system-media combos that we want to avoid skeletons for?

**Comment by mnadareski** [comment]
Personally, I don't want to include by default _or_ include a configuration option to include skeletons until I can get confirmation on why they were removed from default dumping to begin with. If I add either of those, I risk using a feature that might get deprecated or removed.

**Comment by Deterous** [comment]
From the horses mouth:

> it often errors out and people think dump failed with error
it's so slow for dvd+
it's easy to do that externally with redumper cd skeleton ...

That is to say, its intended use is as I'm suggesting (append the command), and the reasons I suggest not to run skeleton for DVD-Video and all bluray is why it was removed by default.

**Comment by mnadareski** [comment]
Given the information above I believe that adding `skeleton` to CDs only is safe. I feel it is reasonable to stay that way by default until Redumper adds it back.

**Comment by Deterous** [comment]
> until Redumper adds it back.

I'm not sure it will ever be added back by default.
