### ISSUE TITLE
[Problem] PS3 Firmware not added to submission 

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#764]
Currently firmware is being checked against SiteCode.Patches existing in Comments, but it's in Contents. Either an equivalent contents function needs to exist or this needs to be an exception.
https://github.com/SabreTools/MPF/blob/19d6006aff287127e6f3d1034072efb63f2b2f32/MPF.Frontend/Tools/SubmissionGenerator.cs#L831

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/59a427963d61bb7852b0e6b3d7ab811020b6615a
