### ISSUE TITLE
[Problem] DIC's basename_YYYYMMDDTHHMMSS.txt isn't zipped

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#767]
Had a look and can't decode your new output files framework to find what's going wrong, but `dump_20241001T225411.txt` isn't zipped despite it clearly matching the regex below and is flagged as Zippable.

```cs
new RegexOutputFile(Regex.Escape(baseFilename) + @"_(\d{8})T\d{6}\.txt", OutputFileFlags.Required
                            | OutputFileFlags.Artifact
                            | OutputFileFlags.Zippable,
                            "cmd"),
```

Somewhere in https://github.com/SabreTools/MPF/blob/e72336a835c61df8636d15b0f4d768ec2c567446/MPF.Processors/BaseProcessor.cs#L521 it must be not getting the correct filename. Maybe you can spot what's wrong without having to debug this.

**Comment by Deterous** [comment]
The issue seems to be that RegexOutputFile isn't returning valid filenames, but instead the regex itself.

**Comment by Deterous** [comment]
This also affects XBC log files, which has occurred in the past (previously unconfirmed whether bug or user error)

**Comment by mnadareski** [comment]
Implementation note: Do not blindly return lists, take output type into account. All currently treated as standard.

**Comment by mnadareski** [comment]
Confirmed to have been fixed in a real-world test.
