### ISSUE TITLE
[Problem] MPF 3.2.4 fails to add PIC into submissioninfo.txt for Blu-ray discs

### ISSUE THREAD

**Issue by noigeaR** [SabreTools/MPF#769]
**Version**
What version are you using?

- [x] Stable release MPF.UI_3.2.4_net9.0-windows_win-x64_release.zip 
- [ ] WIP release (version here)

**Build**
What runtime version are you using?

- [x] .NET 9.0 running on Windows 11

**Describe the issue**
When dumping Blu-ray discs with either Redumper or DIC, the PIC information doesn't get added to submissioninfo.txt anymore. This is a regression for 3.2.4 (still works with 3.2.3).

**To Reproduce**
Dump a Blu-ray disc with MPF 3.2.4.
Tested with dumping both BD-50 and BD-25 video discs with Redumper and DIC and BD-25 PS4 disc with Redumper.
.physical file for dumps with Redumper and PIC.bin for DIC dumps are created and added to log.zip, but PIC section in submissioninfo.txt stays empty.

**Expected behavior**
PIC should be pulled from .physical file for Redumper or PIC.bin for DIC and added to submissioninfo.txt

**Comment by sadikyo** [comment]
Just adding that it seems to do the same thing with PS3 discs.  Probably not too surprising but figured I'd add.

**Comment by mnadareski** [comment]
Confirmed to have been fixed by @Deterous after trying a few PS3 games on latest.
