### ISSUE TITLE
[Problem] MPF incorrectly looks for SS.bin/.security for XboxOne/XboxSX

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#770]
Currently, Processors/DIC and Processors/Redumper look for _SS.bin and .security respectively, based on `system.IsXGD()`
This works for Xbox/Xbox360, but incorrectly flags XboxOne and XboxSX as dumps that need _SS.bin/.security, so any dumps with them will fail.
Either RedumpLib needs an update to remove XboxOne/XboxSX from the IsXGD() function, or a more precise check is needed in MPF.Processors

**Comment by mnadareski** [comment]
For Redumper, the code indicates that it only looks for `.security` for DVD. I was under the impression that all XGD4 discs are Blu-ray, so this should be a non-issue. If you can demonstrate it looking for the file on an XGD4 disc, I will investigate further.

For DIC, the checks for Blu-ray have been split out and `_SS.bin` has been removed from that set. Thank you for the catch there. The fix went in as of https://github.com/SabreTools/MPF/commit/ee4e77b208dd93f3765d802f81e63efb1f6693e3

**Comment by Deterous** [comment]
As long as XboxOne / XboxSX never gets a DVD media added.

Also a todo before this is closed: figure out a way to check whether SS is necessary at all, some Xbox DVDs don't need SS.

**Comment by Deterous** [comment]
if (Xbox || Xbox360) && (DVD) && (DMI.Any(x => x != 0))

Then required .security


For redumper, if .dmi doesn't exist, you'll need to skip the first 4 bytes of the .manufacturer then check if any of the rest are non-zero

**Comment by mnadareski** [comment]
Further enhancement has been split into https://github.com/SabreTools/MPF/issues/774
