### ISSUE TITLE
[Problem] Trailing Period prevents MPF from finding redumper output

### ISSUE THREAD

**Issue by hughobrien** [SabreTools/MPF#772]
**Version**
What version are you using?

Stable 3.2.4

**Build**
What runtime version are you using?
3.2.4_NET9.0

- [X] .NET 9.0 running on Win11

**Describe the issue**
Trailing period in filename but not seemingly in the file path MPF is looking for

**To Reproduce**
Dump with trailing period, in my case, `F.E.A.R.`

**Expected behavior**
Filename sanitization probably.

**Screenshots**
![Screenshot 2024-12-05 013649](https://github.com/user-attachments/assets/2d1acedc-84e1-4afa-a870-a5555e6c6ce8)

**Comment by mnadareski** [comment]
Was this on latest or on last stable? If it was on last stable, please try the [latest WIP](https://github.com/SabreTools/MPF/releases/tag/rolling) and see if this issue still occurs. There were quite a few things updated behind the scenes and I could not replicate this behavior purely from the internal side.

**Comment by hughobrien** [comment]
Confirmed an issue on `MPF.UI_3.2.4_net9.0-windows_win-x64_release` but thankfully also confirmed the latest WIP handles it correctly. Thank you.
