### ISSUE TITLE
[Request] Remove Packer info from submission info

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#776]
Change options.ScanPackersForProtection to only output packer info to the protection info output text file. Packer info does not belong in submissionInfo.txt as it is not stored in redump.

**Comment by mnadareski** [comment]
This has been band-aid fixed by hard-coding exclusion lists for packers into the current filtering.

**Comment by TonyLizard** [comment]
Please also add the EA Online Registration to the list of elements that should not be showed in submissionInfo.txt file.

**Comment by mnadareski** [comment]
EA CD-key will be filtered out alongside packers and game engines now. I will leave this issue open for a couple of days in case others are found.

**Comment by Deterous** [comment]
It may be cleaner to have a list of prefixes to exclude stored somewhere, and loop through all of them in the filtering code to exclude them with `FindAll(p => !p.StartsWith(x)`. This would make maintaining the list easier (every time BOS adds new detections).
Of course the existing, more advanced filtering to remove duplicates can remain.

**Comment by mnadareski** [comment]
All cases that needed to be covered seem to be for now.
