### ISSUE TITLE
[Problem] Interacting with UI during protection scan re-enables the start dumping button

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#787]
- Start Protection Scan, and the controls are disabled:
![image](https://github.com/user-attachments/assets/6e014009-4de4-44ac-afa5-442ef38eea0d)

- Next, change any of the options (Dumping program, system, media type, etc)
- The Start Dumping button is now enabled, allowing you to start a dump during a protection scan
![image](https://github.com/user-attachments/assets/da548dca-4059-4061-a309-24681fa89cc1)

Pressing the start dumping button while protection scan is going can cause conflicts, so this shouldn't be able to be enabled during a scan. Easiest would be to disable all controls during a scan.

**Comment by mnadareski** [comment]
Fixed by https://github.com/SabreTools/MPF/commit/0ff1753aa239f112f0134e92736542ba9c1d12d3
