### ISSUE TITLE
[Problem] Fix threading - MPF unresponsive during log compression 

### ISSUE THREAD

**Issue by Deterous** [SabreTools/MPF#793]
MPF can take a few seconds or more to compress the log files. While it is doing so, the status is "Waiting for additional information.." (which is not the intended message), and the UI window cannot be moved, causing windows to think the app is unresponsive.

The threading at this point in the code needs fixing (such that the status is displayed properly) and so that the UI window remains responsive.

**Comment by mnadareski** [comment]
This should be taken care of as of https://github.com/SabreTools/MPF/commit/ce9c6d1f52104a2ce5ef5013bc36033ba57edb63. The discussion around this issue largely took place in Discord and involved a lot of back-and-forth testing of different possible solutions. This one surprised us and seemed to have worked.
